(function(g){var window=this;'use strict';var eM=function(N){N.publish("cardstatechange",N.q3()&&N.MD()?1:0)},EL=function(N,h){var O=g.DK(h),u=O?h:arguments;
for(O=O?0:1;O<u.length;O++){if(N==null)return;N=N[u[O]]}return N},NVK=function(N){var h=g.Nr(N);
N=g.ui(N);return new g.Ty(h.x,h.y,N.width,N.height)},hM5=function(N,h,O){var u=u===void 0?{}:u;
var D;return D=g.KE(N,h,function(){g.mB(D);O.apply(N,arguments)},u)},qY=function(N){N=g.G5(N);
delete cq[N];g.ox(cq)&&aZ&&aZ.stop()},uER=function(){aZ||(aZ=new g.YL(function(){OnS()},20));
var N=aZ;N.isActive()||N.start()},OnS=function(){var N=g.Aj();
g.kY(cq,function(h){DdY(h,N)});
g.ox(cq)||uER()},gs=function(N,h,O,u){g.b9.call(this);
if(!Array.isArray(N)||!Array.isArray(h))throw Error("Start and end parameters must be arrays");if(N.length!=h.length)throw Error("Start and end points must be the same length");this.W=N;this.B=h;this.duration=O;this.L=u;this.coords=[];this.progress=this.V=0;this.X=null},DdY=function(N,h){h<N.startTime&&(N.endTime=h+N.endTime-N.startTime,N.startTime=h);
N.progress=(h-N.startTime)/(N.endTime-N.startTime);N.progress>1&&(N.progress=1);N.V=1E3/(h-N.X);N.X=h;Udr(N,N.progress);N.progress==1?(N.G=0,qY(N),N.onFinish(),N.ev()):N.isPlaying()&&N.Vx()},Udr=function(N,h){typeof N.L==="function"&&(h=N.L(h));
N.coords=Array(N.W.length);for(var O=0;O<N.W.length;O++)N.coords[O]=(N.B[O]-N.W[O])*h+N.W[O]},ddY=function(N,h){g.lB.call(this,N);
this.coords=h.coords;this.x=h.coords[0];this.y=h.coords[1];this.z=h.coords[2];this.duration=h.duration;this.progress=h.progress;this.fps=h.V;this.state=h.G},rs=function(N,h,O,u,D){gs.call(this,h,O,u,D);
this.element=N},Gfx=function(N,h,O,u,D){if(h.length!=2||O.length!=2)throw Error("Start and end points must be 2D");
rs.call(this,N,h,O,u,D)},bnY=function(N){return Math.pow(N,3)},inR=function(N){return 3*N*N-2*N*N*N},BVx=function(N){g.S.call(this);
this.W=N||window;this.G=[]},sL=function(N){return N.baseUrl||null},JM=function(N,h){return g.pe(g.KR(N,h),function(O){return!!O})},Ct4=function(N,h,O){function u(bY){var BR=bY.hovercardButton;
if(!BR)return null;BR=BR.subscribeButtonRenderer;if(!BR)return null;var oe=U(BR.unsubscribedButtonText),Oa=U(BR.subscribedButtonText);if(BR.subscribed){var Ea=U(BR.subscriberCountWithUnsubscribeText);var nx=U(BR.subscriberCountText)}else Ea=U(BR.subscriberCountText),nx=U(BR.subscriberCountWithSubscribeText);var or=null;if(bY.signinEndpoint){or=EL(bY,"signinEndpoint","webNavigationEndpointData","url");if(!or){var CS,fx;or=(fx=g.X((CS=BR.signInEndpoint)==null?void 0:CS.commandMetadata,g.$8))==null?
void 0:fx.url}if(!or)return null}return oe&&(Oa||or)?{subscribed:BR.subscribed,subscribeText:oe,subscribeCount:Ea,unsubscribeText:Oa,unsubscribeCount:nx,enabled:BR.enabled,signinUrl:or,classic:bY.useClassicSubscribeButton}:null}
function D(bY){if(bY){var BR=[],oe=bY.videoId;oe&&BR.push("v="+oe);(oe=bY.playlistId)&&BR.push("list="+oe);(bY=bY.startTimeSeconds)&&BR.push("t="+bY);return"/watch?"+BR.join("&")}}
function U(bY){if(!bY)return null;var BR=bY.simpleText;return BR?BR:bY.runs?g.KR(bY.runs,function(oe){return oe.text}).join(""):null}
h=h.endscreenElementRenderer;if(!h)return null;var d=h.style,b=h.endpoint||{},B=null,C=null,A=!1,Q=null,L=null,z=null,v=null,t=!1,R=null,p=null,M=null,a=null,J=null,W=null;if(d==="VIDEO")g.X(b,g.qP)?B=g.X(b,g.qP).url:(W=g.X(b,g.Vi),B=D(W)),C=!1,Q=N,h.thumbnailOverlays?(A=h.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,L=U(A.text),A=A.style==="LIVE"):L=U(h.videoDuration);else if(d==="PLAYLIST")g.X(b,g.qP)?B=g.X(b,g.qP).url:(W=g.X(b,g.Vi),B=D(W)),C=!1,Q=N,z=U(h.playlistLength);else if(d===
"CHANNEL"){if(t=EL(b,"browseEndpoint","browseId"))v=t,B="/channel/"+v;C=!1;Q="new";(t=!!h.isSubscribe)?R=u(h):p=U(h.subscribersText)}else d==="WEBSITE"?((M=EL(b,"urlEndpoint","url"))&&(B=M),C=!0,Q="new",M=h.icon.thumbnails[0].url):d==="CREATOR_MERCHANDISE"&&(h.productPrice&&(a=U(h.productPrice)),h.additionalFeesText&&(J=U(h.additionalFeesText)),(C=EL(b,"urlEndpoint","url"))&&(B=C),C=!0,Q="new");N=EL(h,"title","accessibility","accessibilityData","label");var F=h.endpoint?h.endpoint.clickTrackingParams:
null,l="";if(h.metadata){var iY=U(h.metadata);iY&&(l=iY)}return{id:"element-"+O,type:d,title:U(h.title),metadata:l,callToAction:U(h.callToAction),Sz:h.image,iconUrl:M,left:Number(h.left),width:Number(h.width),top:Number(h.top),aspectRatio:Number(h.aspectRatio),startMs:Math.floor(Number(h.startMs)),endMs:Math.floor(Number(h.endMs)),videoDuration:L,TR:A,playlistLength:z,channelId:v,subscribeButton:R,subscribersText:p,isSubscribe:t,targetUrl:B||null,E5:C,sessionData:F?{itct:F}:null,zAn:Q,On:N?N:null,
isPlaceholder:h.isPlaceholder,impressionUrls:JM(h.impressionUrls||[],sL),NF:JM(h.hovercardShowUrls||[],sL),clickUrls:JM(b.loggingUrls||[],sL),visualElement:g.vN(h.trackingParams),productPrice:a,additionalFeesText:J,watchEndpoint:W||null}},A4S=function(N,h){var O={startMs:Math.floor(Number(N.startMs)),
impressionUrls:JM(N.impressionUrls||[],sL),elements:JM(N.elements||[],function(u,D){return Ct4(h,u,D)})};
N.trackingParams&&(O.visualElement=g.vN(N.trackingParams));return O},o_V=function(N){g.Vq.call(this,N);
this.X=this.endscreen=null;this.W={};this.V={};this.L=this.U=null;this.Y=[];this.G=null;this.eS=!0;this.B=0;N=N.K();this.D=g.iM(N)||g.CK(N);this.events=new g.yg(this);g.H(this,this.events);this.events.J(this.player,g.xm("creatorendscreen"),this.onCueRangeEnter);this.events.J(this.player,g.np("creatorendscreen"),this.onCueRangeExit);this.events.J(this.player,"resize",this.x6);this.events.J(window,"focus",this.Zgi);this.load();var h=g.LF("STYLE");(g.dX("HEAD")[0]||document.body).appendChild(h);this.addOnDisposeCallback(function(){g.mq(h)});
h.sheet&&(h.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),h.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Qmm=function(N){return N.player.getVideoData().E8?"current":N.D?"new":"current"},jM=function(N){return N.player.K().playerStyle==="creator-endscreen-editor"},LdS=function(N){var h=N.player.getVideoData(),O=h.videoId;
N.X&&N.X.abort();O={method:"POST",onFinish:function(D){var U=N.X=null;D.status===200&&(D=D.responseText,D.substring(0,3)===")]}"&&(D=D.substring(3),U=JSON.parse(D),U=A4S(U,Qmm(N))));SM(N,U)},
urlParams:{v:O},withCredentials:!0};N.D&&(O.urlParams.ptype="embedded");var u=h.ra;u&&(O.postParams={ad_tracking:u});if(h=g.xFY(h))if(h=g.b_(h),h=g.U3(h))N.X=g.tY(h,O)},SM=function(N,h,O){O=O===void 0?!0:O;
N.player.SV("creatorendscreen");N.U&&(N.U.dispose(),N.U=null,N.L.dispose(),N.L=null);for(var u=g.I(Object.values(N.W)),D=u.next();!D.done;D=u.next())D.value.dispose();N.W={};N.V={};N.Y.length>0&&(N.Y.forEach(function(b){b.dispose()}),N.Y.length=0);
N.G&&(g.UC(N.G,"ytp-ce-element-show"),N.G.setAttribute("aria-hidden","true"));N.B=0;if((N.endscreen=h)&&h.elements){O&&zMY(N);O=[];u=new g.Ym(h.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});O.push(u);N.player.K().W||(N.U=new g.f({T:"div",N:"ytp-ce-shadow"}),g.O9(N.player,N.U.element,4),N.L=new g.ka(N.U,200));for(u=0;u<h.elements.length;++u){D=h.elements[u];var U=v_K(N,D);if(U){N.W[D.id]=U;N.V[D.id]=D;g.O9(N.player,U.element,4);var d=new g.Ym(D.startMs,D.endMs,{id:"ytp-ce-element-"+
D.id,namespace:"creatorendscreen"});O.push(d);wkS(N,U,D)}else g.pX(new g.H5("buildEndscreenElement null",D))}N.player.Vq(O);N.x6()}},zMY=function(N){var h=g.KX(),O=g.m7();
O&&h&&N.endscreen.visualElement&&g.lu(g.HN)(void 0,O,h,N.endscreen.visualElement)},v_K=function(N,h){var O=null;
switch(h.type){case "VIDEO":N={T:"div",M5:["ytp-ce-element","ytp-ce-video"],Z:{tabindex:"0","aria-label":h.On||"","aria-hidden":"true"},C:[{T:"div",N:"ytp-ce-element-shadow"},{T:"div",N:"ytp-ce-covering-image",Z:Hq(h)},{T:"div",N:"ytp-ce-covering-shadow-top"},{T:"a",N:"ytp-ce-covering-overlay",Z:{href:TB(N,h.targetUrl),tabindex:"-1"},C:[{T:"div",M5:["ytp-ce-video-title","ytp-webkit-ellipsis"],Z:{dir:g.oJ(h.title||"")},WB:h.title},{T:"div",N:h.TR?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
WB:h.videoDuration||void 0}]}]};O=new g.f(N);break;case "PLAYLIST":N={T:"div",M5:["ytp-ce-element","ytp-ce-playlist"],Z:{tabindex:"0","aria-label":h.On||"","aria-hidden":"true"},C:[{T:"div",N:"ytp-ce-element-shadow"},{T:"div",N:"ytp-ce-covering-image",Z:Hq(h)},{T:"div",N:"ytp-ce-covering-shadow-top"},{T:"a",N:"ytp-ce-covering-overlay",Z:{href:TB(N,h.targetUrl),tabindex:"-1"},C:[{T:"div",M5:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Z:{dir:g.oJ(h.title||"")},WB:h.title},{T:"div",N:"ytp-ce-playlist-count",
C:[{T:"div",N:"ytp-ce-playlist-icon"},{T:"div",N:"ytp-ce-playlist-count-text",WB:h.playlistLength||void 0}]}]}]};O=new g.f(N);break;case "CHANNEL":O={T:"div",M5:["ytp-ce-element","ytp-ce-channel",h.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Z:{tabindex:"0","aria-label":h.On||"","aria-hidden":"true"},C:[{T:"div",N:"ytp-ce-element-shadow"},{T:"div",N:"ytp-ce-expanding-overlay",C:[{T:"div",N:"ytp-ce-expanding-overlay-hider"},{T:"div",N:"ytp-ce-expanding-overlay-background"},{T:"div",N:"ytp-ce-expanding-overlay-content",
C:[{T:"div",N:"ytp-ce-expanding-overlay-body",C:[{T:"div",N:"ytp-ce-expanding-overlay-body-padding",C:[{T:"a",M5:["ytp-ce-channel-title","ytp-ce-link"],Z:{href:TB(N,h.targetUrl),target:"_blank",tabindex:"-1",dir:g.oJ(h.title||"")},WB:h.title},h.subscribeButton?{T:"div",N:"ytp-ce-subscribe-container",C:[{T:"div",N:"ytp-ce-channel-subscribe"}]}:"",h.subscribersText?{T:"div",N:"ytp-ce-channel-subscribers-text",WB:h.subscribersText}:"",h.metadata?{T:"div",M5:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],WB:h.metadata}:""]}]}]}]},{T:"div",N:"ytp-ce-expanding-image",Z:Hq(h)}]};O=new g.f(O);var u=g.bD(document,"div","ytp-ce-channel-subscribe",O.element)[0];if(h.subscribeButton&&h.channelId){g.u9(u,"ytp-ce-subscribe-button");if(N.player.K().W){var D=null;var U=h.sessionData.itct}else D="endscreen",U=null;D=new g.UG(h.subscribeButton.subscribeText,h.subscribeButton.subscribeCount,h.subscribeButton.unsubscribeText,h.subscribeButton.unsubscribeCount,!!h.subscribeButton.enabled,!!h.subscribeButton.classic,
h.channelId,!!h.subscribeButton.subscribed,D,U,N.player,!1);u.appendChild(D.element);N.Y.push(D)}break;case "WEBSITE":N={T:"div",M5:["ytp-ce-element","ytp-ce-website"],Z:{tabindex:"0","aria-label":h.On||"","aria-hidden":"true"},C:[{T:"div",N:"ytp-ce-element-shadow"},{T:"div",N:"ytp-ce-expanding-overlay",C:[{T:"div",N:"ytp-ce-expanding-overlay-hider"},{T:"div",N:"ytp-ce-expanding-overlay-background"},{T:"div",N:"ytp-ce-expanding-overlay-content",C:[{T:"div",N:"ytp-ce-expanding-overlay-body",C:[{T:"div",
N:"ytp-ce-expanding-overlay-body-padding",C:[{T:"div",N:"ytp-ce-website-title",Z:{dir:g.oJ(h.title||"")},WB:h.title},{T:"div",N:"ytp-ce-website-metadata",WB:h.metadata},{T:"a",M5:["ytp-ce-website-goto","ytp-ce-link"],Z:{href:TB(N,h.targetUrl),target:"_blank",tabindex:"-1"},WB:h.callToAction}]}]}]}]},{T:"div",N:"ytp-ce-expanding-image",Z:Hq(h)},{T:"div",N:"ytp-ce-expanding-icon",Z:KdY(h.iconUrl)}]};O=new g.f(N);break;case "CREATOR_MERCHANDISE":O="",h.productPrice&&(O={T:"div",N:"ytp-ce-merchandise-price-container",
C:[{T:"div",N:"ytp-ce-merchandise-price",WB:h.productPrice}]},h.additionalFeesText&&O.C.push({T:"div",N:"ytp-ce-merchandise-additional-fees",WB:h.additionalFeesText})),N={T:"div",M5:["ytp-ce-element","ytp-ce-merchandise"],Z:{tabindex:"0","aria-label":h.On||"","aria-hidden":"true"},C:[{T:"div",N:"ytp-ce-element-shadow"},{T:"div",N:"ytp-ce-expanding-overlay",C:[{T:"div",N:"ytp-ce-expanding-overlay-hider"},{T:"div",N:"ytp-ce-expanding-overlay-background"},{T:"div",N:"ytp-ce-expanding-overlay-content",
C:[{T:"div",N:"ytp-ce-expanding-overlay-body",C:[{T:"div",N:"ytp-ce-expanding-overlay-body-padding",C:[{T:"div",N:"ytp-ce-merchandise-title",Z:{dir:g.oJ(h.title||"")},WB:h.title},O,{T:"div",N:"ytp-ce-merchandise-metadata",WB:h.metadata},{T:"a",M5:["ytp-ce-merchandise-goto","ytp-ce-link"],Z:{href:TB(N,h.targetUrl),target:"_blank",tabindex:"-1"},WB:h.callToAction}]}]}]}]},{T:"div",N:"ytp-ce-expanding-image",Z:Hq(h)},{T:"div",N:"ytp-ce-merchandise-invideo-cta-container",C:[{T:"div",N:"ytp-ce-merchandise-invideo-cta",
WB:h.callToAction||void 0}]}]},O=new g.f(N)}h.isPlaceholder&&g.u9(O.element,"ytp-ce-placeholder");return O},Hq=function(N){if(N.Sz)var h=N.Sz.thumbnails;
return KdY(h?h[h.length-1].url:null)},KdY=function(N){return N?{style:"background-image: url("+N+")"}:{}},wkS=function(N,h,O){function u(B){B&&(h.listen("blur",function(){B.style.display!="none"&&N.eS&&B.focus()}),h.J(B,"focus",U),h.J(B,"blur",d))}
function D(B){N.B+=B;N.B>0?(g.u9(h.element,"ytp-ce-force-expand"),Wq(N,O.id,!0)):(g.UC(h.element,"ytp-ce-force-expand"),g.UC(h.element,"ytp-ce-element-hover"),Wq(N,O.id,!1))}
function U(){D(1)}
function d(){D(-1)}
h.listen("mouseenter",function(){mdR(N,h,O)});
h.listen("mouseleave",function(){IWK(N,h,O)});
N.player.K().W||h.listen("click",function(){g.u9(h.element,"ytp-ce-element-hover")});
h.listen("click",function(B){tjx(N,O,B)});
h.listen("keypress",function(B){tjx(N,O,B)});
h.listen("focus",function(){mdR(N,h,O)});
h.listen("blur",function(){IWK(N,h,O)});
h.listen("touchstart",function(){mdR(N,h,O)});
var b=g.iD("ytp-ce-expanding-overlay-hider",h.element);b&&h.J(b,"touchstart",function(B){B.stopPropagation();g.UC(h.element,"ytp-ce-element-hover");g.UC(h.element,"ytp-ce-force-expand")});
h.listen("keydown",function(B){N.eS=B.keyCode===9&&!B.shiftKey});
u(g.iD("ytp-sb-subscribe",h.element));u(g.iD("ytp-sb-unsubscribe",h.element));h.listen("focus",U);h.listen("blur",d)},tjx=function(N,h,O){if(h.targetUrl&&(!O||O.type!=="keypress"||O.keyCode===13)){for(var u=O.target;u&&!g.OC(u,"ytp-ce-element");){g.OC(u,"subscribe-label")&&$dY(N,h);
if(g.OC(u,"ytp-ce-channel-subscribe"))return;u=u.parentElement||null}if(!u||g.OC(u,"ytp-ce-element-hover")){O.preventDefault();O.stopPropagation();if(u=N.W[h.id])IWK(N,u,h),u.element.blur();if(O.ctrlKey||O.metaKey||h.zAn==="new")$dY(N,h),N.player.sendVideoStatsEngageEvent(17,void 0),N.player.pauseVideo(),O=g.b_(TB(N,h.targetUrl)),O=g.U3(O),g.H9(O,void 0,h.sessionData);else{var D=g.yv(N.player.K())||N.player.getVideoData().E8,U=function(){var d=TB(N,h.targetUrl),b=h.sessionData,B=h.watchEndpoint,C=
g.Nq(d);D&&C&&(C.v||C.list)?N.player.Yz(C.v,b,C.list,!1,void 0,B||void 0):g.Sk(d,b)};
$dY(N,h,function(){N.player.sendVideoStatsEngageEvent(17,U)})}}}},TB=function(N,h){N=N.player.K();
if(h){if(h.startsWith("//"))return N.protocol+":"+h;if(h.startsWith("/"))return g.cj(N)+h}else return"";return h},mdR=function(N,h,O){g.OC(h.element,"ytp-ce-element-hover")||(O.type==="VIDEO"||O.type==="PLAYLIST"?g.u9(h.element,"ytp-ce-element-hover"):N.player.K().W?(new g.YL(function(){g.u9(h.element,"ytp-ce-element-hover")},200)).start():g.u9(h.element,"ytp-ce-element-hover"),X8(N,O.NF),Wq(N,O.id,!0))},IWK=function(N,h,O){g.UC(h.element,"ytp-ce-element-hover");
g.UC(h.element,"ytp-ce-force-expand");Wq(N,O.id,!1)},Wq=function(N,h,O){N.U&&(O?N.L.show():N.L.hide());
for(var u=g.I(Object.keys(N.W)),D=u.next();!D.done;D=u.next())D=D.value,D!==h&&g.GC(N.W[D].element,"ytp-ce-element-shadow-show",O)},X8=function(N,h,O){function u(){U||(D++,D===h.length&&(d.stop(),O&&O()))}
if(!h||h.length===0||jM(N))O&&O();else{h=y4Y(N,h);var D=0,U=!1,d=new g.YL(function(){U=!0;O&&O()},1E3,N);
d.start();for(N=0;N<h.length;N++)g.as(h[N],u)}},$dY=function(N,h,O){X8(N,h.clickUrls,O);
(N=g.m7())&&h.E5&&g.kU(N,h.visualElement)},y4Y=function(N,h){var O=N.player.getVideoData().clientPlaybackNonce;
N=N.player.getCurrentTime().toFixed(2);O={CPN:O,AD_CPN:O,MT:N};N=[];for(var u=0;u<h.length;u++)N.push(VjS(h[u],O));return N},VjS=function(N,h){return N.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(O){var u=unescape(O);
u=u.substring(1,u.length-1);return h[u]?escape(h[u]):O})},RM5=function(N){return typeof N==="string"?N:""},fa=function(N,h,O){for(var u in h)if(h[u]===N)return N;
return O},PtY=function(N,h,O,u){this.value=N;
this.target=h;this.showLinkIcon=O;this.G=u},YK=function(N){return N.value?N.value:null},lz=function(N){if(!N)return null;
var h=g.b_(RM5(N.value));h=g.U3(h);if(!h)return null;var O=fa(N.target,Mjo,"current");if(O==null)N=null;else{var u=N.show_link_icon;N=new PtY(h,O,u==="true"||u==="false"?u==="true":!0,N.pause_on_navigation!=null?N.pause_on_navigation:!0)}return N},pkV=function(N,h,O){this.type=N;
this.trigger=h;this.url=O},c4x=function(N){if(!N)return null;
var h=fa(N.type,eMn),O=fa(N.trigger,E_x);N=N.url;N=Array.isArray(N)&&N.length?N[0]:N;N=lz(N?N:null);return h?new pkV(h,O,N):null},aWn=function(N,h,O,u,D){this.id=N;
this.type=h;this.style=O;this.data=D;this.action=u||[]},qvr=function(N,h){return g.KS(N.action,h)},g_V=function(N,h){this.context=N;
this.G=h},r4Y=function(N){return N.customMessage?xK("div","iv-card-message",N.customMessage):""},na=function(N,h){N="background-image: url("+N+");";
var O=[];h&&O.push(h);return{T:"div",N:"iv-card-image",Z:{style:N},C:O}},smS=function(N){if(!N.metaInfo||N.metaInfo.length===0)return"";
var h=[];N=g.I(N.metaInfo);for(var O=N.next();!O.done;O=N.next())h.push(xK("li","",O.value));return{T:"ul",N:"iv-card-meta-info",C:h}},xK=function(N,h,O){h?typeof h==="string"?h={"class":h}:Array.isArray(h)&&(h={"class":h.join(" ")}):h={};
h.dir=g.oJ(O);return{T:N,Z:h,WB:O}},J4n=function(N){if(!N.customMessage)return"";
var h=["iv-card-action","iv-card-primary-link"],O={};N.uM&&(h.push("iv-card-action-icon"),O.style="background-image: url("+N.uM+");");O.dir=g.oJ(N.customMessage);var u=[{T:"span",WB:N.customMessage}];N.showLinkIcon&&(u.push("\u00a0"),u.push({T:"span",N:"iv-card-link-icon"}));return{T:"div",M5:h,Z:O,C:u}},F8=function(N,h,O,u){if(u){h=g.I(h);
for(var D=h.next();!D.done;D=h.next())N.G(D.value,u,O.id,O.sessionData,O.IR.click,5)}},jmV=function(N,h){this.merchant=N;
this.price=h},Svo=function(N){var h;
(h=N)&&!(h=N.length>1?N.charAt(0)==="/"&&N.charAt(1)!=="/":N==="/")&&(h=N.replace(/^(https?:)?\/\//,"").split("/",1),h=!h||h.length<1||!h[0]?[]:h[0].toLowerCase().split(".").reverse(),h=h[0]==="com"&&h[1]==="youtube"||h[0]==="be"&&h[1]==="youtu");return h?N.indexOf("/redirect?")===-1:!1},Hnn=function(N,h){return h?h:Svo(N)?"current":"new"},Zm=function(N,h){g.S.call(this);
var O=this;this.element=N;this.context=h;this.CC=!1;this.u0=new Map;this.pC=new Map;this.context.S.addEventListener(g.xm("annotations_module"),function(u){(u=O.u0.get(u))&&u.apply(O)});
this.context.S.addEventListener(g.np("annotations_module"),function(u){(u=O.pC.get(u))&&u.apply(O)})},kK=function(N,h,O,u,D,U,d){N.context.G.listen(h,"click",function(b){N.BC(O,u,D,U||[],d||0,b)});
N.context.G.listen(h,"touchstart",function(){N.CC=!1});
N.context.G.listen(h,"touchmove",function(){N.CC=!0})},TVV=function(N){var h;
return((h=g.X(N,g.qP))==null?0:h.url)?g.X(N,g.qP).url:(N=g.X(N,g.Vi))&&N.videoId?(h="/watch?v="+N.videoId,N.playlistId&&(h+="&list="+N.playlistId),N.index&&(h+="&index="+N.index),N.startTimeSeconds&&(h+="&t="+N.startTimeSeconds),h):null},NE=function(N,h,O){return{yw:(N.impressionLoggingUrlsV2s||[]).map(function(u){return u.baseUrl||""}),
click:(O.loggingUrls||[]).map(function(u){return u.baseUrl||""}),
close:(h.dismissLoggingUrlsV2s||[]).map(function(u){return u.baseUrl||""}),
Qf:(h.impressionLoggingUrlsV2s||[]).map(function(u){return u.baseUrl||""}),
YX:(h.clickLoggingUrlsV2s||[]).map(function(u){return u.baseUrl||""})}},Wdj=function(N,h,O){Zm.call(this,h,O);
var u=this;this.S=N;this.eventId=null;this.GZ=this.m$=this.UJ=this.U=this.isInitialized=!1;this.cards=[];this.KC=this.L=this.FA=this.V=this.HB=this.G=null;this.eS=[];this.fC=this.Y=this.Ze=this.b0=null;this.B=0;this.TO=new g.YL(function(){},O.Qm.e3?4E3:3E3);
g.H(this,this.TO);this.xn=new g.YL(function(){});
g.H(this,this.xn);this.vB=new g_V(O,function(D,U,d,b,B,C){kK(u,D,U,d,b,B,C)});
this.D=new g.f({T:"div",N:"iv-drawer",Z:{id:"iv-drawer"},C:[{T:"div",N:"iv-drawer-header",Z:{"aria-role":"heading"},C:[{T:"span",N:"iv-drawer-header-text"},{T:"button",M5:["iv-drawer-close-button","ytp-button"],Z:{"aria-label":"Hide cards",tabindex:"0"}}]},{T:"div",N:"iv-drawer-content"}]});g.H(this,this.D);this.X=this.D.element;this.PB=new g.ka(this.D,330);g.H(this,this.PB);this.e6=g.iD("iv-drawer-header-text",this.X);this.W=g.iD("iv-drawer-content",this.X);this.addCueRange(0,O.videoData.lengthSeconds*
1E3,"",function(){u.UJ&&hG(u,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(u.UJ=u.U)&&OZ(u)});
this.O3=new g.yg(this);g.H(this,this.O3);this.S.addEventListener("videodatachange",this.La.bind(this))},Xk5=function(N,h){h=h.data;
h.autoOpenMs&&N.addCueRange(h.autoOpenMs,0x8000000000000,"",function(){hG(N,"YOUTUBE_DRAWER_AUTO_OPEN")});
h.autoCloseMs&&N.addCueRange(h.autoCloseMs,0x8000000000000,"",function(){OZ(N)});
var O=h.headerText;g.tA(N.e6,O);N.L&&(N.S.j("player_tooltip_data_title_killswitch")?N.L.setAttribute("title",O):N.L.setAttribute("data-tooltip-title",O));h.eventId&&(N.eventId=h.eventId);N.b0=g.vN(h.trackingParams);N.Y=g.vN(h.closeTrackingParams);N.Ze=g.vN(h.iconTrackingParams)},fWm=function(N,h){var O=h.cardId?h.cardId:"cr:"+N.B,u=N.S.K().experiments.nC("enable_error_corrections_infocard_web_client");
if(!h.content&&h.teaser.simpleCardTeaserRenderer&&u){var D=h.teaser.simpleCardTeaserRenderer,U=h.icon?h.icon.infoCardIconRenderer:null;if(D.channelAvatar&&D.channelAvatar.thumbnails&&D.channelAvatar.thumbnails.length>0)var d=u3(D.channelAvatar.thumbnails,22,22).url;h={id:O,timestamp:N.B,type:"simple",teaserText:g.Cv(D.message),teaserDurationMs:Number(h.cueRanges[0].teaserDurationMs),startMs:Number(h.cueRanges[0].startCardActiveMs),autoOpen:!!h.autoOpen,sessionData:{},sponsored:!1,IR:{},FJ:null,Cy:D.trackingParams?
g.vN(D.trackingParams):null,Ze:U&&U.trackingParams?g.vN(U.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,uM:null,title:"",customMessage:"",url:null,onClickCommand:D.onTapCommand||null,z5:d};D3(N,h)}else{var b;if((b=h.content)==null?0:b.simpleCardContentRenderer){if(!h.cueRanges.length)return;d=(D=h.content)==null?void 0:D.simpleCardContentRenderer;D=h.teaser.simpleCardTeaserRenderer;U=h.icon?h.icon.infoCardIconRenderer:null;h={id:O,timestamp:N.B,type:"simple",teaserText:g.Cv(D.message),
teaserDurationMs:Number(h.cueRanges[0].teaserDurationMs),startMs:Number(h.cueRanges[0].startCardActiveMs),autoOpen:!!h.autoOpen,sessionData:UZ(N,O,h,d),sponsored:!1,IR:NE(d,D,d.command),FJ:d.trackingParams?g.vN(d.trackingParams):null,Cy:D.trackingParams?g.vN(D.trackingParams):null,Ze:U&&U.trackingParams?g.vN(U.trackingParams):null,imageUrl:u3(d.image.thumbnails,290,290).url,displayDomain:d.displayDomain?g.Cv(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,uM:null,title:d.title?g.Cv(d.title):"",
customMessage:d.callToAction?g.Cv(d.callToAction):"",url:g.X(d.command,g.qP).url?lz({pause_on_navigation:!N.context.videoData.isLivePlayback,target:"new",value:g.X(d.command,g.qP).url}):null,onClickCommand:null};D3(N,h)}else{var B;if((B=h.content)==null?0:B.collaboratorInfoCardContentRenderer){if(!h.cueRanges.length)return;d=(U=h.content)==null?void 0:U.collaboratorInfoCardContentRenderer;D=h.teaser.simpleCardTeaserRenderer;U=h.icon?h.icon.infoCardIconRenderer:null;h={id:O,timestamp:N.B,type:"collaborator",
teaserText:g.Cv(D.message),teaserDurationMs:Number(h.cueRanges[0].teaserDurationMs),startMs:Number(h.cueRanges[0].startCardActiveMs),autoOpen:!!h.autoOpen,sessionData:UZ(N,O,h,d),sponsored:!1,IR:NE(d,D,d.endpoint),FJ:d.trackingParams?g.vN(d.trackingParams):null,Cy:D.trackingParams?g.vN(D.trackingParams):null,Ze:U&&U.trackingParams?g.vN(U.trackingParams):null,channelId:g.X(d.endpoint,g.k4).browseId,customMessage:d.customText?g.Cv(d.customText):null,profileImageUrl:u3(d.channelAvatar.thumbnails,290,
290).url,title:d.channelName?g.Cv(d.channelName):"",metaInfo:[d.subscriberCountText?g.Cv(d.subscriberCountText):""],url:lz({pause_on_navigation:!N.context.videoData.isLivePlayback,target:"new",value:g.X(d.endpoint,g.k4).canonicalBaseUrl?g.X(d.endpoint,g.k4).canonicalBaseUrl:"/channel/"+g.X(d.endpoint,g.k4).browseId}),onClickCommand:null};D3(N,h)}else{var C;if((C=h.content)==null?0:C.playlistInfoCardContentRenderer){if(!h.cueRanges.length)return;var A;d=(A=h.content)==null?void 0:A.playlistInfoCardContentRenderer;
D=h.teaser.simpleCardTeaserRenderer;U=h.icon?h.icon.infoCardIconRenderer:null;h={id:O,timestamp:N.B,type:"playlist",teaserText:g.Cv(D.message),teaserDurationMs:Number(h.cueRanges[0].teaserDurationMs),startMs:Number(h.cueRanges[0].startCardActiveMs),autoOpen:!!h.autoOpen,sessionData:UZ(N,O,h,d),sponsored:!1,IR:NE(d,D,d.action),FJ:d.trackingParams?g.vN(d.trackingParams):null,Cy:D.trackingParams?g.vN(D.trackingParams):null,Ze:U&&U.trackingParams?g.vN(U.trackingParams):null,Z0:u3(d.playlistThumbnail.thumbnails,
258,290).url,customMessage:d.customMessage?g.Cv(d.customMessage):null,playlistVideoCount:g.Cv(d.playlistVideoCount),title:d.playlistTitle?g.Cv(d.playlistTitle):"",metaInfo:[d.channelName?g.Cv(d.channelName):"",d.videoCountText?g.Cv(d.videoCountText):""],url:lz({pause_on_navigation:!N.context.videoData.isLivePlayback,target:"new",value:TVV(d.action)}),onClickCommand:null};D3(N,h)}else{var Q;if((Q=h.content)==null?0:Q.videoInfoCardContentRenderer){if(!h.cueRanges.length)return;var L;d=(L=h.content)==
null?void 0:L.videoInfoCardContentRenderer;D=h.teaser.simpleCardTeaserRenderer;U=h.icon?h.icon.infoCardIconRenderer:null;h={id:O,timestamp:N.B,type:"video",teaserText:g.Cv(D.message),teaserDurationMs:Number(h.cueRanges[0].teaserDurationMs),startMs:Number(h.cueRanges[0].startCardActiveMs),autoOpen:!!h.autoOpen,sessionData:UZ(N,O,h,d),sponsored:!1,IR:NE(d,D,d.action),FJ:d.trackingParams?g.vN(d.trackingParams):null,Cy:D.trackingParams?g.vN(D.trackingParams):null,Ze:U&&U.trackingParams?g.vN(U.trackingParams):
null,Z0:u3(d.videoThumbnail.thumbnails,258,290).url,videoDuration:d.lengthString?g.Cv(d.lengthString):null,customMessage:d.customMessage?g.Cv(d.customMessage):null,title:d.videoTitle?g.Cv(d.videoTitle):"",metaInfo:[d.channelName?g.Cv(d.channelName):"",d.viewCountText?g.Cv(d.viewCountText):""],isLiveNow:!!d.badge,url:lz({pause_on_navigation:!N.context.videoData.isLivePlayback,target:"new",value:TVV(d.action)}),onClickCommand:null};D3(N,h)}}}}}N.B++},u3=function(N,h,O){for(var u=-1,D=-1,U=0;U<N.length;U++){if(N[U].height===
h||N[U].width===O)return N[U];
((N[U].height||0)<h||(N[U].width||0)<O)&&(u<0||(N[u].height||0)<(N[U].height||0)||(N[u].width||0)<(N[U].width||0))?u=U:((N[U].height||0)>=h||(N[U].width||0)>=O)&&(D<0||(N[D].height||0)>(N[U].height||0)||(N[D].width||0)>(N[U].width||0))&&(D=U)}return N[D>=0?D:u]},UZ=function(N,h,O,u){return{feature:O.feature?O.feature:"cards",
src_vid:N.context.videoData.videoId,annotation_id:h,ei:N.context.videoData.eventId||"",itct:u.trackingParams||""}},lWS=function(N,h){if(h=YvS(N,h))h===N.G&&(N.G=null),N.S.removeCueRange(h.BI.id),g.mq(h.YK),g.y4(N.cards,h),N.hB(),d7(N)},hG=function(N,h,O){if(!N.U){N.PB.show();
N.HB=new g.YL(function(){g.u9(N.context.S.getRootNode(),g.$A.IV_DRAWER_OPEN)},0);
N.HB.start();N.O3.J(N.W,"mousewheel",function(d){N.TO.start();d.preventDefault();d=d||window.event;var b=0;d.type=="MozMousePixelScroll"?b=0==(d.axis==d.HORIZONTAL_AXIS)?d.detail:0:window.opera?b=d.detail:b=d.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?d.wheelDeltaY/-30:d.wheelDeltaY/-1.2:d.wheelDelta/-1.6:d.wheelDeltaY/-3;if(d=b)N.W.scrollTop+=d});
N.U=!0;var u=g.m7();u&&N.b0&&N.Y&&g.Fw(u,[N.b0,N.Y]);h={TRIGGER_TYPE:h};for(var D=g.I(N.cards),U=D.next();!U.done;U=D.next())U=U.value,U.J7||(U.J7=!0,xdV(N.context.logger,U.BI.IR.yw,h)),u&&g.Fw(u,[U.BI.FJ]);eM(N.S);O&&(N.V=new g.YL(function(){N.FA=N.L;N.KC.focus()},330),N.V.start())}},OZ=function(N){N.U&&(N.PB.hide(),g.RV(N.O3),g.UC(N.context.S.getRootNode(),g.$A.IV_DRAWER_OPEN),N.U=!1,eM(N.S),N.V&&N.V.stop(),N.V=new g.YL(function(){N.FA&&(N.FA.focus(),N.FA=null)},330),N.V.start())},n_4=function(N){g.DG(N.Iz(),
[g.$A.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.O9(N.S,N.X,5);N.oA();N.L=g.iD("ytp-cards-button",N.S.getRootNode());N.KC=g.iD("iv-drawer-close-button",N.X);N.isInitialized=!0},Fdo=function(N){N.eS.push(g.kk("iv-teaser-shown",N.Zu,N));
N.eS.push(g.kk("iv-teaser-hidden",N.L$n,N));N.eS.push(g.kk("iv-teaser-clicked",N.Jf,N));N.GZ=!0},Zn5=function(N,h){var O;
return h.onClickCommand&&((O=g.X(h.onClickCommand,g.RCx))==null?void 0:O.targetId)==="engagement-panel-error-corrections"?(N.fC=h,!0):!1},kfR=function(N,h){N.fC=h;
var O=N.S.getVideoData();if(!O)return!1;O=g.Ow(O);if(O==null?0:O.markersMap)for(var u,D=0;((u=O)==null?void 0:u.markersMap.length)>D;D++){var U=void 0,d=(U=O)==null?void 0:U.markersMap[D];if(d.key==="ERROR_CORRECTION_MARKERS"&&(U=void 0,(d=(U=d.value)==null?void 0:U.markers)&&d.length>0))return u=void 0,h.startMs=((u=g.X(d[0],g.Wco))==null?void 0:u.timeRangeStartMillis)||0,N.fC=null,!0}return!1},D3=function(N,h){if(!Zn5(N,h)||kfR(N,h)){var O=Nur(N,h);
if(O){var u={BI:h,YK:O.element,J7:!1};if(h.onClickCommand)N.S.j("web_infocards_teaser_show_logging_fix")&&(N.GZ||Fdo(N),lWS(N,h.id),O=N.findLastIndex(u),g.jx(N.cards,O,0,u));else{N.isInitialized||n_4(N);lWS(N,h.id);var D=N.findLastIndex(u);g.jx(N.cards,D,0,u);O.rf(N.W,D);N.hB()}h.autoOpen?N.addCueRange(h.startMs,0x8000000000000,h.id,function(){N.U||(N.G=u,d7(N),hc5(N,u),hG(N,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(O=N.context.S.getCurrentTime()*1E3,O<5E3&&O>h.startMs&&O3m(N,u),N.addCueRange(h.startMs,
h.startMs+1,h.id,function(){O3m(N,u)}),d7(N))}}},Nur=function(N,h){switch(h.type){case "simple":N=N.vB;
var O=h.displayDomain?{T:"div",N:"iv-card-image-text",WB:h.displayDomain}:void 0;var u=J4n(h);O={T:"div",M5:["iv-card"],C:[{T:"a",N:"iv-click-target",Z:{href:h.url?YK(h.url)||"":""},C:[na(h.imageUrl,O),{T:"div",N:"iv-card-content",C:[xK("h2",void 0,h.title),u]}]}]};O=new g.f(O);F8(N,g.Gy("iv-click-target",O.element),h,h.url);h=O;break;case "collaborator":N=N.vB;O={T:"div",M5:["iv-card","iv-card-channel"],C:[{T:"a",M5:["iv-click-target"],Z:{href:YK(h.url)||"","data-ytid":h.channelId},C:[na(h.profileImageUrl),
{T:"div",N:"iv-card-content",C:[r4Y(h),{T:"h2",N:"iv-card-primary-link",WB:h.title},smS(h)]}]}]};O=new g.f(O);F8(N,g.Gy("iv-click-target",O.element),h,h.url);h=O;break;case "playlist":N=N.vB;O={T:"div",M5:["iv-card","iv-card-playlist"],C:[{T:"a",N:"iv-click-target",Z:{href:YK(h.url)||""},C:[na(h.Z0,{T:"div",N:"iv-card-image-overlay",C:[{T:"span",N:"iv-card-playlist-video-count",WB:h.playlistVideoCount}]}),{T:"div",N:"iv-card-content",C:[r4Y(h),xK("h2","iv-card-primary-link",h.title),smS(h)]}]}]};
O=new g.f(O);F8(N,g.Gy("iv-click-target",O.element),h,h.url);h=O;break;case "productListing":N=N.vB;var D=h.offers.length!=0;O=["iv-card"];u="";var U=J4n(h);D&&(O.push("iv-card-product-listing"),u="iv-card-primary-link",U=h.offers[0],D=[],U.price&&D.push({T:"div",N:"iv-card-offer-price",WB:U.price}),U.merchant&&D.push({T:"div",N:"iv-card-offer-merchant",WB:U.merchant}),U={T:"div",C:D});D=h.url?YK(h.url)||"":"";O={T:"div",M5:O,Z:{tabindex:"0"},C:[{T:"a",M5:["iv-card-image","iv-click-target"],Z:{style:"background-image: url("+
h.imageUrl+");",href:D,"aria-hidden":"true",tabindex:"-1"}},{T:"div",N:"iv-card-content",C:[h.sponsored?{T:"div",N:"iv-card-sponsored",C:["Sponsored",{T:"div",N:"iv-ad-info-container",C:[{T:"div",N:"iv-ad-info",WB:"{{adInfo}}"},{T:"div",N:"iv-ad-info-icon-container",C:[{T:"div",N:"iv-ad-info-icon"},{T:"div",N:"iv-ad-info-callout"}]}]}]}:"",{T:"a",N:"iv-click-target",Z:{href:D},C:[xK("h2",u,h.title),U]}]}]};O=new g.f(O);u=g.LF("span");g.tA(u,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
O.pM(u,"adInfo");F8(N,g.Gy("iv-click-target",O.element),h,h.url);h=O;break;case "video":N=N.vB;u=h.videoDuration?{T:"span",N:"iv-card-video-duration",WB:h.videoDuration}:void 0;U=h.isLiveNow?{T:"span",M5:["yt-badge","yt-badge-live"],WB:"LIVE NOW"}:null;D={T:"div",M5:["iv-card","iv-card-video"],C:[{T:"a",N:"iv-click-target",Z:{href:((O=h.url)==null?void 0:YK(O))||""},C:[na(h.Z0,u),{T:"div",N:"iv-card-content",C:[r4Y(h),xK("h2","iv-card-primary-link",h.title),smS(h),U]}]}]};O=new g.f(D);F8(N,g.Gy("iv-click-target",
O.element),h,h.url);h=O;break;default:return null}return h},uy5=function(N){if(N.G)return N.G.BI.type==="productListing";
if(N.S.j("enable_wn_infocards")){var h;return!((h=N.cards)==null||!h.length)&&g.mG(N.cards,function(O){return O.BI.type==="productListing"})}return g.mG(N.cards,function(O){return O.BI.type==="productListing"})},d7=function(N){g.GC(N.S.getRootNode(),"ytp-cards-shopping-active",uy5(N))},O3m=function(N,h){if(!g.OC(N.S.getRootNode(),"ytp-cards-teaser-shown")){if(N.G!==h){var O=g.m7(),u=N.G?N.G.BI.Ze:N.Ze;
O&&u&&g.Zl(O,[u]);N.G=h;d7(N)}(O=N.isInitialized&&N.Iz().style.display=="none")||(O=N.context.S.getPlayerState(),u=O===0&&N.context.S.getCurrentTime()===0,O=!(O===1||O===3||u));if(!O&&h.BI.teaserDurationMs){var D;O={teaserText:h.BI.teaserText,durationMs:h.BI.teaserDurationMs,onClickCommand:h.BI.onClickCommand,z5:(D=h.BI.z5)!=null?D:null};N.S.un(!0,O)}N.xn.isActive()||((!N.U||!N.TO.isActive()&&N.m$)&&hc5(N,h),N.xn.start(910+h.BI.teaserDurationMs))}},hc5=function(N,h){N.D.fF?(h=new gs([0,
N.W.scrollTop],[0,h.YK.offsetTop],600,inR),N.context.U.listen(h,"animate",function(O){N.W.scrollTop=O.y}),N.context.U.listen(h,"finish",function(O){N.W.scrollTop=O.y}),h.play()):(N.D.gq(!0),N.W.scrollTop=h.YK.offsetTop,N.D.gq(!1))},GP=function(N){return N.G&&N.G.BI?N.G.BI:N.cards[0]&&N.cards[0].BI?N.cards[0].BI:null},YvS=function(N,h){return g.KS(N.cards,function(O){return O.BI.id===h})},b3=function(N,h,O){Zm.call(this,N,h);
this.annotation=O;this.isActive=!1},DB5=function(N){var h=N.annotation.data;
"start_ms"in h&&"end_ms"in h&&N.addCueRange(Number(h.start_ms),Number(h.end_ms),N.annotation.id,function(){N.show()},function(){N.hide()})},i3=function(N,h,O){b3.call(this,N,h,O);
this.W=null;this.B=!1;this.U=null;this.X=!1;this.G=this.V=this.L=null},UB5=function(N,h){var O=O===void 0?0:O;
var u=NVK(h).width;g.Z0(h,u);O=new Gfx(h,[u,h.offsetTop],[u-u-O,h.offsetTop],200,bnY);g.H(N,O);N.context.U.listen(O,"begin",function(){g.DZ(h,!0)});
O.play()},b3m=function(N,h){if(h.channel_name){var O=N.createElement({T:"div",
M5:["iv-branding-context-name"],WB:h.channel_name}),u=N.createElement({T:"div",M5:["iv-branding-context-subscribe"]}),D=h.standalone_subscribe_button_data;D&&(N.G=new g.UG(D.subscribeText,D.subscribeCount,D.unsubscribeText,D.unsubscribeCount,!!D.enabled,!!D.classic,h.channel_id,!!D.subscribed,D.feature,h.session_data.itct,N.context.S,!1),N.G.rf(u));var U=N.createElement({T:"div",M5:["iv-branding-context-subscribe-caret"]}),d=N.createElement({T:"div",M5:["branding-context-container-inner"]});d.appendChild(U);
d.appendChild(O);d.appendChild(u);g.DZ(d,!1);var b=N.createElement({T:"div",M5:["branding-context-container-outer"]});b.appendChild(d);g.fF(b,"right",h.image_width+"px");g.vi(N.Iz(),b);N.U=new g.YL(function(){dBV(N,d,b)},500);
g.H(N,N.U);N.context.G.listen(N.Iz(),"mouseover",function(){G_n(N,d,b,U,h.image_height)});
N.context.G.listen(N.Iz(),"mouseout",function(){N.U.start()})}},G_n=function(N,h,O,u,D){N.U.stop();
if(!N.X){var U=g.ui(h);N.G||(h.style.width=g.Fl(U.width,!0),O.style.width=g.Fl(U.width,!0));g.fF(u,"top",U.height-Math.max(Math.min(U.height,D)/2+10,20)+"px");g.fF(u,"right","1px");N.X=!0;g.DZ(h,!0);N.L=new g.YL(function(){g.u9(this.Iz(),"iv-branding-active")},0,N);
N.L.start()}},dBV=function(N,h,O){g.UC(N.Iz(),"iv-branding-active");
N.V=new g.YL(function(){g.DZ(h,!1);N.G||(O.style.width=g.Fl(0,!0))},250);
N.V.start();N.X=!1},i3o=function(N,h,O,u,D,U,d){this.G=N;
this.U=h;this.Qm=O;this.videoData=u;this.logger=D;this.S=U;this.W=d},Bu4=function(N,h,O){b3.call(this,N,h,O);
var u=this;this.Y=this.isCollapsed=this.D=!1;this.V=5E3;this.W=this.U=this.G=this.X=null;this.B=this.createElement({T:"div",M5:["iv-promo-contents"]});this.L=new g.YL(function(){u.G.setAttribute("aria-hidden","true");g.DZ(u.U,!1);g.DZ(u.W,!0)},700,this);
g.H(this,this.L)},AaY=function(N){var h=N.annotation.data;
if(N.annotation.style==="cta")var O=6;else if(N.annotation.style==="video"||N.annotation.style==="playlist")O=7;N.V=h.collapsedelay_ms||N.V;var u=["iv-promo","iv-promo-inactive"];N.Iz().setAttribute("aria-hidden","true");N.Iz().setAttribute("aria-label","Promotion");N.Iz().tabIndex=0;var D=N.annotation.lR(),U=h.image_url;if(U){var d=N.createElement({T:"div",M5:["iv-promo-img","iv-click-target"]});U=N.createElement({T:"img",Z:{src:U,"aria-hidden":"true"}});d.appendChild(U);h.video_duration&&!h.is_live?
(U=N.createElement({T:"span",N:"iv-promo-video-duration",WB:h.video_duration}),d.appendChild(U)):h.playlist_length&&(U=N.createElement({T:"span",N:"iv-promo-playlist-length",WB:h.playlist_length.toString()}),d.appendChild(U));D&&kK(N,d,D,N.annotation.id,h.session_data,void 0,O)}D?(U=N.createElement({T:"a",N:"iv-promo-txt"}),g.By(U,YK(D)),N.G=U):N.G=N.createElement({T:"div",N:"iv-promo-txt"});switch(N.annotation.style){case "cta":case "website":var b=N.createElement({T:"p",C:[{T:"strong",WB:h.text_line_1}]});
var B=N.createElement({T:"p",C:[{T:"span",N:"iv-promo-link",WB:h.text_line_2}]});if(U=h.text_line_3){u.push("iv-promo-website-card-cta-redesign");var C=N.createElement({T:"button",M5:["iv-promo-round-expand-icon","ytp-button"]});U=N.createElement({T:"button",M5:["iv-button","iv-promo-button"],C:[{T:"span",N:"iv-button-content",WB:U}]});var A=N.createElement({T:"div",N:"iv-promo-button-container"});A.appendChild(U);D&&kK(N,N.Iz(),D,N.annotation.id,h.session_data,void 0,O)}g.u9(N.G,"iv-click-target");
D&&kK(N,N.G,D,N.annotation.id,h.session_data,void 0,O);break;case "playlist":case "video":b=N.createElement({T:"p",C:[{T:"span",WB:h.text_line_1}]}),B=N.createElement({T:"p",C:[{T:"strong",WB:h.text_line_2}]}),h.is_live&&(b=B,B=N.createElement({T:"span",M5:["yt-badge","iv-promo-badge-live"],WB:"LIVE NOW"})),g.u9(N.G,"iv-click-target"),D&&kK(N,N.G,D,N.annotation.id,h.session_data,void 0,O),u.push("iv-promo-video")}b&&N.G.appendChild(b);B&&N.G.appendChild(B);N.B.appendChild(N.G);A&&N.B.appendChild(A);
O=N.createElement({T:"div",N:"iv-promo-actions"});N.W=N.createElement({T:"button",M5:["iv-promo-expand","ytp-button"]});N.W.title="Expand";N.context.G.listen(N.W,"click",function(Q){CL5(N,5E3,Q)});
O.appendChild(N.W);g.DZ(N.W,!1);N.context.G.listen(N.Iz(),"mouseover",N.Gm,N);N.context.G.listen(N.Iz(),"mouseout",N.e1,N);N.context.G.listen(N.Iz(),"touchend",function(Q){CL5(N,5E3,Q)});
N.U=N.createElement({T:"button",M5:["iv-promo-close","ytp-button"]});N.U.title="Close";N.context.G.listen(N.U,"click",N.annotation.style==="cta"&&h.text_line_3?N.DD:N.K8,N);O.appendChild(N.U);g.DG(N.Iz(),u);d&&(g.vi(N.Iz(),d),C&&d.appendChild(C));g.vi(N.Iz(),N.B);g.vi(N.Iz(),O)},CL5=function(N,h,O){O.stopPropagation();
oP4(N);QUo(N,h);N.G.focus()},LRY=function(N){N.isCollapsed||N.Y||N.X||(g.u9(N.Iz(),"iv-promo-collapsed"),N.isCollapsed=!0,N.L.start())},oP4=function(N){N.L.stop();
N.isCollapsed&&(g.dI(N.Iz(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),N.isCollapsed=!1,N.G&&N.G.removeAttribute("aria-hidden"),g.DZ(N.W,!1),g.DZ(N.U,!0))},QUo=function(N,h){N.X||(N.X=g.Js(function(){zcm(this);
LRY(this)},h,N))},zcm=function(N){N.X&&(g.kp.clearTimeout(N.X),N.X=null)},vP4=function(N){this.S=N},xdV=function(N,h,O){h&&(O?Bh(N,h.map(function(u){return g.Mm(u,O)})):Bh(N,h))},Bh=function(N,h,O,u){var D=1,U=void 0,d=-1;
if(O){var b=!1;U=function(){D--;D||b||(clearTimeout(d),b=!0,O())};
d=setTimeout(function(){b=!0;O()},1E3)}h=g.I(h||[]);
for(var B=h.next();!B.done;B=h.next())B=B.value,D++,g.as(B,U);u&&(D++,u!==0&&N.S.sendVideoStatsEngageEvent(u,U))},wPK=function(N){g.Vq.call(this,N);
var h=this;this.eS=this.Y=!1;this.loadNumber=0;this.V={};this.logger=new vP4(this.player);this.X=new g.yg(this);this.L=this.B=null;this.events=new g.yg(this);this.wc=this.D=this.G=null;this.fC=[];g.H(this,this.X);this.X.J(this.player,"onVideoAreaChange",function(){h.publish("onVideoAreaChange")});
this.X.J(this.player,"onHideControls",function(){h.publish("onHideControls")});
this.X.J(this.player,"onShowControls",function(){h.publish("onShowControls")});
this.X.J(this.player,"resize",function(u){h.publish("resize",u)});
this.X.J(this.player,"presentingplayerstatechange",function(u){h.publish("presentingplayerstatechange",u)});
this.subscribe("presentingplayerstatechange",this.CP,this);this.subscribe("resize",this.h$,this);this.player.K().m$.subscribe("vast_info_card_add",this.qp,this);g.H(this,this.events);this.vB=this.createElement({T:"div",N:"video-custom-annotations"});this.W=new g.f({T:"div",M5:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.W);g.O9(this.player,this.W.element,4);this.W.hide();this.U=new g.f({T:"div",M5:["ytp-iv-video-content"]});g.H(this,this.U);N=this.createElement({T:"div",N:"video-annotations"});
N.appendChild(this.vB);this.U.element.appendChild(N);this.xz()&&this.load();var O=this.createElement({T:"style"});(g.dX("HEAD")[0]||document.body).appendChild(O);this.addOnDisposeCallback(function(){g.mq(O)});
if(N=O.sheet)N.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),N.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),N.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),N.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),N.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),N.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),N.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),N.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),N.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),N.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},KRr=function(N){N=N.createElement({T:"div",
M5:["annotation","annotation-type-custom"]});g.DZ(N,!1);return N},mB5=function(N,h){h=!h.isCued()&&!g.Y(h,1024);
N.W.gq(h);N.U.gq(h)},IQK=function(N,h,O){N.Y=!0;
N.L=g.tY(h,O)},t4m=function(N,h){for(var O={},u=g.I(h.attributes),D=u.next();!D.done;D=u.next())D=D.value,O[D.name]=D.nodeValue;
for(u=0;u<h.childNodes.length;u++)if(D=h.childNodes[u],g.UR(D)&&D.nodeType==1){if(O[D.tagName])var U=O[D.tagName];else if(D.tagName==="data"){D.childNodes.length>0&&(U=D.childNodes[0].nodeValue,O[D.tagName]=typeof U==="string"?U.trim():U);continue}else U=[],O[D.tagName]=U;D&&D.tagName==="TEXT"?D.childNodes.length===1&&D.childNodes[0].nodeType===3?U.push(D.childNodes[0].nodeValue):U.push(""):D&&U.push(t4m(N,D))}return O},Rcj=function(N){var h=N.player.getVideoData();
if(h.O3){var O=N.player.K().m$.get(h.videoId);if(O){var u={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(D,U,d){D=N.loadNumber;U=h.videoId;N.loaded&&N.loadNumber===D&&N.player.getVideoData().videoId===U&&(d=g.BY(d)&&d.responseXML?d.responseXML:null)&&$Bj(N,d)}};
g.nE()&&(u.onFinish=ya4(N,u.onFinish));u.postParams={ic_only:"1"};V45(u,O);N.Y=!0;g.tY(h.O3,u)}}},V45=function(N,h){N.method="POST";
N.postParams=N.postParams||{};h.s4&&(N.postParams.ic_coll=h.s4);h.kK&&(N.postParams.ic_xml=h.kK);h.TK&&(N.postParams.ic_track=h.TK)},PLn=function(N){var h=new g.f({T:"div"});
g.DZ(h.element,!1);var O=new Wdj(N.player,h.element,Cl(N));g.H(O,h);h.rf(N.W.element);O.s7();return O},pP4=function(N,h){var O,u;
if(h=(O=h.getWatchNextResponse())==null?void 0:(u=O.cards)==null?void 0:u.cardCollectionRenderer)N.eS=!0,M4Y(N,h),h.headerText&&N.wc&&(O=g.Cv(h.headerText),N.player.j("player_tooltip_data_title_killswitch")?N.wc.setAttribute("title",O):N.wc.setAttribute("data-tooltip-title",O))},Cl=function(N){if(!N.D){var h=new BVx(N);
g.H(N,h);var O=new g.zx(N);g.H(N,O);N.D=new i3o(h,O,N.player.K(),N.player.getVideoData(),N.logger,N.player,N.XR)}return N.D},$Bj=function(N,h){var O=!1,u=h.getElementsByTagName("annotations");
if(u&&!(u.length<1)&&(u=u[0].getAttribute("itct"))){var D=g.m7();if(D){var U=g.KX();U&&g.lu(g.SC)(void 0,D,U,[g.vN(u)])}}h=h.getElementsByTagName("annotation");for(u=0;u<h.length;u++){U=t4m(N,h[u]);D=null;try{if(U){var d=U.id,b=/.+/;var B=typeof d==="string"&&b!=null&&d!=null&&d.match(b)?d:"";var C=fa(U.type,ec4),A=fa(U.style,EPr),Q=RM5(U.data),L=Q.length!==0?JSON.parse(Q):{};var z=U.action;U=c4x;if(z==null)var v=null;else if(g.DK(z)){b=[];for(var t=g.I(z),R=t.next();!R.done;R=t.next()){var p=U(R.value);
p&&b.push(p)}v=b}else{var M=U(z);v=M?[M]:[]}D=B&&C?new aWn(B,C,A,v,L):null}else D=null}catch(iY){}if(D)if(D.type==="branding"||D.type==="promotion"){U=N;b=D;var a=KRr(U),J=null;switch(b.type){case "branding":if(U.player.K().Ax)break;U.player.j("web_player_overlay_positioned_layout")?(a.setAttribute("data-overlay-order","11"),U.player.jf(a,4,!0)):U.W.element.appendChild(a);J=new i3(a,Cl(U),b);break;case "promotion":g.O9(U.player,a,4),J=new Bu4(a,Cl(U),b)}J&&J.s7();if(U=J)g.H(N,U),N.V[D.id]=U}else if(D.type===
"card"||D.type==="drawer"){N.G||(N.G=PLn(N),g.H(N,N.G));if(D.type==="card"){a=N.G;var W=(O=D)&&O.data&&O.data.card_type;D=O.data;if(W)switch(U=D.tracking||{},U={yw:U.impression,click:U.click,close:U.close,Qf:U.teaser_impression,YX:U.teaser_click},b=D.tracking_params||{},J=null,W){case "collaborator":O={id:O.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,startMs:D.start_ms,autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||
!1,IR:U,FJ:b.card?g.vN(b.card):null,Cy:b.teaser?g.vN(b.teaser):null,Ze:b.icon?g.vN(b.icon):null,channelId:D.channel_id,customMessage:D.custom_message?D.custom_message:null,profileImageUrl:D.image_url,title:D.title,metaInfo:D.meta_info,url:lz({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),onClickCommand:null};D3(a,O);break;case "playlist":O={id:O.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,startMs:D.start_ms,
autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||!1,IR:U,FJ:b.card?g.vN(b.card):null,Cy:b.teaser?g.vN(b.teaser):null,Ze:b.icon?g.vN(b.icon):null,Z0:D.image_url,playlistVideoCount:D.playlist_video_count,customMessage:D.custom_message?D.custom_message:null,title:D.title,metaInfo:D.meta_info,url:lz({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),onClickCommand:null};D3(a,O);break;case "productListing":D.signin_url&&(J=lz({target:"current",
value:D.signin_url}));W=[];for(var F=D.offers||[],l=0;l<F.length;l++)W.push(new jmV(g.E3(F[l].merchant),g.E3(F[l].price)));O={id:O.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,startMs:D.start_ms,autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||!1,IR:U,FJ:b.card?g.vN(b.card):null,Cy:b.teaser?g.vN(b.teaser):null,Ze:b.icon?g.vN(b.icon):null,imageUrl:D.image_url,displayDomain:D.display_domain?D.display_domain:
null,showLinkIcon:!!D.show_link_icon,uM:D.button_icon_url?D.button_icon_url:null,title:D.title,customMessage:D.custom_message?D.custom_message:null,url:lz({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),Kv0:J,ER$:D.signin_title?D.signin_title:void 0,CJQ:D.signin_message?D.signin_message:void 0,offers:W,onClickCommand:null};D3(a,O);break;case "simple":O={id:O.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,
startMs:D.start_ms,autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||!1,IR:U,FJ:b.card?g.vN(b.card):null,Cy:b.teaser?g.vN(b.teaser):null,Ze:b.icon?g.vN(b.icon):null,imageUrl:D.image_url,displayDomain:D.display_domain?D.display_domain:null,showLinkIcon:!!D.show_link_icon,uM:D.button_icon_url?D.button_icon_url:null,title:D.title,customMessage:D.custom_message?D.custom_message:null,url:lz({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),onClickCommand:null};
D3(a,O);break;case "video":O={id:O.id,timestamp:D.timestamp||0,type:D.card_type,teaserText:D.teaser_text,teaserDurationMs:D.teaser_duration_ms,startMs:D.start_ms,autoOpen:D.auto_open||!1,sessionData:D.session_data||{},sponsored:D.sponsored||!1,IR:U,FJ:b.card?g.vN(b.card):null,Cy:b.teaser?g.vN(b.teaser):null,Ze:b.icon?g.vN(b.icon):null,Z0:D.image_url,videoDuration:D.video_duration||null,customMessage:D.custom_message?D.custom_message:null,title:D.title,metaInfo:D.meta_info,isLiveNow:!!D.is_live_now,
url:lz({pause_on_navigation:D.pause_on_navigation,target:D.target||"new",value:D.url}),onClickCommand:null},D3(a,O)}}else Xk5(N.G,D);O=!0}}O&&(eM(N.player),N.h$())},M4Y=function(N,h){var O=!1;
N.G||(N.G=PLn(N),g.H(N,N.G));for(var u=g.I(h.cards||[]),D=u.next();!D.done;D=u.next())D=D.value,D.cardRenderer&&(fWm(N.G,D.cardRenderer),O=!0);if(O){var U;(U=N.player.getVideoData())!=null&&g.dg(U)||(O=N.G,u=h.headerText?g.Cv(h.headerText):"",g.tA(O.e6,u),O.L&&(O.S.j("player_tooltip_data_title_killswitch")?O.L.setAttribute("title",u):O.L.setAttribute("data-tooltip-title",u)),O.context.videoData.eventId&&(O.eventId=O.context.videoData.eventId),O.b0=h.trackingParams?g.vN(h.trackingParams):null,O.Y=
h.closeButton.infoCardIconRenderer.trackingParams?g.vN(h.closeButton.infoCardIconRenderer.trackingParams):null,O.Ze=h.icon.infoCardIconRenderer.trackingParams?g.vN(h.icon.infoCardIconRenderer.trackingParams):null,N.h$());eM(N.player)}},caS=function(N,h,O,u,D){if(!N.player.K().Ax){var U=[];
h.navigationEndpoint&&g.X(h.navigationEndpoint,g.k4)&&g.X(h.navigationEndpoint,g.k4).browseId&&U.push(new pkV("openUrl","click",new PtY("/channel/"+g.X(h.navigationEndpoint,g.k4).browseId,"new",!0,!0)));var d=h.watermark.thumbnails[0];u={channel_name:h.channelName,end_ms:h.endTimeMs,image_height:d.height,image_type:1,image_url:d.url,image_width:d.width,is_mobile:!1,session_data:{annotation_id:O,ei:D,feature:"iv",itct:h.trackingParams,src_vid:u},start_ms:h.startTimeMs};if(h.subscribeButton&&g.X(h.subscribeButton,
g.NA)){u.channel_id=g.X(h.subscribeButton,g.NA).channelId;var b;h=g.X(h.subscribeButton,g.NA);d=D=null;h.subscribed?(h.subscriberCountWithUnsubscribeText&&(D=g.Cv(h.subscriberCountWithUnsubscribeText)),h.subscriberCountText&&(d=g.Cv(h.subscriberCountText))):(h.subscriberCountText&&(D=g.Cv(h.subscriberCountText)),h.subscriberCountWithSubscribeText&&(d=g.Cv(h.subscriberCountWithSubscribeText)));var B,C=((B=g.X((b=h.signInEndpoint)==null?void 0:b.commandMetadata,g.$8))==null?void 0:B.url)||"";b={subscribeText:g.Cv(h.unsubscribedButtonText),
subscribeCount:D||"",unsubscribeText:g.Cv(h.subscribedButtonText),unsubscribeCount:d||"",enabled:h.enabled||!1,classic:!1,subscribed:h.subscribed||!1,feature:"iv",signInUrl:C};u.standalone_subscribe_button_data=b}U=new aWn(O,"branding","branding",U,u);b=KRr(N);N.player.j("web_player_overlay_positioned_layout")?(b.setAttribute("data-overlay-order","11"),N.player.jf(b,4,!0)):N.W.element.appendChild(b);U=new i3(b,Cl(N),U);U.s7();g.H(U,U);N.V[O]=U}},ya4=function(N,h){return function(){var O=g.jo.apply(0,
arguments);
N.SS()||N.fC.push(g.jD.wY(function(){h.apply(null,g.Lx(O))}))}},aQY=function(N){return N==="annotation-editor"||N==="live-dashboard"};
g.lw.prototype.un=g.Dd(39,function(N,h){var O=g.se(this.l_());O&&O.un(N,h)});
var cq={},aZ=null;g.LS(gs,g.b9);g.w=gs.prototype;g.w.getDuration=function(){return this.duration};
g.w.play=function(N){if(N||this.G==0)this.progress=0,this.coords=this.W;else if(this.isPlaying())return!1;qY(this);this.startTime=N=g.Aj();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.X=this.startTime;this.progress||this.qA();this.r5("play");this.isPaused()&&this.r5("resume");this.G=1;var h=g.G5(this);h in cq||(cq[h]=this);uER();DdY(this,N);return!0};
g.w.stop=function(N){qY(this);this.G=0;N&&(this.progress=1);Udr(this,this.progress);this.onStop();this.ev()};
g.w.pause=function(){this.isPlaying()&&(qY(this),this.G=-1,this.r5("pause"))};
g.w.q5=function(){this.G==0||this.stop(!1);this.r5("destroy");gs.YE.q5.call(this)};
g.w.destroy=function(){this.dispose()};
g.w.Vx=function(){this.r5("animate")};
g.w.r5=function(N){this.dispatchEvent(new ddY(N,this))};
g.LS(ddY,g.lB);g.LS(rs,gs);rs.prototype.U=function(){};
rs.prototype.Vx=function(){this.U();rs.YE.Vx.call(this)};
rs.prototype.ev=function(){this.U();rs.YE.ev.call(this)};
rs.prototype.qA=function(){this.U();rs.YE.qA.call(this)};
g.LS(Gfx,rs);Gfx.prototype.U=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.K(BVx,g.S);g.w=BVx.prototype;g.w.listen=function(N,h,O,u){O=(0,g.bS)(O,u||this.W);N=g.KE(N,h,O);this.G.push(N);return N};
g.w.Pn=function(N,h,O,u){O=(0,g.bS)(O,u||this.W);N=hM5(N,h,O);this.G.push(N);return N};
g.w.Td=function(N){g.mB(N);g.y4(this.G,N)};
g.w.removeAll=function(){g.mB(this.G);this.G.length=0};
g.w.q5=function(){this.removeAll();g.S.prototype.q5.call(this)};g.K(o_V,g.Vq);g.w=o_V.prototype;g.w.load=function(){g.Vq.prototype.load.call(this);if(!jM(this)){var N=g.nfY(this.player.getVideoData());N?(N=A4S(N,Qmm(this)),SM(this,N,!1)):LdS(this)}};
g.w.unload=function(){SM(this,null);this.X&&(this.X.abort(),this.X=null);g.Vq.prototype.unload.call(this)};
g.w.kx=function(N,h){return jM(this)?N==="loadCustomEndscreenRenderer"?(N=A4S(h,"new"),SM(this,N),!0):null:null};
g.w.getOptions=function(){return jM(this)?["loadCustomEndscreenRenderer"]:[]};
g.w.x6=function(){if(this.endscreen&&this.endscreen.elements){var N=this.player.getVideoContentRect();if(N&&N.width!==0&&N.height!==0){var h=this.player.getPlayerSize();if(h&&h.width!==0&&h.height!==0){var O=N.width/N.height;var u=0;for(var D=-1,U=0;U<q$Y.length;U++){var d=Math.abs(h.width-q$Y[U]);if(D===-1||u>=d)D=U,u=d}u=gPS[D];this.U&&g.fF(this.U.element,"outline-width",Math.max(h.width,h.height)+"px");for(h=0;h<this.endscreen.elements.length;++h)if(U=this.endscreen.elements[h].id,D=this.W[U],
d=this.V[U],D&&d){var b=d.width*O/d.aspectRatio,B=Math.round(d.width*N.width);U=Math.round(b*N.height);var C=N.left+Math.round(d.left*N.width),A=N.top+Math.round(d.top*N.height);g.Ol(D.element,B,U);g.Z0(D.element,C,A);g.dI(D.element,rax);B>256||U>256?g.u9(D.element,"ytp-ce-large-round"):B>96||U>96?g.u9(D.element,"ytp-ce-medium-round"):g.u9(D.element,"ytp-ce-small-round");g.dI(D.element,sUY);B=d.left+d.width/2;d=d.top+b/2;g.u9(D.element,B<=.5&&d<=.5?"ytp-ce-top-left-quad":B>.5&&d<=.5?"ytp-ce-top-right-quad":
B<=.5&&d>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.dI(D.element,gPS);g.u9(D.element,u);(D=g.bD(document,"div","ytp-ce-expanding-overlay-body",D.element)[0])&&g.fF(D,"height",U+"px")}}}}};
g.w.onCueRangeEnter=function(N){if(this.endscreen)if(N.getId()==="ytp-ce-in-endscreen")X8(this,this.endscreen.impressionUrls),(N=g.m7())&&this.endscreen.visualElement&&g.nX(N,this.endscreen.visualElement),this.G&&(g.u9(this.G,"ytp-ce-element-show"),this.G.removeAttribute("aria-hidden"),this.player.q3()?g.u9(this.G,"ytp-ce-hide-button-lower"):g.UC(this.G,"ytp-ce-hide-button-lower"));else{N=N.getId().substring(15);var h=this.W[N],O=this.V[N];g.u9(h.element,"ytp-ce-element-show");h.element.removeAttribute("aria-hidden");
h=this.player.getRootNode();g.u9(h,"ytp-ce-shown");X8(this,O.impressionUrls);(h=g.m7())&&g.nX(h,O.visualElement);this.player.K().Y&&this.player.wf("endscreenelementshown",N)}};
g.w.onCueRangeExit=function(N){if(N.getId()==="ytp-ce-in-endscreen")this.G&&(g.UC(this.G,"ytp-ce-element-show"),this.G.setAttribute("aria-hidden","true"));else{N=N.getId().substring(15);var h=this.W[N];g.UC(h.element,"ytp-ce-element-show");h.element.setAttribute("aria-hidden","true");h=this.player.getRootNode();g.UC(h,"ytp-ce-shown");this.player.K().Y&&this.player.wf("endscreenelementhidden",N)}};
g.w.Zgi=function(N){var h=this;N.target===window&&(new g.YL(function(){for(var O=g.I(Object.values(h.W)),u=O.next();!u.done;u=O.next())g.dI(u.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.w.gq=function(N){for(var h=g.I(Object.values(this.W)),O=h.next();!O.done;O=h.next())O=O.value,N?O.element.setAttribute("hidden",""):O.element.removeAttribute("hidden")};
g.w.iUC=function(N){this.G&&this.player.getRootNode().removeChild(this.G);N&&(g.u9(N,"ytp-ce-hide-button-container"),this.G=N,g.O9(this.player,this.G,4))};
var q$Y=[346,426,470,506,570,640,853,1280,1920],gPS="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),sUY=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],rax=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Mjo={HyS:"current",q$n:"new"};var eMn={CLOSE:"close",lPr:"openUrl",SUBSCRIBE:"subscribe"},E_x={vmQ:"click",CLOSE:"close",BhA:"hidden",mBO:"rollOut",hdF:"rollOver",dBA:"shown"};aWn.prototype.lR=function(){var N=qvr(this,function(h){return h.type==="openUrl"&&h.url!=null});
return N?N.url:null};
var EPr={lYA:"anchored",bU:"branding",CHANNEL:"channel",jRB:"cta",RJr:"highlightText",hkn:"label",PLAYLIST:"playlist",POPUP:"popup",xBA:"speech",SUBSCRIBE:"subscribe",yb3:"title",VIDEO:"video",Ab$:"website"},ec4={bU:"branding",kk3:"card",wFB:"drawer",d3m:"highlight",pbi:"marker",Anm:"promotion",TEXT:"text",iHQ:"widget"};g.K(Zm,g.S);g.w=Zm.prototype;g.w.addCueRange=function(N,h,O,u,D){N=new g.Ym(N,h,{id:O,namespace:"annotations_module"});u&&this.u0.set(N,u);D&&this.pC.set(N,D);this.context.S.Vq([N],1)};
g.w.s7=function(){this.context.W.subscribe("resize",this.hB,this)};
g.w.Iz=function(){return this.element};
g.w.BC=function(N,h,O,u,D,U){if(this.CC)return!1;U&&(U.stopPropagation(),U.preventDefault());this.navigate(N,O,u,D);return!1};
g.w.show=function(){};
g.w.hide=function(){};
g.w.destroy=function(){g.mq(this.Iz())};
g.w.hB=function(){};
g.w.navigate=function(N,h,O,u){var D=this,U=YK(N);if(U){var d=Hnn(U,N.target),b=function(){N.G&&D.context.S.pauseVideo();var B=D.context.videoData.E8||!1,C=g.Nq(U||"");B&&C&&(C.v||C.list)?D.context.S.Yz(C.v,h,C.list,!1):g.H9(U||"",d==="current"?"_top":void 0,h)};
d==="new"&&(b(),b=null);Bh(this.context.logger,O,b,u);Svo(U)||(O=g.m7(),u=h.itct,O&&u&&g.kU(O,g.vN(u)))}};
g.w.q5=function(){this.u0.clear();this.pC.clear();g.S.prototype.q5.call(this)};
g.w.createElement=function(N){N=new g.f(N);g.H(this,N);return N.element};g.K(Wdj,Zm);g.w=Wdj.prototype;g.w.La=function(){this.fC&&D3(this,this.fC)};
g.w.isAvailable=function(){var N;if(N=!!this.cards.length)(N=this.S.getRootNode())?(N=g.ui(N),N=173<N.width&&173<N.height):N=!1;return N};
g.w.hB=function(){var N=this.isAvailable();g.DZ(this.Iz(),N);g.GC(this.context.S.getRootNode(),g.$A.IV_DRAWER_ENABLED,N);eM(this.S)};
g.w.destroy=function(){this.S.un(!1);try{this.S.getRootNode().removeChild(this.X)}catch(N){}g.N$(this.eS);g.RV(this.O3);this.HB&&this.HB.dispose();this.V&&this.V.dispose();Zm.prototype.destroy.call(this)};
g.w.oA=function(){var N=this;this.context.G.listen(g.iD("iv-drawer-close-button",this.X),"click",this.Ea,this);this.context.G.listen(this.W,"touchend",function(){N.TO.start()});
this.context.G.listen(this.W,"scroll",this.mZ,this);this.context.W.subscribe("onHideControls",function(){N.m$=!0});
this.context.W.subscribe("onShowControls",function(){N.m$=!1});
this.context.W.subscribe("onVideoAreaChange",function(){N.m$=g.OC(N.S.getRootNode(),"ytp-autohide")});
this.eS.push(g.kk("iv-button-shown",this.rQS,this));this.eS.push(g.kk("iv-button-hidden",this.Tfr,this));Fdo(this)};
g.w.findLastIndex=function(N){if(this.cards.length===0)return 0;var h=g.mY(this.cards,function(O){return N.BI.startMs>O.BI.startMs||N.BI.startMs===O.BI.startMs&&N.BI.timestamp>=O.BI.timestamp?!0:!1});
return h===-1?0:h+1};
g.w.Ea=function(){if(this.U){Bh(this.context.logger,GP(this).IR.close);var N=g.m7();N&&this.Y&&g.kU(N,this.Y);OZ(this)}};
g.w.mZ=function(){g.GC(this.X,"iv-drawer-scrolled",this.W.scrollTop>0)};
g.w.rQS=function(){var N=g.m7(),h=GP(this);h=h?h.Ze:this.Ze;N&&h&&g.Fw(N,[h])};
g.w.Tfr=function(){var N=g.m7(),h=GP(this);h=h?h.Ze:this.Ze;N&&h&&g.Zl(N,[h])};
g.w.Zu=function(){var N=GP(this);Bh(this.context.logger,N.IR.Qf);var h=g.m7();if(h&&N)if(this.S.j("web_infocards_teaser_show_logging_fix")){var O=[];N.Cy&&O.push(N.Cy);N.Ze&&O.push(N.Ze);O.length>0&&g.Fw(h,O)}else g.Fw(h,[N.Cy,N.Ze])};
g.w.L$n=function(){var N=g.m7(),h=GP(this);N&&h&&g.Zl(N,[h.Cy])};
g.w.Jf=function(N){var h=GP(this),O=g.m7();this.G?N?(N=this.context.logger,Bh(N,h.IR.YX),N.S.sendVideoStatsEngageEvent(4,void 0),O&&h.Cy&&g.kU(O,h.Cy)):(N=this.context.logger,Bh(N,h.IR.YX),N.S.sendVideoStatsEngageEvent(4,void 0),O&&h.Ze&&g.kU(O,h.Ze)):(N=this.context.logger,Bh(N,h.IR.YX),N.S.sendVideoStatsEngageEvent(4,void 0),O&&this.Ze&&g.kU(O,this.Ze))};g.K(b3,Zm);b3.prototype.s7=function(){Zm.prototype.s7.call(this);DB5(this)};
b3.prototype.show=function(){Zm.prototype.show.call(this);var N=g.m7(),h=this.annotation.data;N&&h&&(h=h.session_data)&&g.Fw(N,[g.vN(h.itct)])};
b3.prototype.hide=function(){Zm.prototype.hide.call(this);var N=g.m7(),h=this.annotation.data;N&&h&&(h=h.session_data)&&g.Zl(N,[g.vN(h.itct)])};g.K(i3,b3);
i3.prototype.show=function(){if(!this.isActive){b3.prototype.show.call(this);if(!this.B){g.u9(this.Iz(),"iv-branding");var N=this.annotation.data;this.W=this.createElement({T:"img",M5:["branding-img","iv-click-target"],Z:{"aria-label":"Channel watermark",src:N.image_url,width:N.image_width,height:N.image_height}});g.DZ(this.W,!1);var h=this.createElement({T:"button",M5:["branding-img-container","ytp-button"]});h.appendChild(this.W);this.Iz().appendChild(h);var O=this.annotation.lR();O&&kK(this,h,
O,this.annotation.id,N.session_data);this.context.S.j("disable_branding_context")||b3m(this,N);this.B=!0}g.DZ(this.Iz(),!0);this.isActive=!0;if(this.W){try{UB5(this,this.W)}catch(u){}g.u9(this.context.S.getRootNode(),"ytp-branding-shown");this.context.S.getRootNode().style.setProperty("--branding-image-width",this.W.getAttribute("width")+"px")}}};
i3.prototype.hide=function(){this.isActive&&(b3.prototype.hide.call(this),g.DZ(this.Iz(),!1),this.isActive=!1,g.UC(this.context.S.getRootNode(),"ytp-branding-shown"))};
i3.prototype.destroy=function(){this.G&&(this.G.dispose(),this.G=null);g.UC(this.context.S.getRootNode(),"ytp-branding-shown");b3.prototype.destroy.call(this)};g.K(Bu4,b3);g.w=Bu4.prototype;g.w.show=function(){this.isActive||(b3.prototype.show.call(this),this.D||(AaY(this),this.D=!0),g.DZ(this.Iz(),!0),g.Js(function(){g.UC(this.Iz(),"iv-promo-inactive")},100,this),this.Iz().removeAttribute("aria-hidden"),this.isActive=!0,zcm(this),oP4(this),QUo(this,this.V))};
g.w.hide=function(){this.isActive&&(g.u9(this.Iz(),"iv-promo-inactive"),this.isActive=!1,this.Iz().setAttribute("aria-hidden","true"))};
g.w.BC=function(N,h,O,u,D,U){return this.isCollapsed?!1:b3.prototype.BC.call(this,N,h,O,u,D,U)};
g.w.Gm=function(N){this.Y=!0;CL5(this,500,N)};
g.w.e1=function(){this.Y=!1;LRY(this)};
g.w.K8=function(N){N.stopPropagation();this.hide()};
g.w.DD=function(N){N.stopPropagation();zcm(this);this.isCollapsed=!0;g.u9(this.Iz(),"iv-promo-collapsed-no-delay");this.L.start()};
g.w.destroy=function(){this.L.dispose();b3.prototype.destroy.call(this)};g.K(wPK,g.Vq);g.w=wPK.prototype;g.w.kx=function(N,h){if(!aQY(this.player.K().playerStyle))return null;switch(N){case "loadCustomAnnotationsXml":return(N=g.Zi(h))&&$Bj(this,N),!0;case "removeCustomAnnotationById":return h&&this.G&&(lWS(this.G,h),eM(this.player)),!0}return null};
g.w.getOptions=function(){return aQY(this.player.K().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.w.xz=function(){var N=this.player.K(),h=this.player.getVideoData(),O=N.annotationsLoadPolicy||h.annotationsLoadPolicy;return h.E8||this.player.isMutedByEmbedsMutedAutoplay()?!1:O===1&&!h.VC||N.m$.get(h.videoId)||g.GL(h)||g.bw(h)?!0:!1};
g.w.h$=function(){if(this.U){var N=this.player.zO().getVideoContentRect(!0);g.Ol(this.U.element,N.width,N.height);g.Z0(this.U.element,N.left,N.top)}if(this.G){var h=this.player.r9();N=this.G;h=h.width;g.GC(N.X,"iv-drawer-small",h<=426);g.GC(N.X,"iv-drawer-big",h>=1280)}};
g.w.CP=function(N){mB5(this,N.state);g.Y(N.state,2)&&(this.q3()&&this.MD()&&this.player.getPresentingPlayerType()!==2&&this.wi(!1),this.un(!1))};
g.w.load=function(){function N(d){var b=h.loadNumber;h.L=null;h.loaded&&h.loadNumber===b&&h.player.getVideoData().videoId===u&&(d=g.BY(d)&&d.responseXML?d.responseXML:null)&&($Bj(h,d),g.u9(h.player.getRootNode(),"iv-module-loaded"))}
var h=this;g.Vq.prototype.load.call(this);mB5(this,this.player.getPlayerStateObject());this.loadNumber++;var O=this.player.getVideoData(),u=O.videoId;g.nE()&&(N=ya4(this,N));var D={format:"XML",onFinish:N,onError:function(){h.L=null},
urlParams:{}};O.isPharma&&(D.urlParams.pharma="1");D.method="POST";D.withCredentials=!0;var U=this.player.K().m$.get(u);U&&V45(D,U);U=U&&(U.kK||U.s4);if(!O.GN||U)O.O3?IQK(this,O.O3,D):(this.B=function(){if(!h.Y)h.onVideoDataChange(D);var d=h.player.getVideoData();(d==null?0:g.dg(d))&&!h.eS&&pP4(h,d)},this.player.addEventListener("videodatachange",this.B));
g.O9(this.player,this.U.element,4);this.h$();(U=g.GL(O))&&M4Y(this,U);(U=g.bw(O))&&U.featuredChannel&&caS(this,U.featuredChannel,U.annotationId||"branding",O.videoId||null,O.eventId||null);this.wc=g.iD("ytp-cards-button",this.player.getRootNode());g.dg(O)&&pP4(this,O)};
g.w.onVideoDataChange=function(N){var h=this.player.getVideoData();h.O3&&IQK(this,h.O3,N)};
g.w.unload=function(){this.player.SV("annotations_module");for(var N=g.I(Object.keys(this.V)),h=N.next();!h.done;h=N.next())this.V[h.value].destroy();this.D=null;this.G&&(this.G.destroy(),this.G=null,eM(this.player));this.Y=!1;this.L&&(this.L.abort(),this.L=null);this.eS=!1;this.V={};this.W.hide();g.Vq.prototype.unload.call(this);this.U.detach();this.B&&(this.player.removeEventListener("videodatachange",this.B),this.B=null)};
g.w.qp=function(N){N===this.player.getVideoData().videoId&&(this.loaded?Rcj(this):this.load())};
g.w.q3=function(){var N;return((N=this.G)==null?void 0:N.isAvailable())||this.eS};
g.w.MD=function(){return!!this.G&&this.G.U};
g.w.wi=function(N,h,O){h=h===void 0?!1:h;this.q3();this.G&&(N?O?hG(this.G,O,h):hG(this.G,"YOUTUBE_DRAWER_AUTO_OPEN",h):OZ(this.G))};
g.w.un=function(N,h){this.player.publish(N?"cardsteasershow":"cardsteaserhide",h)};
g.w.q5=function(){this.player.K().m$.unsubscribe("vast_info_card_add",this.qp,this);g.UC(this.player.getRootNode(),g.$A.IV_DRAWER_OPEN);for(var N=this.fC,h=g.jD,O=0,u=N.length;O<u;O++)h.UZ(N[O]);this.fC.length=0;g.Vq.prototype.q5.call(this)};
g.w.createElement=function(N){N=new g.f(N);g.H(this,N);return N.element};g.yq("annotations_module",wPK);g.yq("creatorendscreen",o_V);})(_yt_player);
