(function(g){var window=this;'use strict';var S$V=function(N,h,O){g.c(function(u){N.G=g.tY(h,O);g.yy(u)})},AG=function(N){N.isActive()||N.start()},H3r=function(N,h){return h?N.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},TuK=function(N){return g.yv(N)||N.j("web_enable_caption_language_preference_stickiness")},WRS=function(N,h){var O=new g.Tu;
O.languageCode=N.languageCode;O.languageName=N.languageName;O.name=N.name;O.displayName=N.displayName;O.kind=N.kind;O.isDefault=!1;O.G=N.G;O.isTranslateable=N.isTranslateable;O.vssId=N.vssId;O.url=N.url;O.translationLanguage=h;N.xtags&&(O.xtags=N.xtags);N.captionId&&(O.captionId=N.captionId);return O},XPj=function(N,h){var O,u,D;
return g.c(function(U){if(U.G==1)return O=N+"|"+h,g.E(U,g.xT(),2);if(U.G!=3){u=U.W;if(!u)throw g.zg("gct");return g.E(U,g.Gd(u),3)}D=U.W;return U.return(D.get("captions",O))})},fQV=function(N,h,O){XPj(N,h).then(function(u){u&&O(u.trackData,new g.Tu(u.metadata))})},xBV=function(N){if(!Y$r.test(N))throw Error("'"+N+"' is not a valid hex color");
N.length==4&&(N=N.replace(lQV,"#$1$1$2$2$3$3"));N=N.toLowerCase();N=parseInt(N.slice(1),16);return[N>>16,N>>8&255,N&255]},nPx=function(){var N=void 0;
N=N===void 0?{}:N;var h="suggest_correction"in g.vZm?g.vZm.suggest_correction:"Edit caption";h=h||"";var O={},u;for(u in N){O={F7:O.F7};O.F7=u;var D=function(U){return function(){return String(N[U.F7])}}(O);
h=h.replace(new RegExp("\\$\\{"+O.F7+"\\}","gi"),D);h=h.replace(new RegExp("\\$"+O.F7,"gi"),D)}return h},FR5=function(){return g.en("yt-player-caption-display-settings")},ow=function(){this.segments=[]},Z3j=function(N,h){var O=g.T5(N.segments,h);
O>=0||O<0&&(-O-1)%2===1||(O=-O-1,O>0&&h-N.segments[O-1]===1&&O<N.segments.length&&N.segments[O]-h===1?(g.$Y(N.segments,O),g.$Y(N.segments,O-1)):O>0&&h-N.segments[O-1]===1?N.segments[O-1]=h:O<N.segments.length&&N.segments[O]-h===1?N.segments[O]=h:(g.jx(N.segments,O,0,h),g.jx(N.segments,O+1,0,h)))},k_j=function(N,h,O,u,D,U){g.S.call(this);
this.policy=N;this.player=h;this.eS=O;this.Y=u;this.L=D;this.D=U;this.X=new ow;this.V=-1;this.W=this.U=this.G=null;this.fC=0;this.B=new g.YL(this.ws,1E3,this);this.events=new g.yg(this);g.H(this,this.B);g.H(this,this.events);this.events.J(h,"SEEK_COMPLETE",this.mS);this.mS();this.ws()},NhK=function(N){return N.G&&N.G.V?N.G.V+N.player.Ho()<N.player.getCurrentTime():!1},ho5=function(N,h){if(N.policy.Gz&&N.player.NB()){var O=g.AL(h,N.policy,{});
O.set("pot",N.player.NB());O=O.lR()}else O=g.AL(h,N.policy,{}).lR();var u={format:"RAW",withCredentials:!0};if(N.policy.FA){u.method="POST";var D=h.X;D&&Object.keys(D).length>0?u.postBody=g.xD(D,g.aY):u.postBody=(0,g.Ht)([120,0])}N.L&&(u.responseType="arraybuffer");var U=++N.fC,d=(0,g.to)();N.W=g.RQ(O,u,3,100,-1,function(b){b.errorCode==="net.timeout"&&N.player.GO("capnt",{rn:U++})}).then(function(b){if(N.policy.L1&&U%100===1){var B=(0,g.to)();
N.player.GO("caprsp",{rn:U,ms:B-d,kb:(b.xhr.responseText.length/1024).toFixed()})}a:{b=b.xhr;N.SS();if(N.U){var C=!(N.L?b.response:b.responseText)||b.status>=400;if(B=g.Gmy(b)){b=g.AL(N.U,N.policy,{});N.U.mJ(b,B);ho5(N,N.U);break a}if(C)N.player.GO("capfail",{status:b.status});else{var A;g.Ok("fcb_r",(0,g.to)(),((A=N.player.getVideoData())==null?void 0:A.eS)||"");A=N.U.JQ[0];B=A.hQ;N.Y!=null&&N.V!==B&&(N.L?N.Y(b.response,(A.startTime+N.player.Ho())*1E3):N.Y(b.responseText,(A.startTime+N.player.Ho())*
1E3),N.V=B)}}N.U=null;N.W=null}}).Es(function(b){N.U=null;
N.W=null;var B;N.player.GO("capfail",{rn:U,status:(B=b.xhr)==null?void 0:B.status})});
N.U=h;Z3j(N.X,N.U.JQ[0].hQ)},QZ=function(N,h){g.PB.call(this,h);
this.G=N;this.S=h;this.X=null;this.V=!1;this.logger=new g.tL("caps");this.B=g.wdd(this.S,this.G)},uWn=function(N,h){var O=[],u;
for(u in N.G.G)if(N.G.G.hasOwnProperty(u)){var D=N.G.G[u];if(g.pP(D,h||null)){var U=D.info.id,d=U,b="."+U,B="",C="";if(D=D.info.captionTrack)U=D.languageCode,d=D.displayName,b=D.vssId,B=D.kind,C=D.id;else{D=U;var A=g.HIY.get(D);A==null&&(A=OM4[D]||OM4[D.replace(/-/g,"_")],g.HIY.set(D,A));D=A;d=D||d}O.push(new g.Tu({id:u,languageCode:U,languageName:d,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:b,kind:B,captionId:C}))}}return O},D1S=function(N,h){return h!=null&&h in N.G.G?N.G.G[h]:null},
U15=function(N,h,O){var u=[],D;
for(D in N.G.G)if(N.G.G.hasOwnProperty(D)){var U=N.G.G[D];if(g.pP(U,O||null)){var d=U.info.captionTrack;d&&d.languageCode===h&&u.push(U)}}return u.length?u[0]:null},Ll=function(N,h,O,u,D,U,d,b,B,C){var A=C.isInline()&&!0,Q={};
Object.assign(Q,h);Object.assign(Q,N.params);Object.assign(Q,O);var L={};Object.assign(L,h.YF);N.params.YF&&Object.assign(L,N.params.YF);Object.assign(L,O.YF);A&&(Q.windowOpacity=.6,L.backgroundOpacity=0);Q.YF=L;var z=Q.cg===1,v=[{T:"span",N:"captions-text",Z:{style:"word-wrap: normal; display: block;"}}],t,R,p;(b=b.nC("caption_edit_on_hover")&&((t=C.getVideoData().getPlayerResponse())==null?void 0:(R=t.captions)==null?void 0:(p=R.playerCaptionsTracklistRenderer)==null?void 0:p.openTranscriptCommand))&&
v.unshift({T:"button",N:"caption-edit",Z:{tabindex:"0","aria-label":nPx()},C:[{T:"svg",Z:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},C:[{T:"path",Z:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.f.call(this,{T:"div",N:"caption-window",Z:{id:"caption-window-"+N.id,dir:z?"rtl":"ltr",tabindex:"0",lang:Q.lang},C:v});var M=
this;this.V=[];this.b0=!1;this.W=N;this.m$=this.FA=null;this.rU=U;this.yd=d;this.B=null;this.maxWidth=U*.96;this.maxHeight=d*.96;this.G=Q;this.Ad=O;this.fC=h;this.X=this.Ir("captions-text");this.UJ=this.X.style.getPropertyValue("box-decoration-break")!==""||this.X.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.HB=d1Y(u,D,U,d);this.Po=B;b&&(this.L=this.Ir("caption-edit"),this.J(this.L,"click",function(){M.Po()}));
this.type=0;this.u0=this.HB*GSR(L);this.KC=A;N=new g.HL(this.element,!0);g.H(this,N);N.subscribe("dragstart",this.Du,this);N.subscribe("dragmove",this.KP,this);N.subscribe("dragend",this.EV,this);this.PB=this.pC=this.CC=this.xn=0;N="";this.G.windowOpacity&&(N=xBV(this.G.windowColor),N="rgba("+N[0]+","+N[1]+","+N[2]+","+this.G.windowOpacity+")");h={"background-color":N,display:this.G.isVisible===!1?"none":"","text-align":bMn[this.G.textAlign]};this.UJ&&(h["border-radius"]=N?this.u0/8+"px":"");(this.U=
this.W.params.cg===2||this.W.params.cg===3)&&iMS(this,this.element);g.fF(this.element,h);if(A){var a;(a=this.element.parentElement)==null||a.style.setProperty("--caption-window-color",N)}switch(this.G.qf){case 0:case 1:case 2:g.u9(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.u9(this.element,"ytp-caption-window-bottom")}},iMS=function(N,h){var O="vertical-rl";
N.G.o0===1&&(O="vertical-lr");g.Cd&&(O=O==="vertical-lr"?"tb-lr":"tb-rl");g.fF(h,"-o-writing-mode",O);g.fF(h,"-webkit-writing-mode",O);g.fF(h,"writing-mode",O);g.fF(h,"text-orientation","upright");g.u9(h,"ytp-vertical-caption");N.W.params.cg===3&&(g.fF(h,"text-orientation",""),g.fF(h,"transform","rotate(180deg)"))},GSR=function(N){var h=1+.25*(N.fontSizeIncrement||0);
if(N.offset===0||N.offset===2)h*=.8;return h},BhV=function(N,h){var O={},u=h.background?h.background:N.G.YF.background;
if(h.backgroundOpacity!=null||h.background){var D=h.backgroundOpacity!=null?h.backgroundOpacity:N.G.YF.backgroundOpacity;u=xBV(u);O.background="rgba("+u[0]+","+u[1]+","+u[2]+","+D+")";N.UJ&&(O["box-decoration-break"]="clone",O["border-radius"]=N.u0/8+"px")}if(h.fontSizeIncrement!=null||h.offset!=null)O["font-size"]=N.HB*GSR(h)+"px";u=1;D=h.color||N.G.YF.color;if(h.color||h.textOpacity!=null)D=xBV(D),u=h.textOpacity==null?N.G.YF.textOpacity:h.textOpacity,D="rgba("+D[0]+","+D[1]+","+D[2]+","+u+")",
O.color=D,O.fill=D;var U=h.charEdgeStyle;U===0&&(U=void 0);if(U){D="rgba(34, 34, 34, "+u+")";var d="rgba(204, 204, 204, "+u+")";h.Q9&&(d=D=h.Q9);var b=N.HB/16/2,B=Math.max(b,1),C=Math.max(2*b,1),A=Math.max(3*b,1),Q=Math.max(5*b,1);u=[];switch(U){case 4:for(;A<=Q;A+=b)u.push(C+"px "+C+"px "+A+"px "+D);break;case 1:C=window.devicePixelRatio>=2?.5:1;for(U=B;U<=A;U+=C)u.push(U+"px "+U+"px "+D);break;case 2:u.push(B+"px "+B+"px "+d);u.push("-"+B+"px -"+B+"px "+D);break;case 3:for(A=0;A<5;A++)u.push("0 0 "+
C+"px "+D)}O["text-shadow"]=u.join(", ")}D="";switch(h.fontFamily){case 1:D='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:D='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:D='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:D='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:D='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:D=g.HY()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:D='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}D&&(O["font-family"]=D);D=h.offset;D==null&&(D=N.G.YF.offset);switch(D){case 0:O["vertical-align"]="sub";break;case 2:O["vertical-align"]="super"}h.fontFamily===7&&(O["font-variant"]="small-caps");h.bold&&(O["font-weight"]="bold");h.italic&&(O["font-style"]="italic");h.underline&&(O["text-decoration"]=
"underline");h.Hp&&(O.visibility="hidden");h.Qw===1&&N.U&&(O["text-combine-upright"]="all",O["text-orientation"]="mixed",D=g.Ma||g.QG,N.W.params.cg===3?O.transform=D?"rotate(90deg)":"rotate(180deg)":D&&(O.transform="rotate(-90deg)"));if(h.textEmphasis===1||h.textEmphasis===2||h.textEmphasis===3||h.textEmphasis===4||h.textEmphasis===5)if(g.Ma)O["font-weight"]="bold";else switch(O["text-emphasis-style"]="filled circle",O["text-emphasis-color"]="currentcolor",O["webkit-text-emphasis"]="filled circle",
h.textEmphasis){case 4:case 3:O["text-emphasis-position"]="under left";O["webkit-text-emphasis-position"]="under left";break;case 5:case 2:O["text-emphasis-position"]="over right",O["webkit-text-emphasis-position"]="over right"}return O},zP=function(N){N=N.split("px");
return N.length>0?(N=Number(N[0]))?N:0:0},CvS=function(N){N.B=g.LF("SPAN");
g.fF(N.B,{display:"block"});g.u9(N.B,"caption-visual-line");N.X.appendChild(N.B)},A34=function(N,h){var O=g.LF("SPAN");
g.fF(O,{display:"inline-block","white-space":"pre-wrap"});g.fF(O,BhV(N,h));O.classList.add("ytp-caption-segment");N.B.appendChild(O);O.previousElementSibling&&(g.fF(O.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.fF(O,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return O},o0j=function(N,h,O){N.b0=N.b0||!!O;
var u={};Object.assign(u,N.G.YF);Object.assign(u,O||h.G);Object.assign(u,N.Ad.YF);(O=!N.B)&&CvS(N);for(var D=N.FA&&N.m$&&g.LZ(u,N.m$)?N.FA:A34(N,u),U=typeof h.text==="string",d=U?h.text.split("\n"):[h.text],b=0;b<d.length;b++){var B=b>0||!h.append,C=d[b];B&&!O?(CvS(N),D=A34(N,u)):B&&O&&(O=!1);C&&(D.appendChild(U?g.zy(C):C),U||C.tagName!=="RUBY"||C.childElementCount!==4||g.Ma||!g.lD(C.children[2],"text-emphasis")||(B=N.U?"padding-right":"padding-top",g.lD(C.children[2],"text-emphasis-position")&&(B=
N.U?"padding-left":"padding-bottom"),g.CF?g.fF(D,B,"1em"):g.fF(D,B,"0.5em")))}N.m$=u;N.FA=D;N.V.push(h)},d1Y=function(N,h,O,u){var D=h/360*16;
h>=N&&(N=640,u>O*1.3&&(N=480),D=O/N*16);return D},LPo=function(){this.U=this.time=this.mode=this.W=0;
this.X=new Qk5(this);this.L=new Qk5(this);this.G=[];this.clear()},v0K=function(N,h,O){if(N===255&&h===255||!N&&!h)return{ZE:N,
YG:h,result:0};N=zox[N];h=zox[h];if(N&128){var u;if(u=!(h&128))u=h,u=O.R2()&&O.YG===u;if(u)return{ZE:N,YG:h,result:1}}else if(h&128&&1<=N&&N<=31)return{ZE:N,YG:h,result:2};return{ZE:N,YG:h,result:3}},KPR=function(N,h,O,u){h===255&&O===255||!h&&!O?(++N.U===45&&N.reset(),N.X.W.clear(),N.L.W.clear()):(N.U=0,wnY(N.X,h,O,u))},m1x=function(N,h){N.G.sort(function(D,U){var d=D.time-U.time;
return d===0?D.order-U.order:d});
for(var O=g.I(N.G),u=O.next();!u.done;u=O.next())u=u.value,N.time=u.time,u.type===0?KPR(N,u.ph,u.wF,h):u.type===1&&N.W&496&&wnY(N.L,u.ph,u.wF,h);N.G.length=0},vh=function(){this.type=0},w7=function(){this.state=this.YG=this.ZE=0},Ipr=function(){this.timestamp=this.G=0},Kl=function(N){this.L=N;
this.U=[];this.G=this.W=this.row=0;this.style=new vh;for(N=this.X=0;N<=15;N++){this.U[N]=[];for(var h=0;h<=32;h++)this.U[N][h]=new Ipr}},mc=function(N,h){if(N.style.type===3){for(var O=0,u=0,D=N.L.time+0,U="",d="",b=D,B=1;B<=15;++B){for(var C=!1,A=u?u:1;A<=32;++A){var Q=N.U[B][A];
if(Q.G!==0){O===0&&(O=B,u=A);C=String.fromCharCode(Q.G);var L=Q.timestamp;L<D&&(D=L);Q.timestamp=b;d&&(U+=d,d="");U+=C;C=!0}if((Q.G===0||A===32)&&C){d="\n";break}else if(u&&!C)break}if(O&&!C)break}U&&h.X(O,u,D,b,U)}else for(u=O=0,U=D=N.L.time+0,d=1;d<=15;++d)for(b="",B=1;B<=32;++B)if(A=N.U[d][B],Q=A.G,Q!==0&&(O===0&&(O=d,u=B),C=String.fromCharCode(Q),L=A.timestamp,L<=D&&(D=L),b+=C,A.reset()),B===32||Q===0)b&&h.X(O,u,D,U,b),D=U,b="",u=O=0},RoY=function(N,h){switch(N){case 0:return twm[(h&127)-32];
case 1:return $1r[h&15];case 2:return y3n[h&31];case 3:return Vwm[h&31]}return 0},Iw=function(N){return N.U[N.row][N.W]},tG=function(N,h,O){h>=2&&N.W>1&&(--N.W,Iw(N).G=0);
var u=Iw(N);u.timestamp=N.L.time+0;u.G=RoY(h,O);N.W<32&&N.W++},Pvm=function(N,h,O,u){for(var D=0;D<u;D++)for(var U=0;U<=32;U++){var d=N.U[h+D][U],b=N.U[O+D][U];
d.G=b.G;d.timestamp=b.timestamp}},$t=function(N,h,O){for(var u=0;u<O;u++)for(var D=0;D<=32;D++)N.U[h+u][D].reset()},MwV=function(N){N.row=N.G>0?N.G:1;
N.W=1;$t(N,0,15)},pnS=function(N){this.U=N;
this.L=0;this.style=new vh;this.V=new Kl(this.U);this.B=new Kl(this.U);this.text=new Kl(this.U);this.W=this.V;this.X=this.B;this.G=this.W},eoK=function(N,h,O){var u=N.W,D=!1;
switch(N.style.get()){case 4:case 1:case 2:N.style.get()===4&&u.G>0||(mc(u,O),MwV(N.W),MwV(N.X),u.row=15,u.G=h,D=!0)}N.style.set(3);N.G=u;N.G.style=N.style;N.U.mode=1<<u.X;D?u.W=1:u.G!==h&&(u.G>h?(mc(u,O),$t(u,u.row-u.G,h)):u.row<h&&(h=u.G),u.G=h)},E0V=function(N){N.style.set(1);
N.G=N.X;N.G.G=0;N.G.style=N.style;N.U.mode=1<<N.G.X},c3V=function(N){N.style.set(4);
N.G=N.text;N.G.style=N.style;N.U.mode=1<<N.G.X},Qk5=function(N){this.G=N;
this.L=0;this.U=new pnS(this.G);this.V=new pnS(this.G);this.W=new w7;this.X=this.U},wnY=function(N,h,O,u){N.W.update();
h=v0K(h,O,N.W);switch(h.result){case 0:return;case 1:case 2:return}var D=h.ZE;O=h.YG;if(32<=D||!D)N.G.mode&N.G.W&&(h=D,h&128&&(h=127),O&128&&(O=127),N=N.X.G,h&96&&tG(N,0,h),O&96&&tG(N,0,O),h!==0&&O!==0&&N.style.type===3&&mc(N,u));else if(D&16)a:if(!N.W.matches(D,O)&&(h=N.W,h.ZE=D,h.YG=O,h.state=2,h=D&8?N.V:N.U,N.X=h,N.G.mode=1<<(N.L<<2)+(h.L<<1)+(h.style.type===4?1:0),(N.G.mode|1<<(N.L<<2)+(h.L<<1)+(h.style.type!==4?1:0))&N.G.W))if(O&64){u=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(D&7)<<1|O>>5&1];
N=O&16?((O&14)>>1)*4:0;O=h.G;switch(h.style.get()){case 4:u=O.row;break;case 3:if(u!==O.row){if(u<O.G&&(u=O.G,u===O.row))break;var U=1+O.row-O.G,d=1+u-O.G;Pvm(O,d,U,O.G);h=U;D=O.G;d<U?(U=d+D-U,U>0&&(h+=U,D-=U)):(U=U+D-d,U>0&&(D-=U));$t(O,h,D)}}O.row=u;O.W=N+1}else switch(D&7){case 1:switch(O&112){case 32:tG(h.G,0,32);break a;case 48:O===57?(u=h.G,Iw(u).G=0,u.W<32&&u.W++):tG(h.G,1,O&15)}break;case 2:O&32&&tG(h.G,2,O&31);break;case 3:O&32&&tG(h.G,3,O&31);break;case 4:case 5:if(32<=O&&O<=47)switch(O){case 32:E0V(h);
break;case 33:u=h.G;u.W>1&&(--u.W,Iw(u).G=0);break;case 36:u=h.G;h=Iw(u);for(N=0;N<=15;N++)for(O=0;O<=32;O++)if(u.U[N][O]===h){for(;O<=32;O++)u.U[N][O].reset();break}break;case 37:eoK(h,2,u);break;case 38:eoK(h,3,u);break;case 39:eoK(h,4,u);break;case 40:tG(h.G,0,32);break;case 41:h.style.set(2);h.G=h.W;h.G.G=0;h.G.style=h.style;h.U.mode=1<<h.G.X;break;case 42:u=h.text;u.G=15;u.style.set(4);MwV(u);c3V(h);break;case 43:c3V(h);break;case 44:N=h.W;switch(h.style.get()){case 1:case 2:case 3:mc(N,u)}$t(N,
0,15);break;case 45:b:{N=h.G;switch(h.style.get()){default:case 2:case 1:break b;case 4:if(N.row<15){++N.row;N.W=1;break b}break;case 3:}N.G<2&&(N.G=2,N.row<N.G&&(N.row=N.G));h=N.row-N.G+1;mc(N,u);Pvm(N,h,h+1,N.G-1);$t(N,N.row,1)}break;case 46:$t(h.X,0,15);break;case 47:mc(h.W,u),h.X.updateTime(h.U.time+0),u=h.X,h.X=h.W,h.W=u,E0V(h)}break;case 7:switch(O){case 33:case 34:case 35:u=h.G,(u.W+=O&3)>32&&(u.W=32)}}},apS=function(){},yZ=function(N,h,O,u,D,U,d){U=U===void 0?!1:U;
d=d===void 0?null:d;g.Ym.call(this,N,N+h,{priority:O,namespace:"captions"});this.windowId=u;this.text=D;this.append=U;this.G=d},g0V=function(N,h,O,u,D,U,d){var b=U[0],B=d[b.getAttribute("p")];
if(B.Ih===1){var C=U[1],A=U[2];U=U[3];b.getAttribute("t");C.getAttribute("t");A.getAttribute("t");U.getAttribute("t");b.getAttribute("p");C.getAttribute("p");U.getAttribute("p");d=d[A.getAttribute("p")];b=q1x(b.textContent,C.textContent,A.textContent,U.textContent,d);return new yZ(N,h,D,O,b,u,B)}switch(B.Ih){case 9:case 10:B.textEmphasis=1;break;case 11:B.textEmphasis=2;break;case 12:B.textEmphasis=3;break;case 13:B.textEmphasis=4;break;case 14:B.textEmphasis=5}return new yZ(N,h,D,O,b.textContent||
"",u,B)},q1x=function(N,h,O,u,D){var U=g.HY(),d=U?g.LF("DIV"):g.LF("RUBY"),b=g.LF("SPAN");
b.textContent=N;d.appendChild(b);N=U?g.LF("DIV"):g.LF("RP");N.textContent=h;d.appendChild(N);h=U?g.LF("DIV"):g.LF("RT");h.textContent=O;d.appendChild(h);O=D.Ih;if(O===10||O===11||O===12||O===13||O===14)if(g.fF(h,"text-emphasis-style","filled circle"),g.fF(h,"text-emphasis-color","currentcolor"),g.fF(h,"webkit-text-emphasis","filled circle"),D.Ih===11||D.Ih===13)g.fF(h,"webkit-text-emphasis-position","under left"),g.fF(h,"text-emphasis-position","under left");O=!0;if(D.Ih===4||D.Ih===7||D.Ih===12||
D.Ih===14)g.fF(d,"ruby-position","over"),g.fF(d,"-webkit-ruby-position","before");else if(D.Ih===5||D.Ih===6||D.Ih===11||D.Ih===13)g.fF(d,"ruby-position","under"),g.fF(d,"-webkit-ruby-position","after"),O=!1;D=U?g.LF("DIV"):g.LF("RP");D.textContent=u;d.appendChild(D);U&&(u=O,g.fF(d,{display:"inline-block",position:"relative"}),U=d.firstElementChild.nextElementSibling,g.fF(U,"display","none"),U=U.nextElementSibling,g.fF(U,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.fF(d.lastElementChild,"display","none"),u?(g.fF(d,"padding-top","0.6em"),g.fF(U,"top","0")):(g.fF(d,"padding-bottom","0.6em"),g.fF(U,"bottom","0")));return d},VZ=function(){g.S.apply(this,arguments)},Rw=function(N,h,O,u,D){g.Ym.call(this,N,N+h,{priority:O,
namespace:"captions"});this.id=u;this.params=D;this.G=[]},r3o=function(N){var h="_"+Ph++;
return new Rw(0,0x8000000000000,0,h,N)},ME=function(N){VZ.call(this);
this.X=N;this.pens={};this.Y={};this.D={};this.L="_"+Ph++;this.B={};this.W=this.G=null;this.V=!0},pl=function(N,h){N=N.getAttribute(h);
if(N!=null)return Number(N)},ea=function(N,h){N=N.getAttribute(h);
if(N!=null)return N==="1"},EZ=function(N,h){N=pl(N,h);
return N!==void 0?N:null},aw=function(N,h){N=N.getAttribute(h);
if(N!=null)return ch.test(N),N},skR=function(N,h){var O={},u=h.getAttribute("ws");
Object.assign(O,u?N.D[u]:N.X);N=EZ(h,"mh");N!=null&&(O.kd=N);N=EZ(h,"ju");N!=null&&(O.textAlign=N);N=EZ(h,"pd");N!=null&&(O.cg=N);N=EZ(h,"sd");N!=null&&(O.o0=N);N=aw(h,"wfc");N!=null&&(O.windowColor=N);h=pl(h,"wfo");h!==void 0&&(O.windowOpacity=h/255);return O},J3j=function(N,h){var O={},u=h.getAttribute("wp");
u&&Object.assign(O,N.Y[u]);N=EZ(h,"ap");N!=null&&(O.qf=N);N=pl(h,"cc");N!=null&&(O.aH=N);N=pl(h,"ah");N!=null&&(O.sZ=N);N=pl(h,"rc");N!=null&&(O.Mu=N);h=pl(h,"av");h!=null&&(O.fK=h);return O},jkV=function(N,h,O,u){var D={};
Object.assign(D,J3j(N,h));Object.assign(D,skR(N,h));u?g.LZ(D,N.X)?(u=N.L,D=N.X):u="_"+Ph++:u=h.getAttribute("id")||"_"+Ph++;N=pl(h,"t")+O;h=pl(h,"d")||0x8000000000000;if(D.cg===2||D.cg===3)O=D.Mu,D.Mu=D.aH,D.aH=O;return new Rw(N,h,0,u,D)},qE=function(N){VZ.call(this);
this.V=N;this.G=new Map;this.X=new Map;this.L=new Map;this.W=new Map},g7=function(N){N=g.S8(Math.round(N),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-N.length)+N},S1m=function(N,h,O,u,D){u===0&&(u=0x8000000000000);
var U={};h.wpWinPosId&&Object.assign(U,N.X.get(h.wpWinPosId));h.wsWinStyleId&&Object.assign(U,N.L.get(h.wsWinStyleId));N=h.rcRowCount;N!==void 0&&(U.Mu=N);h=h.ccColCount;h!==void 0&&(U.aH=h);if(U.cg===2||U.cg===3)h=U.Mu,U.Mu=U.aH,U.aH=h;return new Rw(O,u,0,D,U)},r7=function(N,h,O){g.PB.call(this,N);
this.videoData=h;this.audioTrack=O;this.L=h.XL},sZ=function(N,h,O,u,D,U,d,b,B,C){Ll.call(this,N,h,O,u,D,U,d,b,B,C);
this.type=1},JG=function(N,h,O){this.trackData=N;
this.V=O;this.version=this.L=this.U=this.byteOffset=0;this.W=[];this.G=new DataView(this.trackData)},Sa=function(N){var h=N.byteOffset;
N.byteOffset+=1;return N.G.getUint8(h)},Hh=function(N){var h=N.byteOffset;
N.byteOffset+=4;return N.G.getUint32(h)},TP=function(N,h){VZ.call(this);
this.W=N;this.X=h;this.track=this.X.languageName==="CC3"?4:0;this.G=new LPo;this.G.W=1<<this.track},Thj=function(N){if(typeof N==="string")return!1;
N=new JG(N,8,0);return HMS(N)},HMS=function(N){if(!(N.byteOffset<N.G.byteLength)||Hh(N)!==1380139777)return!1;
N.version=Sa(N);if(N.version>1)return!1;Sa(N);Sa(N);Sa(N);return!0},Wh=function(N,h,O,u,D,U,d,b,B,C){Ll.call(this,N,h,O,u,D,U,d,b,B,C);
var A=this;this.type=2;this.vB=[];this.eS=this.D=this.O3=0;this.TO=NaN;this.e6=0;this.j6=null;this.GZ=new g.YL(this.Wz,433,this);this.L&&(C.createClientVe(this.L,this,167342),this.J(this.L,"click",function(){C.logClick(A.L)}),N=new g.HL(this.element,!0),g.H(this,N),N.subscribe("hoverstart",function(){C.logVisibility(A.L,!0)},this));
g.u9(this.element,"ytp-caption-window-rollup");g.H(this,this.GZ);g.fF(this.element,"overflow","hidden")},WPr=function(N,h){if(!h)return"";
N.U&&N.W.params.o0!==1&&(h*=-1);return"translate"+(N.U?"X":"Y")+"("+h+"px)"},Xnr=function(N){N.vB=Array.from(N.element.getElementsByClassName("caption-visual-line"));
for(var h=N.W.params.Mu,O=0,u=0,D=N.vB.length-1;O<h&&D>-1;){var U=N.vB[D];u+=N.U?U.offsetWidth:U.offsetHeight;O++;D--}N.D=u;h=Math;O=h.max;isNaN(N.TO)&&((u=N.G.aH)?(D=g.LF("SPAN"),g.tA(D,"\u2013".repeat(u)),g.fF(D,BhV(N,N.G.YF)),N.X.appendChild(D),N.TO=D.offsetWidth,N.X.removeChild(D)):N.TO=0);u=N.X;N.eS=O.call(h,N.TO,N.e6,(N.U?u.offsetHeight:u.offsetWidth)+1)},fpj=function(N,h){Xnr(N);
var O=N.vB.reduce(function(U,d){return(N.U?d.offsetWidth:d.offsetHeight)+U},0);
O=N.D-O;if(O!==N.O3){var u=O>0&&N.O3===0,D=O<N.O3;h||isNaN(O)||u||!D||(g.u9(N.element,"ytp-rollup-mode"),N.J(N.element,"transitionend",N.Wz));g.fF(N.X,"transform",WPr(N,O));N.O3=O}Xnr(N)},Y1x=function(N,h,O,u){var D=this;
this.S=N;this.U=h;this.logger=O;this.m9=u;this.eB=[];this.g6=[];this.G=null;this.KF={y_f:function(){return D.G},
nU:function(){return D.eB}};
N=g.u8(this.S.K().experiments,"html5_override_micro_discontinuities_threshold_ms");this.W=N>0?N:10},n0S=function(N,h){N.G=function(O,u){if(O.info.X){var D=O;
if(N.g6.length>0){for(D=N.g6.shift();N.g6.length>0;)D=g.R_(D,N.g6.shift());D=g.R_(D,O)}if(D){O=D;try{var U=g.Pr(O)*1E3}catch(C){U=O.info.startTime*1E3}try{var d=g.F1a(O)*1E3}catch(C){d=O.info.duration*1E3}if(U<0||d<0)U<0&&(U=O.info.startTime*1E3),d<0&&(d=O.info.duration*1E3);O.info.startTime=U/1E3;O.info.L=U/1E3;O.info.duration=d/1E3;O.info.Y=d/1E3;U=N.A2(D);d=U.hQ;U={formatId:U.formatId,startTimeMs:U.startTimeMs,durationMs:U.durationMs,Us:d,yG:d};d=lpY(N.eB,U.startTimeMs);var b=(O=d>=0?N.eB[d]:null)?
O.startTimeMs+O.durationMs:0,B=U.startTimeMs+U.durationMs;!O||U.startTimeMs-b>N.W?N.eB.splice(d+1,0,U):(O.durationMs=Math.max(b,B)-O.startTimeMs,O.yG=Math.max(O.yG,U.yG));u(N.eB);u=g.V8(D);x1x(N.U,u.buffer.slice(u.byteOffset,u.byteLength+u.byteOffset),h,D.info.L)}else N.logger.G(350058965,"Empty slice")}else N.g6.push(O)};
N.S.addEventListener("sabrCaptionsDataLoaded",N.G)},lpY=function(N,h){N=g.T5(N,{startTimeMs:h},function(O,u){return O.startTimeMs-u.startTimeMs});
return N>=0?N:-N-2},XX=function(N,h){g.PB.call(this,h);
this.G=N;this.S=h;this.logger=new g.tL("caps");this.X=this.V=null;this.B=new Y1x(this.S,this,this.logger,this.G.m9)},x1x=function(N,h,O,u){N.logger.debug(function(){return"SABR captions data received for "+u});
N.V?N.X==null?N.logger.G(350058965,"Null loaded track meta data at captions data received"):O.Fv(h,N.X,u*1E3):N.logger.G(350058965,"Null Representation at captions data received")},FPo=function(N,h){var O=[],u;
for(u in N.G.G)if(N.G.G.hasOwnProperty(u)){var D=N.G.G[u];if(g.pP(D,h||null)){var U=D.info.id,d=U,b="."+U,B="",C="";if(D=D.info.captionTrack)U=D.languageCode,d=D.displayName,b=D.vssId,B=D.kind,C=D.id;O.push(new g.Tu({id:u,languageCode:U,languageName:d,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:b,kind:B,captionId:C}))}}return O},ZM4=function(N,h,O){var u=[],D;
for(D in N.G.G)if(N.G.G.hasOwnProperty(D)){var U=N.G.G[D];if(g.pP(U,O||null)){var d=U.info.captionTrack;d&&d.languageCode===h&&u.push(U)}}return u.length?u[0]:null},kS4=function(N,h){if(!g.haa(N)||N.G!=null&&g.wdd(h,N.G)&&N.G.G.rawcc!=null)return!1;
h=!!N.G&&N.G.isManifestless&&Object.values(N.G.G).some(function(O){return g.pP(O,"386")});
N=!!N.G&&!N.G.isManifestless&&g.C5o(N.G);return h||N},NCS=function(){VZ.call(this)},Oe5=function(N){var h=hwR.length;
if(N.byteLength<h)return!1;N=new Uint8Array(N,0,h);for(var O=0;O<h;O++)if(hwR[O]!==N[O])return!1;return!0},uYS=function(N,h,O,u,D,U,d,b,B){switch(d.tagName){case "b":b.bold=!0;
break;case "i":b.italic=!0;break;case "u":b.underline=!0}for(var C=0;C<d.childNodes.length;C++){var A=d.childNodes[C];if(A.nodeType===3)A=new yZ(h,O,u,D.id,A.nodeValue,U||C>0,g.ox(b)?void 0:b),B.push(A),D.G.push(A);else{var Q={};Object.assign(Q,b);uYS(N,h,O,u,D,!0,A,Q,B)}}},Db4=function(N){var h=N.split(":");
N=0;h=g.I(h);for(var O=h.next();!O.done;O=h.next())N=N*60+Number(O.value);return N*1E3},UbY=function(N,h,O,u){u=Object.assign({kd:0},u);
return new Rw(N,h,O,"_"+Ph++,u)},fl=function(N,h){g.S.call(this);
this.S=N;this.Qm=h;this.G=null;this.W=this.S.HZ();this.logger=new g.tL("caps")},GD5=function(N,h,O){if(typeof h==="string"||Thj(h))return[{trackData:h,
Ez:O}];if(typeof h==="string"&&h.substring(0,6)==="WEBVTT"||typeof h!=="string"&&Oe5(h))return[{trackData:h,Ez:O}];var u=new DataView(h);if(u.byteLength<=8||u.getUint32(4)!==1718909296)return[];var D=g.kAo(u);if(N.W&&D){var U=g.Xb7(D),d=g.fba(D);D=D.g9;U&&D&&N.W.GJ(D,U,d)}N=g.$S(u,1835295092);if(!N||!N.length||!N[0].size)return[];U=[];for(d=0;d<N.length;d++)D=N[d],D=new Uint8Array(h,D.dataOffset,D.size-(D.dataOffset-D.offset)),D=g.L$(D),U.push({trackData:D,Ez:O+d*1E3});dbY(u,U,O);return U=U.filter(function(b){return!!b.trackData})},
dbY=function(N,h,O){var u=g.QJ(N,0,1836476516),D=9E4;
u&&(D=g.LG(u)||9E4);u=0;for(var U=g.$S(N,1836019558),d=0;d<U.length;d++){var b=U[d];d<h.length&&(b=g.QJ(N,b.dataOffset,1953653094))&&(b=g.QJ(N,b.dataOffset,1952867444))&&(b=g.IC(b)/D*1E3,d===0&&(u=b),h[d].Ez=b-u+O||O*d*1E3)}},ben=function(N,h,O){N.G||(N.G=new NCS);
N=N.G.U(h,O);Math.random()<.01&&g.pX(Error("Deprecated subtitles format in web player: WebVTT"));return N},ie5=function(N){var h={};
if(N=g.fK(N))h.lang=N,g.nyR.test(N)&&(h.cg=1);return h},AZo=function(N){g.Vq.call(this,N);
var h=this;this.S=N;this.FA=[];this.vB={};this.u0={};this.Y=!1;this.X="NONE";this.G=this.D=this.eS=this.HB=this.xn=null;this.GZ={AF:function(){h.AF()},
Fv:function(U,d,b,B){h.Fv(U,d,b,B)}};
this.W=null;this.Qm=this.S.K();this.videoData=this.S.getVideoData();this.CC=this.S.zO();this.U={YF:{}};this.V={YF:{}};g.my(this.videoData)?this.X="OFFLINE":kS4(this.videoData,this.S)?this.X="SABR_LIVE":g.K8a(this.videoData,this.S)?this.X="LIVE":this.videoData.captionTracks.length?this.X="INNERTUBE":this.videoData.HX&&(this.X="TTS");this.pC=this.Qm.controlsType==="3";this.PB=new fl(this.S,this.Qm);this.b0=new g.yg(this);this.B=new g.f({T:"div",N:"ytp-caption-window-container",Z:{id:"ytp-caption-window-container"}});
this.fC={top:0,right:0,bottom:0,left:0,width:1,height:1};var O=null,u=g.aJ("yt-html5-player-modules::subtitlesModuleData");u&&(O=new g.yD(u));this.storage=O;var D;this.KC=!((D=N.wU())==null||!D.ww());this.L=BCK(this);this.TO=!this.L&&this.pC&&this.KC&&(this.X==="LIVE"||this.X==="SABR_LIVE");g.H(this,this.PB);this.L?this.O3=this.m$=null:(this.m$=new g.fz(this.B7,void 0,this),g.H(this,this.m$),this.O3=new g.YL(this.cwB,2E3,this),g.H(this,this.O3));g.H(this,this.b0);g.O9(this.player,this.B.element,4);
g.H(this,this.B);this.L||this.b0.J(N,"resize",this.tp);(this.e6=g.bM(this.Qm)&&!g.Qx()&&!this.S.isFullscreen()&&!this.L&&!this.TO)&&this.b0.J(N,"resize",this.n6A);this.b0.J(N,"onPlaybackAudioChange",this.aTn);this.b0.J(N,g.xm("captions"),function(U){h.onCueRangeEnter(U)});
this.b0.J(N,g.np("captions"),function(U){h.onCueRangeExit(U)});
CNS(this,FR5()||{});this.player.yq("onCaptionsModuleAvailable")},LZ5=function(N){if(N.Qm.EZ===1||N.videoData.P0===1||g.Fa(N.videoData,"yt:cc")==="alwayson")return!0;
if(N.videoData.captionTracks.length)var h=N.getAudioTrack().W;if(N.Qm.EZ===2){if(g.yv(N.Qm))var O=o94(N);else if(N.storage)try{O=N.storage.get("module-enabled")}catch(D){N.storage.remove("module-enabled")}else O=null;if(O!=null)return!!O}O=H3r(N.player.getAudioTrack(),g.yv(N.Qm));var u=g.Fa(N.videoData,"yt:cc");if(Qg5(N)===void 0){if(O==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return u?u==="on":!0;if(O==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return u==="on"}else return u==="on";return h==="ON"||
g.Fa(N.videoData,"yt:cc")==="on"},Yt=function(N,h){if(N.W&&(h===void 0||!h)||!N.videoData.captionTracks.length)return!1;
N=N.getAudioTrack();return!!N.G||N.W==="FORCED_ON"},Qg5=function(N){var h=void 0,O=g.rJ().hI(65);
if(g.yv(N.Qm)&&O!=null){if(o94(N)!=null)return!1;h=!O}return h},xt=function(N,h){if(!N.G)return null;
if(N.D&&N.D.X)return N.D.X;h=zwm(N,h);h=g.Ue(N.G.W,h);var O=null;if(TuK(N.Qm)){var u=N.S.isInline()?void 0:g.en("yt-player-caption-sticky-language");for(var D=[u,N.videoData.captionsLanguagePreference,N.Qm.captionsLanguagePreference,g.Fa(N.videoData,"yt:cc_default_lang")],U=!1,d=0;d<D.length;d++){var b=D[d];if(b){U=!0;for(var B=0;B<h.length;B++)if(g.fK(h[B])===b)return h[B];for(B=0;B<h.length;B++)if(g.fK(h[B]).split("-")[0]===b.split("-")[0])return h[B]}}if(U&&N.G&&(D=N.G.L,D.length))for(D=g.I(D),
U=D.next();!U.done;U=D.next())if(U=U.value,U.languageCode===u){O=U;break}}else for(u=[N.videoData.captionsLanguagePreference,N.Qm.captionsLanguagePreference,g.Fa(N.videoData,"yt:cc_default_lang")],D=0;D<u.length;D++)for(U=0;U<h.length;U++)if(g.fK(h[U])===u[D])return h[U];u=null;N.D&&N.D.U&&(u=N.D.U);u||(u=h.find(function(C){return C.isDefault})||null);
u||(u=h[0]||l3(N));u&&O&&g.fK(u).split("-")[0]!==O.languageCode.split("-")[0]&&(u=WRS(u,O));return u},l3=function(N){return N.D&&N.D.G},nl=function(N){var h=l3(N);
return!!h&&N.W===h},v9Y=function(N,h){var O=N.S.wU().Iz().textTracks;
N=N.W.toString();for(var u=0;u<O.length;u++){var D=O[u];D.id===N&&(h?D.mode!=="showing"&&(D.mode="showing"):D.mode==="showing"&&(D.mode="disabled"))}},kt=function(N,h,O){N.loaded&&N.unload();
O!=null&&(N.Y=O,N.Y&&(g.yv(N.Qm)?FX(N,!!h):Z3(N,!!h)));h!==null||Yt(N,!0)||N.n7(h,!!h,N.Y?"m":"s");N.W=h;Yt(N)&&(N.W=l3(N));var u;w05(N,(u=N.W)!=null?u:void 0);N.load()},mbm=function(N,h){if(h instanceof Rw){var O=N.vB[h.id];
O&&O.W!==h&&(O.dispose(),delete N.vB[h.id],O=null);O||(O=KZR(N,h))&&(N.vB[h.id]=O)}else O=h.windowId,N.u0[O]||(N.u0[O]=[]),N.u0[O].push(h)},KZR=function(N,h){var O=IVR(N);
if(!O)return null;var u=N.W?g.fK(N.W):null;u&&g.nyR.test(u)&&(h.params.cg=1);var D=N.CC.getPlayerSize();u=D.height*N.fC.height;D=D.width*N.fC.width;N.Qm.playerStyle!=="google-live"||N.U.isDefault||Object.assign(h.params,N.U);switch(h.params.kd!=null?h.params.kd:h.G.length>1?1:0){case 1:return new sZ(h,N.U,N.V,O.width,O.height,D,u,N.Qm.experiments,N.gC.bind(N),N.S);case 2:return new Wh(h,N.U,N.V,O.width,O.height,D,u,N.Qm.experiments,N.gC.bind(N),N.S);default:return new Ll(h,N.U,N.V,O.width,O.height,
D,u,N.Qm.experiments,N.gC.bind(N),N.S)}},CNS=function(N,h,O){O=O===void 0?!1:O;
var u=N4.YF;N.U={};Object.assign(N.U,N4);N.U.YF={};Object.assign(N.U.YF,u);N.V={YF:{}};var D=h.backgroundOverride?N.V:N.U,U=h.background||u.background;ch.test(U);D.YF.background=U;D=h.colorOverride?N.V:N.U;U=h.color||u.color;ch.test(U);D.YF.color=U;D=h.windowColorOverride?N.V:N.U;U=h.windowColor||N4.windowColor;ch.test(U);D.windowColor=U;D=h.backgroundOpacityOverride?N.V:N.U;U=h.backgroundOpacity;U==null&&(U=u.backgroundOpacity);D.YF.backgroundOpacity=U;D=h.fontSizeIncrementOverride?N.V:N.U;U=h.fontSizeIncrement;
U==null&&(U=u.fontSizeIncrement);D.YF.fontSizeIncrement=U;U=h.fontStyleOverride?N.V:N.U;D=h.fontStyle;D==null&&(D=u.bold&&u.italic?3:u.bold?1:u.italic?2:0);U=U.YF;switch(D){case 1:U.bold=!0;delete U.italic;break;case 2:delete U.bold;U.italic=!0;break;case 3:U.bold=!0;U.italic=!0;break;default:delete U.bold,delete U.italic}D=h.textOpacityOverride?N.V:N.U;U=h.textOpacity;U==null&&(U=u.textOpacity);D.YF.textOpacity=U;D=h.windowOpacityOverride?N.V:N.U;U=h.windowOpacity;U==null&&(U=N4.windowOpacity);D.windowOpacity=
U;D=h.charEdgeStyleOverride?N.V:N.U;U=h.charEdgeStyle;U==null&&(U=u.charEdgeStyle);D.YF.charEdgeStyle=U;D=h.fontFamilyOverride?N.V:N.U;U=h.fontFamily;U==null&&(U=u.fontFamily);D.YF.fontFamily=U;N.loaded&&N.tp();O&&g.pE("yt-player-caption-display-settings",h,2592E3)},tUV=function(N,h){if(!N.G)return{};
if(h){g.ox(h)||N.zA(h.vss_id,"m");if(N.L||!g.UR(h))return;if(g.ox(h)){kt(N,null,!0);return}for(var O,u=g.Ue(N.G.W,!0),D=0;D<u.length;D++){var U=u[D];U.languageCode!==h.languageCode||O&&(U.languageName!==h.languageName||(U.captionId||"")!==(h.captionId||"")||g.Wj(U)!==h.displayName)||(O=h.translationLanguage?WRS(U,h.translationLanguage):U)}N.Xr(h.position);!O||O===N.W&&N.loaded||(h=g.IE(),u=g.fK(O),h.length&&u===h[h.length-1]||(h.push(u),g.pE("yt-player-caption-language-preferences",h)),TuK(N.Qm)&&
!N.S.isInline()&&g.pE("yt-player-caption-sticky-language",u,2592E3),kt(N,O,!0))}else return N.loaded&&N.W&&!nl(N)?g.XD(N.W):{};return""},yZV=function(N,h,O){h&&!N.eS?(h=r3o({cg:0,
lang:"en"}),N.eS=[h,new yZ(h.start,h.end-h.start,0,h.id,O!=null?O:"Captions look like this")],N.player.Vq(N.eS)):!h&&N.eS&&($bo(N,N.eS),N.eS=null)},$bo=function(N,h){N.player.wQ(h);
h=g.I(h);for(var O=h.next();!O.done;O=h.next())g.y4(N.FA,O.value);AG(N.m$)},w05=function(N,h){N.Qm.j("html5_modify_caption_vss_logging")&&(N.videoData.Wk=h)},IVR=function(N){var h=N.CC.getVideoContentRect(!0).height,O=N.CC.getVideoContentRect(!0).width;
if(!h||!O)return null;h*=N.fC.height;O*=N.fC.width;return{width:O,height:h}},Z3=function(N,h){if(N.storage)try{N.storage.set("module-enabled",h)}catch(O){}},FX=function(N,h){N.S.isInline()||g.pE("yt-player-sticky-caption",h,2592E3)},o94=function(N){if(!N.S.isInline())return g.en("yt-player-sticky-caption")},BCK=function(N){var h,O=!((h=N.S.wU())==null||!h.c5());
return N.pC&&O&&N.X!=="LIVE"&&N.X!=="SABR_LIVE"},zwm=function(N,h){g.Bc(N.videoData)&&(h=!0);
h||(h=N.X==="TTS"?!1:N.X==="INNERTUBE"?!1:!0);return h||N.Qm.j("web_deprecate_always_includes_asr_setting")&&g.yv(N.Qm)?!0:!!g.rJ().hI(66)};
g.PB.prototype.Pz=g.Dd(71,function(){return!1});
g.PB.prototype.n5=g.Dd(70,function(){});
g.MH.prototype.n5=g.Dd(69,function(N,h,O){var u=this;this.SS();h=this.B2(N,h);var D=this.Vm.K().j("html5_report_captions_ctmp_qoe"),U=(0,g.to)();this.W9();S$V(this,h,{format:"RAW",onSuccess:function(d){u.G=null;if(D){var b=(d.responseText.length/1024).toFixed(),B=(0,g.to)();u.videoData.GO("capresp",{ms:B-U,kb:b})}O.Fv(d.responseText,N)},
onError:D?function(d){var b;d=(b=d==null?void 0:d.status)!=null?b:0;u.videoData.GO("capfail",{status:d})}:void 0,
withCredentials:!0})});
g.ee.prototype.n5=g.Dd(68,function(N,h,O){var u=this;this.SS();h=this.B2(N,h);this.W9();this.G=g.tY(h,{format:"RAW",onSuccess:function(D){u.G=null;O.Fv(D.responseText,N)},
withCredentials:!0})});
g.nJ.prototype.Xl=g.Dd(67,function(){for(var N=g.bD(document,"track",void 0,this.G),h=0;h<N.length;h++)g.mq(N[h])});
g.HX.prototype.Xl=g.Dd(66,function(){this.mediaElement.Xl()});
g.nJ.prototype.ww=g.Dd(65,function(){return!(!this.G.textTracks||!this.G.textTracks.addEventListener)});
g.HX.prototype.ww=g.Dd(64,function(){return this.mediaElement.ww()});
g.nJ.prototype.c5=g.Dd(63,function(){return!!this.G.textTracks});
g.HX.prototype.c5=g.Dd(62,function(){return this.mediaElement.c5()});
g.nJ.prototype.Nb=g.Dd(61,function(N){for(var h=0;h<N.length;h++)this.G.appendChild(N[h])});
g.HX.prototype.Nb=g.Dd(60,function(N){this.mediaElement.Nb(N)});
g.id.prototype.GJ=g.Dd(59,function(N,h,O){this.FH.GJ(N,h,O)});
g.hC.prototype.GJ=g.Dd(58,function(N,h,O){this.W.set(N,{rp:h,Q_:O})});
g.OJ.prototype.GJ=g.Dd(57,function(N,h,O){this.fC.GJ(N,h,O)});
g.id.prototype.He=g.Dd(56,function(N){return this.FH.He(N)});
g.OJ.prototype.He=g.Dd(55,function(N){var h=2;this.L.has(N)?h=0:g.P1Y(this,N)&&(h=1);return h});
g.lw.prototype.CK=g.Dd(43,function(N){var h=this.app.LM({playerType:void 0});return h?h.CK(N):!1});
g.bb.prototype.CK=g.Dd(42,function(N){return this.ym.QG.CK(N)});
g.qe.prototype.CK=g.Dd(41,function(N){return this.Ay().some(function(h){return h.namespace===N})});
g.YJ.prototype.CK=g.Dd(40,function(){return!1});
g.lw.prototype.zA=g.Dd(38,function(N,h){this.app.Rr().zA(N,h)});
g.bb.prototype.zA=g.Dd(37,function(N,h){this.ym.zA(N,h)});
g.hw.prototype.zA=g.Dd(36,function(N,h){N=[N,h];g.Ne(this,g.ud(this.provider),"cfi",N)});
g.cV.prototype.zA=g.Dd(35,function(N,h){this.qoe&&this.qoe.zA(N,h)});
g.Us.prototype.zA=g.Dd(34,function(N,h){this.S6.zA(N,h)});
g.YJ.prototype.zA=g.Dd(33,function(){});
g.lw.prototype.n7=g.Dd(32,function(N,h,O){this.app.Rr().n7(N,h,O)});
g.bb.prototype.n7=g.Dd(31,function(N,h,O){this.ym.n7(N,h,O)});
g.hw.prototype.n7=g.Dd(30,function(N,h,O){if(this.m$!==N||this.Po!==h)h=h==="rawcc"?"":h,O=[N,h,this.m$,O],g.Ne(this,g.ud(this.provider),"cfs",O),this.m$=N,this.Po=h});
g.cV.prototype.n7=g.Dd(29,function(N,h,O){this.qoe&&this.qoe.n7(N,h,O)});
g.Us.prototype.n7=g.Dd(28,function(N,h,O){this.S6.n7(N,h,O)});
g.YJ.prototype.n7=g.Dd(27,function(){});
g.bd.prototype.EG=g.Dd(12,function(){return this.Y});
g.wG.prototype.EG=g.Dd(11,function(){return this.Rr().HZ()});
g.lw.prototype.HZ=g.Dd(10,function(){return this.app.EG()});
g.bb.prototype.HZ=g.Dd(9,function(){return this.ym.HZ()});
g.Us.prototype.HZ=g.Dd(8,function(){var N;return((N=this.loader)==null?void 0:N.EG())||null});
g.YJ.prototype.HZ=g.Dd(7,function(){return null});
g.hV.prototype.cO=g.Dd(1,function(N){return(N=this.MB(N))?N.G:0});
g.Eg.prototype.cO=g.Dd(0,function(){return 0});
var lQV=/#(.)(.)(.)/,Y$r=/^#(?:[0-9a-f]{3}){1,2}$/i,OM4={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};ow.prototype.contains=function(N){N=g.T5(this.segments,N);return N>=0||N<0&&(-N-1)%2===1};
ow.prototype.length=function(){return this.segments.length/2};
g.K(k_j,g.S);g.w=k_j.prototype;g.w.q5=function(){g.S.prototype.q5.call(this);this.W&&this.W.cancel()};
g.w.mS=function(){this.seekTo(this.player.getCurrentTime())};
g.w.seekTo=function(N){N-=this.player.Ho();var h=this.G;this.G=g.vo(this.eS.V1(N).JQ);h!==this.G&&this.D&&this.D()};
g.w.reset=function(){this.X=new ow;this.V=-1;this.W&&(this.W.cancel(),this.W=null)};
g.w.ws=function(){this.SS();var N;if(N=this.G!=null)N=this.G,N=N.G.nS(N);if(N&&!this.W&&!(this.G&&this.G.startTime-this.player.getCurrentTime()>30)){N=this.G;N=N.G.YP(N);var h=N.JQ[0],O;if((O=this.player.getVideoData())==null?0:O.enableServerStitchedDai)if(O=this.player.HZ()){var u=h.G.info.id,D=h.hQ,U=N.JQ[0].L;if(this.policy.FA){if(O=O.xj(U,D,u,3))N.X=O}else if(u=O.xH(U,D,u,3))if(O=O.He(D),O===0)u&&(N.G=new g.YA(u));else if(O===2){this.B.start();NhK(this)&&this.seekTo(this.player.getCurrentTime());
return}}h.G.index.d5(h.hQ)?(this.X.contains(N.JQ[0].hQ)||ho5(this,N),this.G=g.vo(N.JQ)):NhK(this)&&this.seekTo(this.player.getCurrentTime())}this.B.start()};
g.K(QZ,g.PB);g.w=QZ.prototype;g.w.n5=function(N,h,O){var u=this;this.W9();h=D1S(this,N.getId());h||(h=N.languageCode,h=this.G.isManifestless?U15(this,h,"386"):U15(this,h));if(h){var D=(h.index.cO(h.index.jA())-h.index.getStartTime(h.index.jA()))*1E3,U=new g.hPy(this.S.K());this.X=new k_j(U,this.S,h,function(d,b){O.Fv(d,N,b,D)},this.B||g.n4(h.info),function(){u.X&&u.X.reset();
u.V=!0})}};
g.w.Pz=function(){var N=this.V;this.V=!1;return N};
g.w.vx=function(N){var h=this.S.K().j("html5_fallback_if_rawcc_missing");var O=this.G.G.rawcc!=null;if(!this.B||!O&&h)h=this.G.isManifestless?uWn(this,"386"):uWn(this);else{if(!O){this.logger.G(386248249,"rawcc used but unavailable");return}h=[new g.Tu({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Tu({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}h=g.I(h);
for(O=h.next();!O.done;O=h.next())g.RK(this.W,O.value);N.AF()};
g.w.W9=function(){this.X&&(this.X.dispose(),this.X=null)};
g.w.B2=function(){return""};
var ch=/^#(?:[0-9a-f]{3}){1,2}$/i;var bMn=["left","right","center","justify"];g.K(Ll,g.f);g.w=Ll.prototype;g.w.Du=function(N,h){this.pC=N;this.PB=h;var O=g.hS(this.element,this.element.parentElement);this.xn=N-O.x;this.CC=h-O.y};
g.w.KP=function(N,h){if(N!==this.pC||h!==this.PB){g.OC(this.element,"ytp-dragging")||g.u9(this.element,"ytp-dragging");var O=g.ui(this.element);N=N-this.xn-.02*this.rU;var u=h-this.CC-.02*this.yd,D=(N+O.width/2)/this.maxWidth*3;D=Math.floor(g.S8(D,0,2));var U=(u+O.height/2)/this.maxHeight*3;U=Math.floor(g.S8(U,0,2));h=D+U*3;N=(N+D/2*O.width)/this.maxWidth;N=g.S8(N,0,1)*100;O=(u+U/2*O.height)/this.maxHeight;O=g.S8(O,0,1)*100;this.W.params.qf=h;this.W.params.fK=O;this.W.params.sZ=N;this.W.params.isDefault=
!1;this.G.qf=h;this.G.fK=O;this.G.sZ=N;this.G.isDefault=!1;this.fC.qf=h;this.fC.fK=O;this.fC.sZ=N;this.fC.isDefault=!1;this.eL()}};
g.w.EV=function(){g.UC(this.element,"ytp-dragging")};
g.w.eL=function(){this.ER(this.V)};
g.w.ER=function(N){var h=this.KC?0:Math.min(this.UM(),this.maxWidth),O=this.qh(),u=this.KC;if(u){var D=getComputedStyle(this.X.parentNode);D=zP(D.borderLeftWidth)+zP(D.borderRightWidth)+zP(D.paddingLeft)+zP(D.paddingRight)}else D=0;var U=D;D="";this.W.params.cg===3&&(D="rotate(180deg)");var d=u?"calc(96% - "+U+"px)":"96%";g.fF(this.element,{top:0,left:0,right:"",bottom:"",width:h?h+"px":"",height:O?O+"px":"","max-width":d,"max-height":d,margin:"",transform:""});this.ge(N);D={transform:D,top:"",left:"",
width:h?h+"px":"",height:O?O+"px":"","max-width":"","max-height":""};var b=this.G.sZ*.96+2;d=this.G.qf;switch(d){case 0:case 3:case 6:(u=this.G.YF.fontSizeIncrement)&&u>0&&this.G.cg!==2&&this.G.cg!==3&&(b=Math.max(b/(1+u*2),2));D.left=b+"%";break;case 1:case 4:case 7:D.left=b+"%";b=this.X.offsetWidth;h||b?(h=h||b+1,D.width=h+"px",D["margin-left"]=u?h/-2-U/2+"px":h/-2+"px"):D.transform+=" translateX(-50%)";break;case 2:case 5:case 8:D.right=100-b+"%"}u=this.G.fK*.96+2;switch(d){case 0:case 1:case 2:D.top=
u+"%";break;case 3:case 4:case 5:D.top=u+"%";(O=O||this.element.clientHeight)?(D.height=O+"px",D["margin-top"]=O/-2+"px"):D.transform+=" translateY(-50%)";break;case 6:case 7:case 8:D.bottom=100-u+"%"}g.fF(this.element,D);if(this.L){O=this.X.offsetHeight;u=1;for(h=0;h<N.length;h++)D=N[h],typeof D.text==="string"&&(u+=D.text.split("\n").length-1,D.append||h===0||u++);O/=u;this.L.style.height=O+"px";this.L.style.width=O+"px";this.element.style.paddingLeft=O+5+"px";this.element.style.paddingRight=O+
5+"px";N=Number(this.element.style.marginLeft.replace("px",""))-O-5;O=Number(this.element.style.marginRight.replace("px",""))-O-5;this.element.style.marginLeft=N+"px";this.element.style.marginRight=O+"px"}};
g.w.ge=function(N){var h;for(h=0;h<N.length&&N[h]===this.V[h];h++);if(this.b0||this.V.length>h)h=0,this.b0=!1,this.V=[],this.B=this.m$=this.FA=null,g.wX(this.X);for(;h<N.length;h++)o0j(this,N[h])};
g.w.UM=function(){return 0};
g.w.qh=function(){return 0};
g.w.toString=function(){return g.f.prototype.toString.call(this)};LPo.prototype.clear=function(){this.U=this.time=this.mode=0;this.G=[];this.reset()};
LPo.prototype.reset=function(){this.mode=0;this.X.reset(0);this.L.reset(1)};
var zox=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];vh.prototype.set=function(N){this.type=N};
vh.prototype.get=function(){return this.type};
w7.prototype.clear=function(){this.state=0};
w7.prototype.update=function(){this.state=this.state===2?1:0};
w7.prototype.R2=function(){return this.state!==0};
w7.prototype.matches=function(N,h){return this.R2()&&N===this.ZE&&h===this.YG};
Ipr.prototype.reset=function(){this.timestamp=this.G=0};
Kl.prototype.updateTime=function(N){for(var h=1;h<=15;++h)for(var O=1;O<=32;++O)this.U[h][O].timestamp=N};
Kl.prototype.debugString=function(){for(var N="\n",h=1;h<=15;++h){for(var O=1;O<=32;++O){var u=this.U[h][O];N=u.G===0?N+"_":N+String.fromCharCode(u.G)}N+="\n"}return N};
Kl.prototype.reset=function(N){for(var h=0;h<=15;h++)for(var O=0;O<=32;O++)this.U[h][O].reset();this.X=N;this.G=0;this.W=this.row=1};
var twm=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],$1r=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],y3n=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Vwm=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];pnS.prototype.reset=function(N,h){this.L=h;this.style.set(2);this.W=this.V;this.X=this.B;this.G=this.W;var O=(N<<2)+(h<<1);this.V.reset(O);this.B.reset(O);this.text.reset((N<<2)+(h<<1)+1)};
Qk5.prototype.reset=function(N){this.L=N;this.W.clear();this.X=this.U;this.U.reset(N,0);this.V.reset(N,1)};apS.prototype.X=function(){};g.K(yZ,g.Ym);yZ.prototype.toString=function(){return g.Ym.prototype.toString.call(this)};g.K(VZ,g.S);VZ.prototype.reset=function(){};g.K(Rw,g.Ym);Rw.prototype.toString=function(){return g.Ym.prototype.toString.call(this)};
var Ph=0;g.K(ME,VZ);ME.prototype.reset=function(){this.B={};this.W=this.G=null;this.V=!0};
ME.prototype.U=function(N,h){N=N.firstChild;N.getAttribute("format");h=h||0;Number.isFinite(h);N=Array.from(N.childNodes);N=g.I(N);for(var O=N.next();!O.done;O=N.next())if(O=O.value,O.nodeType===1)switch(O.tagName){case "head":var u=O;break;case "body":var D=O}if(u)for(u=Array.from(u.childNodes),u=g.I(u),N=u.next();!N.done;N=u.next())if(N=N.value,N.nodeType===1)switch(N.tagName){case "pen":O=N.getAttribute("id");var U=this.pens,d={},b=N.getAttribute("p");b&&Object.assign(d,this.pens[b]);b=ea(N,"b");
b!=null&&(d.bold=b);b=ea(N,"i");b!=null&&(d.italic=b);b=ea(N,"u");b!=null&&(d.underline=b);b=EZ(N,"et");b!=null&&(d.charEdgeStyle=b);b=EZ(N,"of");b!=null&&(d.offset=b);b=aw(N,"bc");b!=null&&(d.background=b);b=aw(N,"ec");b!=null&&(d.Q9=b);b=aw(N,"fc");b!=null&&(d.color=b);b=EZ(N,"fs");b!=null&&b!==0&&(d.fontFamily=b);b=pl(N,"sz");b!==void 0&&(d.fontSizeIncrement=b/100-1);b=pl(N,"bo");b!==void 0&&(d.backgroundOpacity=b/255);b=pl(N,"fo");b!==void 0&&(d.textOpacity=b/255);b=EZ(N,"rb");b!=null&&b!==10&&
b!==0&&(d.Ih=b>10?b-1:b);N=EZ(N,"hg");N!=null&&(d.Qw=N);U[O]=d;break;case "ws":O=N.getAttribute("id");this.D[O]=skR(this,N);break;case "wp":O=N.getAttribute("id"),this.Y[O]=J3j(this,N)}if(D){u=[];D=Array.from(D.childNodes);D=g.I(D);for(N=D.next();!N.done;N=D.next())if(N=N.value,N.nodeType===1)switch(N.tagName){case "w":this.G=jkV(this,N,h,!1);(N=this.B[this.G.id])&&N.end>this.G.start&&(N.end=this.G.start);this.B[this.G.id]=this.G;u.push(this.G);break;case "p":var B=N;b=h;O=[];U=B.getAttribute("w")||
this.L;d=!!ea(B,"a");b=(pl(B,"t")||0)+b;var C=pl(B,"d")||5E3;d||(!this.V&&this.W&&this.W.windowId===U&&this.W.end>b&&(this.W.end=b),this.W&&this.W.text==="\n"&&(this.W.text=""));var A=d?6:5,Q=B.getAttribute("p");Q=Q?this.pens[Q]:null;var L=Array.from(B.childNodes);L.length&&(this.V=B.getAttribute("d")!=null);for(B=0;B<L.length;B++){var z=L[B],v=void 0;B>0&&(d=!0);var t=void 0;z.nodeType===1&&(t=z);if(t&&t.tagName==="s"){if((z=(z=t.getAttribute("p"))?this.pens[z]:null)&&z.Ih&&(z.Ih===1?(z=L.slice(B,
B+4),z.length===4&&(v=g0V(b,C,U,d,A,z,this.pens),B+=3)):v=g0V(b,C,U,d,A,[t],this.pens)),!v){var R=t;v=b;t=C;z=U;var p=d,M=A,a=R.textContent?R.textContent:"",J=R.getAttribute("p");J=J?this.pens[J]:null;R=pl(R,"t")||0;v=new yZ(v+R,t-R,M,z,a,p,J)}}else v=new yZ(b,C,A,U,z.textContent||"",d,Q);O.push(v);this.W=v}if(O.length>0)for(O[0].windowId===this.L&&(this.G=jkV(this,N,h,!0),u.push(this.G)),N=g.I(O),O=N.next();!O.done;O=N.next())O=O.value,O.windowId=this.G.id,this.G.G.push(O),u.push(O)}h=u}else h=[];
return h};var VUY=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.K(qE,VZ);qE.prototype.reset=function(){this.W.clear()};
qE.prototype.U=function(N,h){var O=JSON.parse(N);if(!O)return[];if(O.pens){N=0;for(var u=g.I(O.pens),D=u.next();!D.done;D=u.next()){D=D.value;var U={},d=D.pParentId;d&&Object.assign(U,this.G.get(d));D.bAttr&&(U.bold=!0);D.iAttr&&(U.italic=!0);D.uAttr&&(U.underline=!0);d=D.ofOffset;d!=null&&(U.offset=d);D.szPenSize!==void 0&&(U.fontSizeIncrement=D.szPenSize/100-1);d=D.etEdgeType;d!=null&&(U.charEdgeStyle=d);D.ecEdgeColor!==void 0&&(U.Q9=g7(D.ecEdgeColor));d=D.fsFontStyle;d!=null&&d!==0&&(U.fontFamily=
d);D.fcForeColor!==void 0&&(U.color=g7(D.fcForeColor));D.foForeAlpha!==void 0&&(U.textOpacity=D.foForeAlpha/255);D.bcBackColor!==void 0&&(U.background=g7(D.bcBackColor));D.boBackAlpha!==void 0&&(U.backgroundOpacity=D.boBackAlpha/255);(d=D.rbRuby)&&d!==10&&(U.Ih=d>10?d-1:d,U.textEmphasis=VUY.get(U.Ih));D.hgHorizGroup&&(U.Qw=D.hgHorizGroup);this.G.set(N++,U)}}if(O.wsWinStyles)for(N=0,u=g.I(O.wsWinStyles),D=u.next();!D.done;D=u.next())D=D.value,U={},(d=D.wsParentId)?Object.assign(U,this.L.get(d)):Object.assign(U,
this.V),D.mhModeHint!==void 0&&(U.kd=D.mhModeHint),D.juJustifCode!==void 0&&(U.textAlign=D.juJustifCode),D.pdPrintDir!==void 0&&(U.cg=D.pdPrintDir),D.sdScrollDir!==void 0&&(U.o0=D.sdScrollDir),D.wfcWinFillColor!==void 0&&(U.windowColor=g7(D.wfcWinFillColor)),D.wfoWinFillAlpha!==void 0&&(U.windowOpacity=D.wfoWinFillAlpha/255),this.L.set(N++,U);if(O.wpWinPositions)for(N=0,u=g.I(O.wpWinPositions),D=u.next();!D.done;D=u.next())D=D.value,U={},(d=D.wpParentId)&&Object.assign(U,this.X.get(d)),D.ahHorPos!==
void 0&&(U.sZ=D.ahHorPos),D.apPoint!==void 0&&(U.qf=D.apPoint),D.avVerPos!==void 0&&(U.fK=D.avVerPos),D.ccCols!==void 0&&(U.aH=D.ccCols),D.rcRows!==void 0&&(U.Mu=D.rcRows),this.X.set(N++,U);if(O.events){N=[];O=g.I(O.events);for(u=O.next();!u.done;u=O.next()){var b=u.value;D=(b.tStartMs||0)+h;U=b.dDurationMs||0;if(b.id)d=String(b.id),u=S1m(this,b,D,U,d),N.push(u),this.W.set(d,u);else{b.wWinId?d=b.wWinId.toString():(d="_"+Ph++,u=S1m(this,b,D,U,d),N.push(u),this.W.set(d,u));u=N;var B=b;U===0&&(U=5E3);
b=this.W.get(d);var C=!!B.aAppend,A=C?6:5,Q=B.segs,L=null;B.pPenId&&(L=this.G.get(B.pPenId));for(B=0;B<Q.length;B++){var z=Q[B],v=z.utf8;if(v){var t=z.tOffsetMs||0,R=null;z.pPenId&&(R=this.G.get(z.pPenId));if((b.params.kd!=null?b.params.kd:b.G.length>1?1:0)===2&&C&&v==="\n")continue;z=null;var p=[],M;if(M=R&&R.Ih===1){M=Q;var a=B;if(a+3>=M.length||!M[a+1].pPenId||!M[a+2].pPenId||!M[a+3].pPenId)M=!1;else{var J=M[a+1].pPenId;(J=this.G.get(J))&&J.Ih&&J.Ih===2?(J=M[a+2].pPenId,J=this.G.get(J),!J||!J.Ih||
J.Ih<3?M=!1:(J=M[a+3].pPenId,M=(J=this.G.get(J))&&J.Ih&&J.Ih===2?!0:!1)):M=!1}}if(M)t=Q[B+1].utf8,z=Q[B+3].utf8,M=Q[B+2].utf8,a=this.G.get(Q[B+2].pPenId),v=q1x(v,t,M,z,a),z=new yZ(D,U,A,d,v,C,R),B+=3;else{if(v.indexOf("<")>-1){var W=void 0;p=R;M=L;a=D;J=U;var F=t,l=A,iY=C,bY=[],BR=g.Zi("<html>"+v+"</html>");if(!BR.getElementsByTagName("parsererror").length&&((W=BR.firstChild)==null?0:W.childNodes.length))for(W=g.I(BR.firstChild.childNodes),BR=W.next();!BR.done;BR=W.next()){BR=BR.value;var oe=void 0,
Oa=void 0,Ea=(Oa=(oe=BR.textContent)==null?void 0:oe.replace(/\n/g,""))!=null?Oa:"";if(BR.nodeType!==3||Ea&&Ea.match(/^ *$/)==null){oe={};Object.assign(oe,p||M);Oa=void 0;switch((Oa=BR)==null?void 0:Oa.tagName){case "b":oe.bold=!0;break;case "i":oe.italic=!0;break;case "u":oe.underline=!0}bY.push(new yZ(a+F,J-F,l,b.id,Ea,iY,oe))}}p=bY}p.length||(p=[new yZ(D+t,U-t,A,b.id,v,C,R||L)])}if(p.length)for(C=g.I(p),R=C.next();!R.done;R=C.next())R=R.value,u.push(R),b.G.push(R);else z&&(u.push(z),b.G.push(z))}C=
!0}}}h=N}else h=[];return h};g.K(r7,g.PB);r7.prototype.n5=function(N,h,O){fQV(this.videoData.videoId,N.vssId,O.Fv)};
r7.prototype.vx=function(N){if(this.audioTrack)for(var h=g.I(this.audioTrack.captionTracks),O=h.next();!O.done;O=h.next())g.RK(this.W,O.value);N.AF()};g.K(sZ,Ll);sZ.prototype.ge=function(N){var h=this.W.G;Ll.prototype.ge.call(this,N);for(N=N.length;N<h.length;N++){var O=h[N];if(U&&O.G===D)var u=U;else{u={};Object.assign(u,O.G);Object.assign(u,Rw5);var D=O.G;var U=u}o0j(this,O,u)}};
var Rw5={Hp:!0};g.K(JG,apS);JG.prototype.X=function(N,h,O,u,D){if(O<u){var U="_"+Ph++;O=O/1E3-this.V;u=u/1E3-this.V;N=new Rw(O,u-O,5,U,{textAlign:0,qf:0,sZ:h*2.5,fK:N*5.33});D=new yZ(O,u-O,5,U,D);this.W.push(N);this.W.push(D)}};
g.K(TP,VZ);TP.prototype.U=function(N){N=new JG(N,N.byteLength,this.W);if(HMS(N)){for(;N.byteOffset<N.G.byteLength;)for(N.version===0?N.U=Hh(N)*(1E3/45):N.version===1&&(N.U=Hh(N)*4294967296+Hh(N)),N.L=Sa(N);N.L>0;N.L--){var h=Sa(N),O=Sa(N),u=Sa(N);h&4&&(h&3)===this.track&&(this.track===0||this.track===1)&&(h=this.G,h.G.push({time:N.U,type:this.track,ph:O,wF:u,order:h.G.length}))}m1x(this.G,N);return N.W}return[]};
TP.prototype.reset=function(){this.G.clear()};g.K(Wh,Ll);g.w=Wh.prototype;g.w.eL=function(){g.xL(this.GZ)};
g.w.Wz=function(){this.element.removeEventListener("transitionend",this.Wz,!1);g.UC(this.element,"ytp-rollup-mode");this.ER(this.j6,!0)};
g.w.qh=function(){return this.U?this.eS:this.D};
g.w.UM=function(){return this.U?this.D:this.eS};
g.w.ER=function(N,h){this.j6=N;if(this.W.params.Mu){for(var O=0,u=0;u<this.V.length&&O<N.length;u++)this.V[u]===N[O]&&O++;O>0&&O<N.length&&(N=this.V.concat(N.slice(O)));this.e6=this.eS;this.D=this.eS=0;Ll.prototype.ER.call(this,N);fpj(this,h)}Ll.prototype.ER.call(this,N)};Y1x.prototype.unload=function(){this.G!=null&&(this.S.removeEventListener("sabrCaptionsDataLoaded",this.G),this.G=null);this.eB=[];this.S.publish("sabrCaptionsBufferedRangesUpdated",this.eB)};
Y1x.prototype.A2=function(N){return{formatId:g.Z4(N.info.G.info,this.m9),hQ:N.info.hQ+(this.m9?0:1),startTimeMs:N.info.L*1E3,durationMs:N.info.Y*1E3}};g.K(XX,g.PB);XX.prototype.n5=function(N,h,O){this.W9();h=N.getId();h=h!=null&&h in this.G.G?this.G.G[h]:null;h||(h=N.languageCode,h=this.G.isManifestless?ZM4(this,h,"386"):ZM4(this,h));h&&(this.X=N,this.V=h,n0S(this.B,O),this.S.publish("sabrCaptionsTrackChanged",g.Z4(h.info,this.G.m9)))};
XX.prototype.vx=function(N){var h=this.G.isManifestless?FPo(this,"386"):FPo(this);h=g.I(h);for(var O=h.next();!O.done;O=h.next())g.RK(this.W,O.value);N.AF()};
XX.prototype.W9=function(){this.X&&(this.X=this.V=null,this.B.unload(),this.S.publish("sabrCaptionsTrackChanged",null))};
XX.prototype.B2=function(){return""};var hwR="WEBVTT".split("").map(function(N){return N.charCodeAt(0)});
g.K(NCS,VZ);
NCS.prototype.U=function(N,h){N instanceof ArrayBuffer&&(N=g.L$(new Uint8Array(N)));var O=[];N=N.split(PNx);for(var u=1;u<N.length;u++){var D=N[u],U=h;if(D!==""&&!MU5.test(D)){var d=p05.exec(D);if(d&&d.length>=4){var b=Db4(d[1]),B=Db4(d[2])-b;b+=U;var C=(d=d[3])?d.split(" "):[];d={};var A=null;var Q="";var L=null,z="";C=g.I(C);for(var v=C.next();!v.done;v=C.next())if(v=v.value.split(":"),v.length===2){var t=v[1];switch(v[0]){case "line":v=t.split(",");v[0].endsWith("%")&&(A=v[0],d.fK=Number.parseInt(A,
10),v.length===2&&(Q=v[1].trim()));break;case "position":v=t.split(",");L=v[0];d.sZ=Number.parseInt(L,10);v.length===2&&(z=v[1].trim());break;case "align":switch(t){case "start":d.textAlign=0;break;case "middle":d.textAlign=2;break;case "end":d.textAlign=1}}}A||Q||(Q="end");if(!L)switch(d.textAlign){case 0:d.sZ=0;break;case 1:d.sZ=100;break;case 2:d.sZ=50}if(d.textAlign!=null){A=0;switch(Q){case "center":A+=3;break;case "end":A+=6;break;default:A+=0}switch(z){case "line-left":A+=0;break;case "center":A+=
1;break;case "line-right":A+=2;break;default:switch(d.textAlign){case 0:A+=0;break;case 2:A+=1;break;case 1:A+=2}}Q=A<0||A>8?7:A;d.qf=Q}D=D.substring(p05.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");z=d;d=D;D={};if(d.indexOf("<")<0&&d.indexOf("&")<0)U=UbY(b,B,5,z),B=new yZ(b,B,5,U.id,d,!1,g.ox(D)?void 0:D),O.push(U),O.push(B),U.G.push(B);else for(Q=d.split(ewS),Q.length===1?(d=5,z=UbY(b,B,d,z)):(A=d=6,z=Object.assign({aH:32},z),z=new Rw(b,B,A,"_"+Ph++,z)),O.push(z),A=b,L=0;L<Q.length;L++)C=Q[L],
L%2===0?(v=g.Zi("<html>"+C+"</html>"),v.getElementsByTagName("parsererror").length?(t=v.createElement("span"),t.appendChild(v.createTextNode(C))):t=v.firstChild,uYS(this,A,B-(A-b),d,z,L>0,t,D,O)):A=Db4(C)+U}p05.lastIndex=0}}return O};
var MU5=/^NOTE/,PNx=/(?:\r\n|\r|\n){2,}/,p05=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ewS=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.K(fl,g.S);fl.prototype.clear=function(){this.G&&this.G.dispose();this.G=null};
fl.prototype.reset=function(){this.G&&this.G.reset()};
fl.prototype.q5=function(){g.S.prototype.q5.call(this);this.clear()};var N4={windowColor:"#080808",windowOpacity:0,textAlign:2,qf:7,sZ:50,fK:100,isDefault:!0,YF:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.K(AZo,g.Vq);g.w=AZo.prototype;g.w.q5=function(){if(this.L||this.TO){var N=this.S.wU();N&&!N.SS()&&N.Xl()}else yZV(this,!1);g.Vq.prototype.q5.call(this)};
g.w.AP=function(){return this.Qm.j("html5_honor_caption_availabilities_in_audio_track")&&this.X!=="LIVE"&&this.X!=="SABR_LIVE"};
g.w.xz=function(){if(this.pC)return this.L||this.TO;var N=this.getAudioTrack();if(this.AP()){if(!N.captionTracks.length)return!1;if(!this.G)return!0}N=H3r(N,g.yv(this.Qm));return N==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:N==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?Yt(this):Qg5(this)||Yt(this)?!0:LZ5(this)};
g.w.load=function(){g.Vq.prototype.load.call(this);this.D=this.getAudioTrack();if(this.G)this.W&&(this.PB.clear(),this.L?v9Y(this,!0):this.player.getPresentingPlayerType()!==3&&this.G.n5(this.W,"json3",this.GZ),this.L||this.TO||nl(this)||this.player.yq("captionschanged",g.XD(this.W)));else{var N;this.X==="OFFLINE"?N=new r7(this.player,this.videoData,this.getAudioTrack()):this.X==="SABR_LIVE"?N=new XX(this.videoData.G,this.player):this.X==="LIVE"?N=new QZ(this.videoData.G,this.player):this.X==="INNERTUBE"?
N=new g.MH(this.player,this.videoData,this.getAudioTrack()):N=new g.ee(this.player,this.videoData.HX,this.videoData.videoId,g.US7(this.videoData),this.videoData.QJ,this.videoData.eventId);this.G=N;g.H(this,this.G);this.G.vx(this.GZ)}};
g.w.unload=function(){this.L&&this.W?v9Y(this,!1):(this.O3&&g.nz(this.O3),this.player.SV("captions"),this.FA=[],this.G&&this.G.W9(),this.PB.clear(),this.eS&&this.player.Vq(this.eS),this.tp());g.Vq.prototype.unload.call(this);this.player.P$();this.player.yq("captionschanged",{})};
g.w.create=function(){this.xz()&&this.load();var N;a:{var h,O,u;if(this.Qm.j("web_player_nitrate_promo_tooltip")&&((h=this.videoData.getPlayerResponse())==null?0:(O=h.captions)==null?0:(u=O.playerCaptionsTracklistRenderer)==null?0:u.enableTouchCaptionsNitrate)){var D,U;if(h=(N=this.videoData.getPlayerResponse())==null?void 0:(D=N.captions)==null?void 0:(U=D.playerCaptionsTracklistRenderer)==null?void 0:U.captionTracks)for(N=g.I(h),D=N.next();!D.done;D=N.next())if(D=D.value,D.kind==="asr"&&D.languageCode===
"en"){N=!0;break a}}N=!1}N&&this.S.publish("showpromotooltip",this.B.element)};
g.w.AF=function(){var N=H3r(this.player.getAudioTrack(),g.yv(this.Qm));var h=N==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?xt(this,this.Y):N==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&Yt(this)?l3(this):Qg5(this)||this.Y||LZ5(this)?xt(this,this.Y):Yt(this)?l3(this):null;if(this.L||this.TO){var O=g.Ue(this.G.W,!0);N=[];for(var u=0;u<O.length;u++){var D=O[u],U=g.LF("TRACK");U.setAttribute("kind","subtitles");U.setAttribute("label",g.Wj(D));U.setAttribute("srclang",g.fK(D));U.setAttribute("id",D.toString());
this.TO||U.setAttribute("src",this.G.B2(D,"vtt"));D===h&&U.setAttribute("default","1");N.push(U)}h=this.S.wU();h.Nb(N);N=h.Iz();this.KC&&this.b0.J(N.textTracks,"change",this.cIm)}else!this.W&&h&&kt(this,h),this.player.yq("onCaptionsTrackListChanged"),this.player.OW("onApiChange")};
g.w.cIm=function(){for(var N=this.S.wU().Iz().textTracks,h=null,O=0;O<N.length;O++)if(N[O].mode==="showing")a:{h=g.Ue(this.G.W,!0);for(var u=0;u<h.length;u++)if(h[u].toString()===N[O].id){h=h[u];break a}h=null}(this.loaded?this.W:null)!==h&&kt(this,h,!0)};
g.w.b75=function(){!this.W&&this.L||this.unload()};
g.w.Fv=function(N,h,O,u){if(N){var D;w05(this,(D=this.W)!=null?D:void 0);this.G.Pz()&&(this.FA=[],this.S.SV("captions"),AG(this.m$),this.PB.reset());a:{D=this.PB;u=u||0;O=GD5(D,N,O||0);N=[];try{for(var U=g.I(O),d=U.next();!d.done;d=U.next()){var b=d.value,B=b.trackData,C=b.Ez,A=D.Qm.j("safari_live_drm_captions_fix");if(typeof B!=="string"){O=N;var Q=O.concat;if(A&&Oe5(B))var L=ben(D,B,C);else{var z=D,v=h,t=B,R=C,p=u;if(!Thj(t))throw Error("Invalid binary caption track data");z.G||(z.G=new TP(p,v));
L=z.G.U(t,R)}var M=Q.call(O,L)}else{if(B.substring(0,6)==="WEBVTT")var a=N.concat(ben(D,B,C));else{O=N;var J=O.concat;b:{v=z=void 0;t=D;R=h;if(B[0]==="{")try{t.G||(t.G=new qE(ie5(R)));var W=v=t.G.U(B,C);break b}catch(Oa){g.Ms(Oa);W=[];break b}var F=g.Zi(B);if(!F||!F.firstChild){var l=Error("Invalid caption track data");l.params=B;throw l;}if(F.firstChild.tagName==="timedtext"){if(Number(F.firstChild.getAttribute("format"))===3){t.G||(t.G=new ME(ie5(R),t.Qm));W=z=t.G.U(F,C);break b}var iY=Error("Unsupported subtitles format in web player (Format2)");
iY.params=B;throw iY;}if(F.firstChild.tagName==="transcript"){var bY=Error("Unsupported subtitles format in web player (Format1)");bY.params=B;throw bY;}var BR=Error("Invalid caption track data");BR.params=B;throw BR;}a=J.call(O,W)}M=a}N=M}var oe=N;break a}catch(Oa){D.logger.G(187101178,"Captions parsing failed: "+Oa.message+". ");D.clear();oe=[];break a}oe=void 0}h=oe;h.length>0&&(oe=this.W,this.n7(oe,!!oe,nl(this)?"g":this.Y?"m":"s"));this.player.Vq(h,void 0,this.X==="LIVE"||this.X==="SABR_LIVE");
!this.Y||this.TO||nl(this)||g.v1(this.Qm)||g.Bj(this.Qm)||g.qG(this.Qm)||this.Qm.b0==="shortspage"||this.player.isInline()||(g.nz(this.O3),h=r3o({qf:0,sZ:5,fK:5,Mu:2,textAlign:0,cg:0,lang:"en"}),this.HB=[h],oe=["Click "," for settings"],this.xn||(U=new g.Ux(g.RR()),g.H(this,U),this.xn=U.element),U=h.end-h.start,(d=g.Wj(this.W))&&this.HB.push(new yZ(h.start,U,0,h.id,d)),this.HB.push(new yZ(h.start,U,0,h.id,oe[0]),new yZ(h.start,U,0,h.id,this.xn,!0),new yZ(h.start,U,0,h.id,oe[1],!0)),this.player.Vq(this.HB),
g.la(this.O3));!this.Y||this.TO||nl(this)||(g.yv(this.Qm)?FX(this,!0):Z3(this,!0),this.D&&(this.D.X=this.W),this.player.P$());this.Y=!1}};
g.w.onCueRangeEnter=function(N){this.FA.push(N);AG(this.m$)};
g.w.onCueRangeExit=function(N){g.y4(this.FA,N);this.G instanceof QZ&&this.G.B&&this.player.wQ([N]);AG(this.m$)};
g.w.getCaptionWindowContainerId=function(){return this.B.element.id};
g.w.cwB=function(){$bo(this,this.HB);this.HB=null};
g.w.B7=function(){var N=this;if(!this.e6||!this.L){this.m$.stop();g.gpa(this.u0);this.FA.sort(g.l8);var h=this.FA;if(this.eS){var O=g.pe(h,function(U){return this.eS.indexOf(U)===-1},this);
O.length&&(h=O)}h=g.I(h);for(O=h.next();!O.done;O=h.next())mbm(this,O.value);h=g.I(Object.entries(this.vB));var u=h.next();for(O={};!u.done;O={Xj:void 0,tb:void 0},u=h.next()){var D=g.I(u.value);u=D.next().value;D=D.next().value;O.Xj=u;O.tb=D;this.u0[O.Xj]?(O.tb.element.parentNode||(O.tb instanceof Wh||O.tb instanceof sZ||g.ON(this.vB,function(U){return function(d,b){b!==U.Xj&&d.W.params.qf===U.tb.W.params.qf&&d.W.params.sZ===U.tb.W.params.sZ&&d.W.params.fK===U.tb.W.params.fK&&(d.dispose(),delete N.vB[b]);
return b===U.Xj}}(O),this),this.B.element.appendChild(O.tb.element)),O.tb.ER(this.u0[O.Xj])):(O.tb.dispose(),delete this.vB[O.Xj])}}};
g.w.zyF=function(){CNS(this,{},!0);this.player.yq("captionssettingschanged")};
g.w.BU=function(){var N=N4.YF;N={background:N.background,backgroundOpacity:N.backgroundOpacity,charEdgeStyle:N.charEdgeStyle,color:N.color,fontFamily:N.fontFamily,fontSizeIncrement:N.fontSizeIncrement,fontStyle:N.bold&&N.italic?3:N.bold?1:N.italic?2:0,textOpacity:N.textOpacity,windowColor:N4.windowColor,windowOpacity:N4.windowOpacity};var h=FR5()||{};h.background!=null&&(N.background=h.background);h.backgroundOverride!=null&&(N.backgroundOverride=h.backgroundOverride);h.backgroundOpacity!=null&&(N.backgroundOpacity=
h.backgroundOpacity);h.backgroundOpacityOverride!=null&&(N.backgroundOpacityOverride=h.backgroundOpacityOverride);h.charEdgeStyle!=null&&(N.charEdgeStyle=h.charEdgeStyle);h.charEdgeStyleOverride!=null&&(N.charEdgeStyleOverride=h.charEdgeStyleOverride);h.color!=null&&(N.color=h.color);h.colorOverride!=null&&(N.colorOverride=h.colorOverride);h.fontFamily!=null&&(N.fontFamily=h.fontFamily);h.fontFamilyOverride!=null&&(N.fontFamilyOverride=h.fontFamilyOverride);h.fontSizeIncrement!=null&&(N.fontSizeIncrement=
h.fontSizeIncrement);h.fontSizeIncrementOverride!=null&&(N.fontSizeIncrementOverride=h.fontSizeIncrementOverride);h.fontStyle!=null&&(N.fontStyle=h.fontStyle);h.fontStyleOverride!=null&&(N.fontStyleOverride=h.fontStyleOverride);h.textOpacity!=null&&(N.textOpacity=h.textOpacity);h.textOpacityOverride!=null&&(N.textOpacityOverride=h.textOpacityOverride);h.windowColor!=null&&(N.windowColor=h.windowColor);h.windowColorOverride!=null&&(N.windowColorOverride=h.windowColorOverride);h.windowOpacity!=null&&
(N.windowOpacity=h.windowOpacity);h.windowOpacityOverride!=null&&(N.windowOpacityOverride=h.windowOpacityOverride);return N};
g.w.uh=function(N,h){var O={};Object.assign(O,FR5());Object.assign(O,N);CNS(this,O,h);this.player.yq("captionssettingschanged")};
g.w.tp=function(){!this.L&&this.loaded&&(g.kY(this.vB,function(N,h){N.dispose();delete this.vB[h]},this),this.B7())};
g.w.kx=function(N,h){switch(N){case "fontSize":if(isNaN(h))break;N=g.S8(h,-2,4);this.uh({fontSizeIncrement:N});return N;case "reload":h&&!this.L&&kt(this,this.W,!0);break;case "stickyLoading":h!==void 0&&this.Qm.Y&&(g.yv(this.Qm)?FX(this,!!h):Z3(this,!!h));break;case "track":return tUV(this,h);case "tracklist":return this.G?g.KR(g.Ue(this.G.W,!(!h||!h.includeAsr)),function(O){return g.XD(O)}):[];
case "translationLanguages":return this.G?this.G.L.map(function(O){return Object.assign({},O)}):[];
case "sampleSubtitles":this.L||h===void 0||yZV(this,!!h);break;case "sampleSubtitlesCustomized":this.L||yZV(this,!!h,h);break;case "recommendedTranslationLanguages":return g.IE();case "defaultTranslationSourceTrackIndices":return this.G?this.G.Y:[]}};
g.w.getOptions=function(){var N="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Qm.Y&&N.push("stickyLoading");return N};
g.w.OS=function(){var N=this.W;if(this.S.CK("captions")){if(this.Qm.j("html5_modify_caption_vss_logging")){var h;return(N=(h=this.videoData.Wk)!=null?h:null)?{cc:g.Vrr(N)}:{}}if(N)return h=N.vssId,N.translationLanguage&&h&&(h="t"+h+"."+g.fK(N)),{cc:h}}return{}};
g.w.YB5=function(){this.isSubtitlesOn()?(g.yv(this.Qm)?FX(this,!1):Z3(this,!1),w05(this),kt(this,null,!0)):this.v7()};
g.w.v7=function(){var N=nl(this)||!this.W?xt(this,!0):this.W;N&&this.zA(N.vssId,"m");this.isSubtitlesOn()||kt(this,nl(this)||!this.W?xt(this,!0):this.W,!0)};
g.w.isSubtitlesOn=function(){return!!this.loaded&&!!this.W&&!nl(this)};
g.w.aTn=function(){var N=nl(this);Yt(this,N)?kt(this,this.getAudioTrack().G,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.AP()&&(this.Y=!1,this.W=null,this.G&&(this.G.dispose(),this.G=null)),this.xz()&&(N?kt(this,xt(this,!1),!1):this.load()))};
g.w.Xr=function(N){N&&(this.fC={top:N.top,right:N.right,bottom:N.bottom,left:N.left,width:1-N.left-N.right,height:1-N.top-N.bottom},this.B.element.style.top=this.fC.top*100+"%",this.B.element.style.left=this.fC.left*100+"%",this.B.element.style.width=this.fC.width*100+"%",this.B.element.style.height=this.fC.height*100+"%",this.B.element.style.position="absolute",N=IVR(this))&&(this.B.element.style.width=N.width+"px",this.B.element.style.height=N.height+"px")};
g.w.onVideoDataChange=function(N,h){N==="newdata"&&(this.videoData=h,this.loaded&&this.unload(),this.Y=!1,this.W=null,this.G&&(this.G.dispose(),this.G=null,this.player.yq("captionschanged",{})),this.xz()&&this.load())};
g.w.getAudioTrack=function(){return this.player.getAudioTrack()};
g.w.n6A=function(){var N=this.S.wU();N&&!N.SS()&&N.Xl();this.S.isFullscreen()?(this.L=this.pC=!0,this.loaded&&this.AF()):(this.pC=this.Qm.controlsType==="3",this.L=BCK(this));kt(this,this.W)};
g.w.gC=function(){var N,h,O,u=(N=this.videoData.getPlayerResponse())==null?void 0:(h=N.captions)==null?void 0:(O=h.playerCaptionsTracklistRenderer)==null?void 0:O.openTranscriptCommand;u&&this.player.wf("innertubeCommand",u)};
g.w.n7=function(N,h,O){var u=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,D="";N&&(D=N.vssId,D=D.replace(u,""));var U="";N&&N.getId()&&(U=N.getId()||"");N&&N.getXtags()&&(N=N.getXtags(),N=N.replace(u,""),U=U.concat(";"+N));this.S.n7(h?D:"",h?U:"",O)};
g.w.zA=function(N,h){N=(N||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");N.length>0&&this.S.zA(N,h)};g.yq("captions",AZo);})(_yt_player);
