(function(g){var window=this;'use strict';var ObK=function(N){N.publish("autonavvisibility")},u6Y=function(N,h){N.wf("onAutonavCoundownStarted",h)},D2o=function(N){var h,O,u;
return N==null?void 0:(h=N.playerOverlays)==null?void 0:(O=h.playerOverlayRenderer)==null?void 0:(u=O.autoplay)==null?void 0:u.playerOverlayAutoplayRenderer},bj=function(N){var h=N.K(),O=h.X;
g.f.call(this,{T:"a",N:"ytp-autonav-suggestion-card",Z:{href:"{{url}}",target:O?h.D:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},C:[{T:"div",M5:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Z:{style:"{{background}}"},C:[{T:"div",Z:{"aria-label":"{{timestamp}}"},M5:["ytp-autonav-timestamp"],WB:"{{duration}}"},{T:"div",M5:["ytp-autonav-live-stamp"],WB:"Live"},{T:"div",
M5:["ytp-autonav-upcoming-stamp"],WB:"Upcoming"},{T:"div",N:"ytp-autonav-list-overlay",C:[{T:"div",N:"ytp-autonav-mix-text",WB:"Mix"},{T:"div",N:"ytp-autonav-mix-icon"}]}]},{T:"div",M5:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],WB:"{{title}}"},{T:"div",M5:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],WB:"{{author}}"},{T:"div",M5:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],WB:"{{views_and_publish_time}}"}]});this.S=N;this.suggestion=
null;this.G=O;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},ij=function(N,h){h=h===void 0?!1:h;
g.f.call(this,{T:"div",N:"ytp-autonav-endscreen-countdown-overlay"});var O=this;this.V=h;this.cancelCommand=this.L=void 0;this.U=0;this.container=new g.f({T:"div",N:"ytp-autonav-endscreen-countdown-container"});g.H(this,this.container);this.container.rf(this.element);h=N.K();var u=h.X;this.S=N;this.suggestion=null;this.onVideoDataChange("newdata",this.S.getVideoData());this.J(N,"videodatachange",this.onVideoDataChange);this.G=new g.f({T:"div",N:"ytp-autonav-endscreen-upnext-container",Z:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},C:[{T:"div",N:"ytp-autonav-endscreen-upnext-header"},{T:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",WB:"{{autoplayAlternativeHeader}}"},{T:"a",N:"ytp-autonav-endscreen-link-container",Z:{href:"{{url}}",target:u?h.D:""},C:[{T:"div",N:"ytp-autonav-endscreen-upnext-thumbnail",Z:{style:"{{background}}"},C:[{T:"div",Z:{"aria-label":"{{timestamp}}"},M5:["ytp-autonav-timestamp"],
WB:"{{duration}}"},{T:"div",M5:["ytp-autonav-live-stamp"],WB:"Live"},{T:"div",M5:["ytp-autonav-upcoming-stamp"],WB:"Upcoming"}]},{T:"div",N:"ytp-autonav-endscreen-video-info",C:[{T:"div",N:"ytp-autonav-endscreen-premium-badge"},{T:"div",N:"ytp-autonav-endscreen-upnext-title",WB:"{{title}}"},{T:"div",N:"ytp-autonav-endscreen-upnext-author",WB:"{{author}}"},{T:"div",N:"ytp-autonav-view-and-date",WB:"{{views_and_publish_time}}"},{T:"div",N:"ytp-autonav-author-and-view",WB:"{{author_and_views}}"}]}]}]});
g.H(this,this.G);this.G.rf(this.container.element);u||this.J(this.G.Ir("ytp-autonav-endscreen-link-container"),"click",this.X5);this.S.createClientVe(this.container.element,this,115127);this.S.createClientVe(this.G.Ir("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.f({T:"div",N:"ytp-autonav-overlay"});g.H(this,this.overlay);this.overlay.rf(this.container.element);this.W=new g.f({T:"div",N:"ytp-autonav-endscreen-button-container"});g.H(this,this.W);this.W.rf(this.container.element);
this.cancelButton=new g.f({T:"button",M5:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",h.j("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Z:{"aria-label":"Cancel autoplay"},WB:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.rf(this.W.element);this.cancelButton.listen("click",this.eh,this);this.S.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.f({T:"a",M5:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
h.j("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Z:{href:"{{url}}",role:"button","aria-label":"Play next video"},WB:"Play Now"});g.H(this,this.playButton);this.playButton.rf(this.W.element);this.playButton.listen("click",this.X5,this);this.S.createServerVe(this.playButton.element,this.playButton,!0);(h=this.S.getVideoData())&&U25(this,h);this.X=new g.YL(function(){d2V(O)},500);
g.H(this,this.X);this.It();this.J(N,"autonavvisibility",this.It);this.S.j("web_autonav_color_transition")&&(this.J(N,"autonavchange",this.ya),this.J(N,"onAutonavCoundownStarted",this.fTC))},Bu=function(N){var h=N.S.r9(!0,N.S.isFullscreen());
g.GC(N.container.element,"ytp-autonav-endscreen-small-mode",N.jo(h));g.GC(N.container.element,"ytp-autonav-endscreen-is-premium",!!N.suggestion&&!!N.suggestion.SBn);g.GC(N.S.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!N.S.qH());g.GC(N.S.getRootNode(),"countdown-running",N.S3());g.GC(N.container.element,"ytp-player-content",N.S.qH());g.fF(N.overlay.element,{width:h.width+"px"});if(!N.S3()){N.S.qH()?G2K(N,Math.round(bbo(N)/1E3)):G2K(N);h=!!N.suggestion&&!!N.suggestion.Dp;var O=N.S.qH()||
!h;g.GC(N.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!O&&h);g.GC(N.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",O&&!h);N.W.gq(N.S.qH());g.GC(N.element,"ytp-enable-w2w-color-transitions",ibx(N))}},d2V=function(N){var h=bbo(N),O=Math,u=O.min;
var D=N.U?Date.now()-N.U:0;O=u.call(O,D,h);G2K(N,Math.ceil((h-O)/1E3));h-O<=500&&N.S3()?N.select(!0):N.S3()&&N.X.start()},bbo=function(N){if(N.S.isFullscreen()){var h;
N=(h=N.S.getVideoData())==null?void 0:h.d4;return N===-1||N===void 0?8E3:N}return N.S.LX()>=0?N.S.LX():g.u8(N.S.K().experiments,"autoplay_time")||1E4},U25=function(N,h){h=h.getWatchNextResponse();
var O,u;h=(O=D2o(h))==null?void 0:(u=O.nextButton)==null?void 0:u.buttonRenderer;N.L=h==null?void 0:h.navigationEndpoint;O=h==null?void 0:h.trackingParams;N.playButton&&O&&N.S.setTrackingParams(N.playButton.element,O)},ibx=function(N){var h;
return!((h=N.S.getVideoData())==null||!h.watchToWatchTransitionRenderer)},G2K=function(N,h){h=h===void 0?-1:h;
N=N.G.Ir("ytp-autonav-endscreen-upnext-header");g.wX(N);if(h>=0){h=String(h);var O="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],u="Up next in $SECONDS".indexOf(O);if(u>=0){N.appendChild(g.zy("Up next in $SECONDS".slice(0,u)));var D=g.LF("span");g.hh(D,"ytp-autonav-endscreen-upnext-header-countdown-number");g.tA(D,h);N.appendChild(D);N.appendChild(g.zy("Up next in $SECONDS".slice(u+O.length)));return}}g.tA(N,"Up next")},Ci=function(N,h){g.f.call(this,{T:"div",
M5:["html5-endscreen","ytp-player-content",h||"base-endscreen"]});this.created=!1;this.player=N},AH=function(N){g.f.call(this,{T:"div",
M5:["ytp-upnext","ytp-player-content"],Z:{"aria-label":"{{aria_label}}"},C:[{T:"div",N:"ytp-cued-thumbnail-overlay-image",Z:{style:"{{background}}"}},{T:"span",N:"ytp-upnext-top",C:[{T:"span",N:"ytp-upnext-header",WB:"Up Next"},{T:"span",N:"ytp-upnext-title",WB:"{{title}}"},{T:"span",N:"ytp-upnext-author",WB:"{{author}}"}]},{T:"a",N:"ytp-upnext-autoplay-icon",Z:{role:"button",href:"{{url}}","aria-label":"Play next video"},C:[{T:"svg",Z:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
C:[{T:"circle",N:"ytp-svg-autoplay-circle",Z:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{T:"circle",N:"ytp-svg-autoplay-ring",Z:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{T:"path",N:"ytp-svg-fill",Z:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{T:"span",N:"ytp-upnext-bottom",C:[{T:"span",N:"ytp-upnext-cancel"},{T:"span",N:"ytp-upnext-paused",
WB:"Autoplay is paused"}]}]});this.api=N;this.cancelButton=null;this.L=this.Ir("ytp-svg-autoplay-ring");this.U=this.notification=this.G=this.suggestion=null;this.X=new g.YL(this.Bj,5E3,this);this.W=0;var h=this.Ir("ytp-upnext-cancel");this.cancelButton=new g.f({T:"button",M5:["ytp-upnext-cancel-button","ytp-button"],Z:{tabindex:"0","aria-label":"Cancel autoplay"},WB:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.listen("click",this.Ge,this);this.cancelButton.rf(h);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.H(this,this.X);this.api.createClientVe(this.element,this,18788);h=this.Ir("ytp-upnext-autoplay-icon");this.J(h,"click",this.fV);this.api.createClientVe(h,this,115130);this.bC();this.J(N,"autonavvisibility",this.bC);this.J(N,"mdxnowautoplaying",this.JdO);this.J(N,"mdxautoplaycanceled",this.ZFC);g.GC(this.element,"ytp-upnext-mobile",this.api.K().W)},BrV=function(N,h){if(h)return h;
if(N.api.isFullscreen()){var O;N=(O=N.api.getVideoData())==null?void 0:O.d4;return N===-1||N===void 0?8E3:N}return N.api.LX()>=0?N.api.LX():g.u8(N.api.K().experiments,"autoplay_time")||1E4},CKx=function(N,h){h=BrV(N,h);
var O=Math,u=O.min;var D=(0,g.to)()-N.W;O=u.call(O,D,h);h=h===0?1:Math.min(O/h,1);N.L.setAttribute("stroke-dashoffset",""+-211*(h+1));h>=1&&N.S3()&&N.api.getPresentingPlayerType()!==3?N.select(!0):N.S3()&&N.G.start()},oj=function(N){Ci.call(this,N,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.f({T:"div",N:"ytp-suggestion-panel",C:[{T:"div",M5:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],WB:"More videos"}]});this.B=new g.f({T:"div",N:"ytp-suggestions-container"});this.videos=[];this.U=null;this.L=this.V=!1;this.W=new ij(this.player);g.H(this,this.W);this.W.rf(this.element);N.getVideoData().gU?this.G=this.W:(this.G=new AH(N),g.O9(this.player,this.G.element,4),g.H(this,this.G));this.overlay=new g.f({T:"div",
N:"ytp-autonav-overlay-cancelled-state"});g.H(this,this.overlay);this.overlay.rf(this.element);this.X=new g.yg(this);g.H(this,this.X);g.H(this,this.table);this.table.rf(this.element);this.table.show();g.H(this,this.B);this.B.rf(this.table.element);this.hide()},QR=function(N){var h=N.qH();
h!==N.L&&(N.L=h,ObK(N.player),N.L?(N.W!==N.G&&N.W.hide(),N.table.hide()):(N.W!==N.G&&N.W.show(),N.table.show()))},Ap4=function(N){Ci.call(this,N,"videowall-endscreen");
var h=this;this.S=N;this.stills=[];this.U=this.videoData=null;this.X=this.V=!1;this.B=null;g.u9(this.element,"modern-videowall-endscreen");this.W=new g.yg(this);g.H(this,this.W);this.L=new g.YL(function(){g.u9(h.element,"ytp-show-tiles")},0);
g.H(this,this.L);this.table=new g.Ux({T:"div",N:"ytp-modern-endscreen-content"});g.H(this,this.table);this.table.rf(this.element);N.getVideoData().gU?this.G=new ij(N,!0):this.G=new AH(N);g.H(this,this.G);g.O9(this.player,this.G.element,4);N.createClientVe(this.element,this,158789);this.hide()},Li=function(N){return g.ub(N.player)&&N.zJ()&&!N.U},zO=function(N){var h=N.qH();
h!==N.V&&(N.V=h,ObK(N.player))},odo=function(N){Ci.call(this,N,"subscribecard-endscreen");
this.G=new g.f({T:"div",N:"ytp-subscribe-card",C:[{T:"img",N:"ytp-author-image",Z:{src:"{{profilePicture}}"}},{T:"div",N:"ytp-subscribe-card-right",C:[{T:"div",N:"ytp-author-name",WB:"{{author}}"},{T:"div",N:"html5-subscribe-button-container"}]}]});g.H(this,this.G);this.G.rf(this.element);var h=N.getVideoData();this.subscribeButton=new g.UG("Subscribe",null,"Unsubscribe",null,!0,!1,h.zc,h.subscribed,"trailer-endscreen",null,N,!1);g.H(this,this.subscribeButton);this.subscribeButton.rf(this.G.Ir("html5-subscribe-button-container"));
this.J(N,"videodatachange",this.N5);this.N5();this.hide()},vu=function(N){var h=N.K(),O=g.m1||g.hR?{style:"will-change: opacity"}:void 0,u=h.X,D=["ytp-videowall-still"];
h.W&&D.push("ytp-videowall-show-text");g.f.call(this,{T:"a",M5:D,Z:{href:"{{url}}",target:u?h.D:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},C:[{T:"div",N:"ytp-videowall-still-image",Z:{style:"{{background}}"}},{T:"span",N:"ytp-videowall-still-info",Z:{"aria-hidden":"true"},C:[{T:"span",N:"ytp-videowall-still-info-bg",C:[{T:"span",N:"ytp-videowall-still-info-content",Z:O,C:[{T:"span",N:"ytp-videowall-still-info-title",WB:"{{title}}"},
{T:"span",N:"ytp-videowall-still-info-author",WB:"{{author_and_views}}"},{T:"span",N:"ytp-videowall-still-info-live",WB:"Live"},{T:"span",N:"ytp-videowall-still-info-duration",WB:"{{duration}}"}]}]}]},{T:"span",M5:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Z:{"aria-hidden":"true"},C:[{T:"span",N:"ytp-videowall-still-listlabel-icon"},"Playlist",{T:"span",N:"ytp-videowall-still-listlabel-length",C:[" (",{T:"span",WB:"{{playlist_length}}"},")"]}]},{T:"span",M5:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Z:{"aria-hidden":"true"},C:[{T:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{T:"span",N:"ytp-videowall-still-listlabel-length",WB:" (50+)"}]}]});this.suggestion=null;this.W=u;this.api=N;this.G=new g.yg(this);g.H(this,this.G);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.G.J(N,"videodatachange",this.onVideoDataChange);N.createServerVe(this.element,this);this.onVideoDataChange()},wU=function(N){Ci.call(this,N,"videowall-endscreen");
var h=this;this.S=N;this.U=0;this.stills=[];this.X=this.videoData=null;this.L=this.B=!1;this.D=null;this.W=new g.yg(this);g.H(this,this.W);this.V=new g.YL(function(){g.u9(h.element,"ytp-show-tiles")},0);
g.H(this,this.V);var O=new g.f({T:"button",M5:["ytp-button","ytp-endscreen-previous"],Z:{"aria-label":"Previous"},C:[g.QT()]});g.H(this,O);O.rf(this.element);O.listen("click",this.X8,this);this.table=new g.Ux({T:"div",N:"ytp-endscreen-content"});g.H(this,this.table);this.table.rf(this.element);O=new g.f({T:"button",M5:["ytp-button","ytp-endscreen-next"],Z:{"aria-label":"Next"},C:[g.Lv()]});g.H(this,O);O.rf(this.element);O.listen("click",this.va,this);N.getVideoData().gU?this.G=new ij(N,!0):this.G=
new AH(N);g.H(this,this.G);g.O9(this.player,this.G.element,4);N.createClientVe(this.element,this,158789);this.hide()},Ki=function(N){return g.ub(N.player)&&N.zJ()&&!N.X},ms=function(N){var h=N.qH();
h!==N.B&&(N.B=h,ObK(N.player))},Qu4=function(N,h){g.f.call(this,{T:"button",
M5:["ytp-watch-on-youtube-button","ytp-button"],WB:"{{content}}"});this.S=N;this.buttonType=this.buttonType=h;this.SL();this.buttonType===2&&g.u9(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.SL);this.gq(!0)},Ij=function(N){Ci.call(this,N,"watch-again-on-youtube-endscreen");
this.watchButton=new Qu4(N,1);g.H(this,this.watchButton);this.watchButton.rf(this.element);g.k5o(N)&&(this.G=new g.NT(N),g.H(this,this.G),this.W=new g.f({T:"div",M5:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Z:{tabIndex:"-1"},C:[this.G]}),g.H(this,this.W),this.G.rf(this.W.element),this.W.rf(this.element));N.createClientVe(this.element,this,156914);this.hide()},wpK=function(N){g.Vq.call(this,N);
var h=this;this.endScreen=null;this.G=this.W=this.U=!1;this.listeners=new g.yg(this);g.H(this,this.listeners);var O=N.K();N.isEmbedsShortsMode()?this.endScreen=new Ij(N):Lwo(N)?(this.U=!0,zhj(this),this.G?this.endScreen=new oj(N):O.j("delhi_modern_endscreen")?this.endScreen=new Ap4(N):this.endScreen=new wU(N)):O.kE?this.endScreen=new odo(N):this.endScreen=new Ci(N);g.H(this,this.endScreen);g.O9(N,this.endScreen.element,4);vd5(this);this.listeners.J(N,"videodatachange",this.onVideoDataChange,this);
this.listeners.J(N,g.xm("endscreen"),function(u){h.onCueRangeEnter(u)});
this.listeners.J(N,g.np("endscreen"),function(u){h.onCueRangeExit(u)})},zhj=function(N){var h=N.player.getVideoData();
if(!h||N.G===h.Db&&N.W===h.gU)return!1;N.G=h.Db;N.W=h.gU;return!0},Lwo=function(N){N=N.K();
return N.gU&&!N.kE&&!N.disableOrganicUi},vd5=function(N){N.player.SV("endscreen");
var h=N.player.getVideoData();h=new g.Ym(Math.max((h.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var O=new g.Ym(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});N.player.Vq([h,O])};
g.lw.prototype.LX=g.Dd(6,function(){return this.app.LX()});
g.wG.prototype.LX=g.Dd(5,function(){return this.getVideoData().K1});
g.Wc.prototype.zv=g.Dd(4,function(N){this.h9().zv(N)});
g.Zv.prototype.zv=g.Dd(3,function(N){this.MC!==N&&(this.MC=N,this.Jm())});
g.K(bj,g.f);bj.prototype.select=function(){this.S.Yz(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Nc||void 0)&&this.S.logClick(this.element)};
bj.prototype.onClick=function(N){g.pk(N,this.S,this.G,this.suggestion.sessionData||void 0)&&this.select()};
bj.prototype.onKeyPress=function(N){switch(N.keyCode){case 13:case 32:N.defaultPrevented||(this.select(),N.preventDefault())}};g.K(ij,g.f);g.w=ij.prototype;g.w.pI=function(N){this.suggestion!==N&&(this.suggestion=N,g.CP(this.G,N),this.playButton.updateValue("url",this.suggestion.Os()),Bu(this))};
g.w.S3=function(){return this.U>0};
g.w.ZK=function(){this.S3()||(this.U=Date.now(),d2V(this),u6Y(this.S,bbo(this)),g.GC(this.S.getRootNode(),"countdown-running",this.S3()))};
g.w.LH=function(){this.Q3();d2V(this);var N=this.G.Ir("ytp-autonav-endscreen-upnext-header");N&&g.tA(N,"Up next")};
g.w.Q3=function(){this.S3()&&(this.X.stop(),this.U=0)};
g.w.select=function(N){this.S.nextVideo(!1,N===void 0?!1:N);this.Q3()};
g.w.X5=function(N){g.pk(N,this.S)&&(N.currentTarget===this.playButton.element?this.S.logClick(this.playButton.element):N.currentTarget===this.G.Ir("ytp-autonav-endscreen-link-container")&&(N=this.G.Ir("ytp-autonav-endscreen-link-container"),this.S.logVisibility(N,!0),this.S.logClick(N)),this.L?(this.S.wf("innertubeCommand",this.L),this.Q3()):this.select())};
g.w.eh=function(){this.S.logClick(this.cancelButton.element);g.nj(this.S,!0);this.cancelCommand&&this.S.wf("innertubeCommand",this.cancelCommand)};
g.w.onVideoDataChange=function(N,h){U25(this,h);N=h.getWatchNextResponse();var O,u;N=(O=D2o(N))==null?void 0:(u=O.cancelButton)==null?void 0:u.buttonRenderer;this.cancelCommand=N==null?void 0:N.command};
g.w.fTC=function(N){if(ibx(this)){var h=this.S.getVideoData().watchToWatchTransitionRenderer,O=h==null?void 0:h.fromColorPaletteDark;h=h==null?void 0:h.toColorPaletteDark;if(O&&h){var u=this.element;u.style.setProperty("--w2w-start-background-color",g.gD(O.surgeColor));u.style.setProperty("--w2w-start-primary-text-color",g.gD(O.primaryTitleColor));u.style.setProperty("--w2w-start-secondary-text-color",g.gD(O.secondaryTitleColor));u.style.setProperty("--w2w-end-background-color",g.gD(h.surgeColor));
u.style.setProperty("--w2w-end-primary-text-color",g.gD(h.primaryTitleColor));u.style.setProperty("--w2w-end-secondary-text-color",g.gD(h.secondaryTitleColor));u.style.setProperty("--w2w-animation-duration",N+"ms")}g.GC(this.element,"ytp-w2w-animate",!0)}};
g.w.ya=function(N){this.S.j("web_autonav_color_transition")&&N!==2&&g.GC(this.element,"ytp-w2w-animate",!1)};
g.w.It=function(){var N=this.S.qH();this.V&&this.fF!==N&&this.gq(N);Bu(this);this.S.logVisibility(this.container.element,N);this.S.logVisibility(this.cancelButton.element,N);this.S.logVisibility(this.G.Ir("ytp-autonav-endscreen-link-container"),N);this.S.logVisibility(this.playButton.element,N)};
g.w.jo=function(N){return N.width<400||N.height<459};g.K(Ci,g.f);g.w=Ci.prototype;g.w.create=function(){this.created=!0};
g.w.destroy=function(){this.created=!1};
g.w.zJ=function(){return!1};
g.w.qH=function(){return!1};
g.w.n0=function(){return!1};g.K(AH,g.f);g.w=AH.prototype;g.w.Bj=function(){this.notification&&(this.X.stop(),this.Td(this.U),this.U=null,this.notification.close(),this.notification=null)};
g.w.pI=function(N){this.suggestion=N;g.CP(this,N,"hqdefault.jpg")};
g.w.bC=function(){this.gq(this.api.qH());this.api.logVisibility(this.element,this.api.qH());this.api.logVisibility(this.Ir("ytp-upnext-autoplay-icon"),this.api.qH());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.qH())};
g.w.QO0=function(){window.focus();this.Bj()};
g.w.ZK=function(N){var h=this;this.S3()||(g.h8("a11y-announce","Up Next "+this.suggestion.title),this.W=(0,g.to)(),this.G=new g.YL(function(){CKx(h,N)},25),CKx(this,N),u6Y(this.api,BrV(this,N)));
g.UC(this.element,"ytp-upnext-autoplay-paused")};
g.w.hide=function(){g.f.prototype.hide.call(this)};
g.w.S3=function(){return!!this.G};
g.w.LH=function(){this.Q3();this.W=(0,g.to)();CKx(this);g.u9(this.element,"ytp-upnext-autoplay-paused")};
g.w.Q3=function(){this.S3()&&(this.G.dispose(),this.G=null)};
g.w.select=function(N){N=N===void 0?!1:N;if(this.api.K().j("autonav_notifications")&&N&&window.Notification&&typeof document.hasFocus==="function"){var h=Notification.permission;h==="default"?Notification.requestPermission():h!=="granted"||document.hasFocus()||(this.Bj(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Jv()}),this.U=this.J(this.notification,"click",this.QO0),this.X.start())}this.Q3();this.api.nextVideo(!1,N)};
g.w.fV=function(N){!g.Iv(this.cancelButton.element,N.target)&&g.pk(N,this.api)&&(this.api.qH()&&this.api.logClick(this.Ir("ytp-upnext-autoplay-icon")),this.select())};
g.w.Ge=function(){this.api.qH()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.nj(this.api,!0)};
g.w.JdO=function(N){this.api.getPresentingPlayerType();this.show();this.ZK(N)};
g.w.ZFC=function(){this.api.getPresentingPlayerType();this.Q3();this.hide()};
g.w.q5=function(){this.Q3();this.Bj();g.f.prototype.q5.call(this)};g.K(oj,Ci);g.w=oj.prototype;g.w.create=function(){Ci.prototype.create.call(this);this.X.J(this.player,"appresize",this.cS);this.X.J(this.player,"onVideoAreaChange",this.cS);this.X.J(this.player,"videodatachange",this.onVideoDataChange);this.X.J(this.player,"autonavchange",this.iC);this.X.J(this.player,"onAutonavCancelled",this.oy);this.onVideoDataChange()};
g.w.show=function(){Ci.prototype.show.call(this);(this.V||this.U&&this.U!==this.videoData.clientPlaybackNonce)&&g.nj(this.player,!1);g.ub(this.player)&&this.zJ()&&!this.U?(QR(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.ZK():this.videoData.autonavState===3&&this.G.LH()):(g.nj(this.player,!0),QR(this));this.cS()};
g.w.hide=function(){Ci.prototype.hide.call(this);this.G.LH();QR(this)};
g.w.cS=function(){var N=this.player.r9(!0,this.player.isFullscreen());QR(this);Bu(this.W);g.GC(this.element,"ytp-autonav-cancelled-small-mode",this.jo(N));g.GC(this.element,"ytp-autonav-cancelled-tiny-mode",this.TH(N));g.GC(this.element,"ytp-autonav-cancelled-mini-mode",N.width<=400||N.height<=360);this.overlay&&g.fF(this.overlay.element,{width:N.width+"px"});if(!this.L)for(N=0;N<this.videos.length;N++)g.GC(this.videos[N].element,"ytp-suggestion-card-with-margin",N%2===1)};
g.w.onVideoDataChange=function(){var N=this.player.getVideoData();if(this.videoData!==N&&N){this.videoData=N;if((N=this.videoData.suggestions)&&N.length||this.player.j("web_player_autonav_empty_suggestions_fix")){var h=g.RP(this.videoData);h&&(this.G.pI(h),this.G!==this.W&&this.W.pI(h))}if(N&&N.length)for(h=0;h<KwR.length;++h){var O=KwR[h];if(N&&N[O]){this.videos[h]=new bj(this.player);var u=this.videos[h];O=N[O];u.suggestion!==O&&(u.suggestion=O,g.CP(u,O));g.H(this,this.videos[h]);this.videos[h].rf(this.B.element)}}this.cS()}};
g.w.iC=function(N){N===1?(this.V=!1,this.U=this.videoData.clientPlaybackNonce,this.G.Q3(),this.fF&&this.cS()):(this.V=!0,this.qH()&&(N===2?this.G.ZK():N===3&&this.G.LH()))};
g.w.oy=function(N){N?this.iC(1):(this.U=null,this.V=!1)};
g.w.zJ=function(){return this.videoData.autonavState!==1};
g.w.jo=function(N){return(N.width<910||N.height<459)&&!this.TH(N)&&!(N.width<=400||N.height<=360)};
g.w.TH=function(N){return N.width<800&&!(N.width<=400||N.height<=360)};
g.w.qH=function(){return this.fF&&g.ub(this.player)&&this.zJ()&&!this.U};
var KwR=[1,3,2,4];g.K(Ap4,Ci);g.w=Ap4.prototype;g.w.create=function(){Ci.prototype.create.call(this);var N=this.player.getVideoData();N&&(this.videoData=N);this.bq();this.W.J(this.player,"appresize",this.bq);this.W.J(this.player,"onVideoAreaChange",this.bq);this.W.J(this.player,"videodatachange",this.onVideoDataChange);this.W.J(this.player,"autonavchange",this.Rw);this.W.J(this.player,"onAutonavCancelled",this.Wa);N=this.videoData.autonavState;N!==this.B&&this.Rw(N);this.W.J(this.element,"transitionend",this.qm)};
g.w.destroy=function(){g.RV(this.W);g.Uu(this.stills);this.stills=[];Ci.prototype.destroy.call(this);g.UC(this.element,"ytp-show-tiles");this.L.stop();this.B=this.videoData.autonavState};
g.w.zJ=function(){return this.videoData.autonavState!==1};
g.w.show=function(){var N=this.fF;Ci.prototype.show.call(this);g.UC(this.element,"ytp-show-tiles");this.player.K().W?g.xL(this.L):this.L.start();(this.X||this.U&&this.U!==this.videoData.clientPlaybackNonce)&&g.nj(this.player,!1);Li(this)?(zO(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.ZK():this.videoData.autonavState===3&&this.G.LH()):(g.nj(this.player,!0),zO(this));N!==this.fF&&this.player.logVisibility(this.element,!0)};
g.w.hide=function(){var N=this.fF;Ci.prototype.hide.call(this);this.G.LH();zO(this);N!==this.fF&&this.player.logVisibility(this.element,!1)};
g.w.qm=function(N){N.target===this.element&&this.bq()};
g.w.bq=function(){var N,h,O,u;var D=((N=this.videoData)==null?0:(h=N.suggestions)==null?0:h.length)?(O=this.videoData)==null?void 0:O.suggestions:[(u=this.videoData)==null?void 0:g.RP(u)];if(D.length){h=this.S.r9(!0,this.S.isFullscreen());N=Math.floor((h.width-64+16)/(g.S8(h.width*.27,250,450)+16));h=Math.min(3,Math.floor((h.height-64)/((h.width-64-(N-1)*16)/N*.5625+70)));g.dI(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.u9(this.element,"ytp-modern-endscreen-limit-rows-"+h);g.GC(this.element,"ytp-modern-endscreen-single-item",N===1);g.GC(this.element,"ytp-modern-endscreen-row-0",h===0);N=this.table.element;N.ariaLive="polite";this.G.pI(g.RP(this.videoData));this.G instanceof ij&&Bu(this.G);g.GC(this.element,"ytp-endscreen-takeover",Li(this));zO(this);h=0;N.ariaBusy="true";O=D.length;for(u=0;u<O;u++){var U=u%O,d=this.stills[u];d||(d=new g.AB(this.player),this.stills[u]=d,N.appendChild(d.element));g.f67(d,D[U]);h++}this.stills.length=
h}};
g.w.onVideoDataChange=function(){var N=this.player.getVideoData(1);this.videoData!==N&&(N!=null&&g.RP(N)?(this.videoData=N,this.bq()):this.player.GO("missg",{vid:(N==null?void 0:N.videoId)||"",cpn:(N==null?void 0:N.clientPlaybackNonce)||""}))};
g.w.n0=function(){return this.G.S3()};
g.w.Rw=function(N){N===1?(this.X=!1,this.U=this.videoData.clientPlaybackNonce,this.G.Q3(),this.fF&&this.bq()):(this.X=!0,this.fF&&Li(this)&&(N===2?this.G.ZK():N===3&&this.G.LH()))};
g.w.Wa=function(N){if(N){for(N=0;N<this.stills.length;N++)this.S.logVisibility(this.stills[N].element,!0);this.Rw(1)}else this.U=null,this.X=!1;this.bq()};
g.w.qH=function(){return this.fF&&Li(this)};g.K(odo,Ci);odo.prototype.N5=function(){var N=this.player.getVideoData();this.G.update({profilePicture:N.profilePicture,author:N.author});this.subscribeButton.channelId=N.zc;var h=this.subscribeButton;N.subscribed?h.G():h.W()};g.K(vu,g.f);vu.prototype.select=function(){this.api.Yz(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Nc||void 0)&&this.api.logClick(this.element)};
vu.prototype.onClick=function(N){if(g.uM(this.api.K())&&this.api.j("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var h=this.suggestion.Os(),O={};g.kj(this.api,O);h=g.KM(h,O);g.e1(h,this.api,N)}else g.pk(N,this.api,this.W,this.suggestion.sessionData||void 0)&&this.select()};
vu.prototype.onKeyPress=function(N){switch(N.keyCode){case 13:case 32:N.defaultPrevented||(this.select(),N.preventDefault())}};
vu.prototype.onVideoDataChange=function(){var N=this.api.getVideoData(),h=this.api.K();this.W=N.E8?!1:h.X};g.K(wU,Ci);g.w=wU.prototype;g.w.create=function(){Ci.prototype.create.call(this);var N=this.player.getVideoData();N&&(this.videoData=N);this.f5();this.W.J(this.player,"appresize",this.f5);this.W.J(this.player,"onVideoAreaChange",this.f5);this.W.J(this.player,"videodatachange",this.onVideoDataChange);this.W.J(this.player,"autonavchange",this.PC);this.W.J(this.player,"onAutonavCancelled",this.UY);N=this.videoData.autonavState;N!==this.D&&this.PC(N);this.W.J(this.element,"transitionend",this.bO)};
g.w.destroy=function(){g.RV(this.W);g.Uu(this.stills);this.stills=[];Ci.prototype.destroy.call(this);g.UC(this.element,"ytp-show-tiles");this.V.stop();this.D=this.videoData.autonavState};
g.w.zJ=function(){return this.videoData.autonavState!==1};
g.w.show=function(){var N=this.fF;Ci.prototype.show.call(this);g.UC(this.element,"ytp-show-tiles");this.player.K().W?g.xL(this.V):this.V.start();(this.L||this.X&&this.X!==this.videoData.clientPlaybackNonce)&&g.nj(this.player,!1);Ki(this)?(ms(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.G.select(!0):this.G.ZK():this.videoData.autonavState===3&&this.G.LH()):(g.nj(this.player,!0),ms(this));N!==this.fF&&this.player.logVisibility(this.element,!0)};
g.w.hide=function(){var N=this.fF;Ci.prototype.hide.call(this);this.G.LH();ms(this);N!==this.fF&&this.player.logVisibility(this.element,!1)};
g.w.bO=function(N){N.target===this.element&&this.f5()};
g.w.f5=function(){var N,h,O,u;var D=((N=this.videoData)==null?0:(h=N.suggestions)==null?0:h.length)?(O=this.videoData)==null?void 0:O.suggestions:[(u=this.videoData)==null?void 0:g.RP(u)];if(D.length){g.u9(this.element,"ytp-endscreen-paginate");var U=this.S.r9(!0,this.S.isFullscreen());if(N=g.Jx(this.S))N=N.lm()?48:32,U.width-=N*2;var d=U.width/U.height;u=96/54;h=N=2;var b=Math.max(U.width/96,2),B=Math.max(U.height/54,2);O=D.length;var C=O*4;for(C-=4;C>0&&(N<b||h<B);){var A=N/2,Q=h/2,L=N<=b-2&&C>=
Q*4,z=h<=B-2&&C>=A*4;if((A+1)/Q*u/d>d/(A/(Q+1)*u)&&z)C-=A*4,h+=2;else if(L)C-=Q*4,N+=2;else if(z)C-=A*4,h+=2;else break}u=!1;C>=12&&O*4-C<=6&&(h>=4||N>=4)&&(u=!0);C=N*96;b=h*54;d=C/b<d?U.height/b:U.width/C;d=Math.min(d,2);C=Math.floor(Math.min(U.width,C*d));b=Math.floor(Math.min(U.height,b*d));U=this.table.element;U.ariaLive="polite";g.Ol(U,C,b);g.fF(U,{marginLeft:C/-2+"px",marginTop:b/-2+"px"});this.G.pI(g.RP(this.videoData));this.G instanceof ij&&Bu(this.G);g.GC(this.element,"ytp-endscreen-takeover",
Ki(this));ms(this);C+=4;b+=4;d=0;U.ariaBusy="true";for(B=0;B<N;B++)for(A=0;A<h;A++)if(Q=d,z=0,u&&B>=N-2&&A>=h-2?z=1:A%2===0&&B%2===0&&(A<2&&B<2?A===0&&B===0&&(z=2):z=2),Q=g.Hy(Q+this.U,O),z!==0){L=this.stills[d];L||(L=new vu(this.player),this.stills[d]=L,U.appendChild(L.element));var v=Math.floor(b*A/h),t=Math.floor(C*B/N),R=Math.floor(b*(A+z)/h)-v-4,p=Math.floor(C*(B+z)/N)-t-4;g.Z0(L.element,t,v);g.Ol(L.element,p,R);g.fF(L.element,"transitionDelay",(A+B)/20+"s");g.GC(L.element,"ytp-videowall-still-mini",
z===1);g.GC(L.element,"ytp-videowall-still-large",z>2);z=Math.max(p,R);g.GC(L.element,"ytp-videowall-still-round-large",z>=256);g.GC(L.element,"ytp-videowall-still-round-medium",z>96&&z<256);g.GC(L.element,"ytp-videowall-still-round-small",z<=96);Q=D[Q];L.suggestion!==Q&&(L.suggestion=Q,z=L.api.K(),v=g.OC(L.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.CP(L,Q,v),g.uM(z)&&!L.api.j("web_player_log_click_before_generating_ve_conversion_params")&&(z=Q.Os(),v={},g.aX(L.api,"addEmbedsConversionTrackingParams",
[v]),z=g.KM(z,v),L.updateValue("url",z)),(Q=(Q=Q.sessionData)&&Q.itct)&&L.api.setTrackingParams(L.element,Q));d++}U.ariaBusy="false";g.GC(this.element,"ytp-endscreen-paginate",d<O);for(D=this.stills.length-1;D>=d;D--)N=this.stills[D],g.mq(N.element),g.DV(N);this.stills.length=d}};
g.w.onVideoDataChange=function(){var N=this.player.getVideoData(1);this.videoData!==N&&(N!=null&&g.RP(N)?(this.U=0,this.videoData=N,this.f5()):this.player.GO("missg",{vid:(N==null?void 0:N.videoId)||"",cpn:(N==null?void 0:N.clientPlaybackNonce)||""}))};
g.w.va=function(){this.U+=this.stills.length;this.f5()};
g.w.X8=function(){this.U-=this.stills.length;this.f5()};
g.w.n0=function(){return this.G.S3()};
g.w.PC=function(N){N===1?(this.L=!1,this.X=this.videoData.clientPlaybackNonce,this.G.Q3(),this.fF&&this.f5()):(this.L=!0,this.fF&&Ki(this)&&(N===2?this.G.ZK():N===3&&this.G.LH()))};
g.w.UY=function(N){if(N){for(N=0;N<this.stills.length;N++)this.S.logVisibility(this.stills[N].element,!0);this.PC(1)}else this.X=null,this.L=!1;this.f5()};
g.w.qH=function(){return this.fF&&Ki(this)};g.K(Qu4,g.f);g.w=Qu4.prototype;g.w.SL=function(){switch(this.buttonType){case 1:var N="Watch again on YouTube";var h=156915;break;case 2:N="Continue watching on YouTube";h=156942;break;default:N="Continue watching on YouTube",h=156942}this.update({content:N});this.S.hasVe(this.element)&&this.S.destroyVe(this.element);this.S.createClientVe(this.element,this,h)};
g.w.onClick=function(N){this.S.j("web_player_log_click_before_generating_ve_conversion_params")&&this.S.logClick(this.element);g.e1(this.getVideoUrl(),this.S,N);this.S.j("web_player_log_click_before_generating_ve_conversion_params")||this.S.logClick(this.element)};
g.w.getVideoUrl=function(){var N=!0;switch(this.buttonType){case 1:N=!0;break;case 2:N=!1}N=this.S.getVideoUrl(N,!1,!1,!0);var h=this.S.K();if(g.uM(h)){var O={};g.uM(h)&&g.aX(this.S,"addEmbedsConversionTrackingParams",[O]);N=g.KM(N,O)}return N};
g.w.logVisibility=function(){this.S.logVisibility(this.element,this.fF&&this.Y)};
g.w.show=function(){g.f.prototype.show.call(this);this.logVisibility()};
g.w.hide=function(){g.f.prototype.hide.call(this);this.logVisibility()};
g.w.DT=function(N){g.f.prototype.DT.call(this,N);this.logVisibility()};g.K(Ij,Ci);Ij.prototype.hasSuggestions=function(){var N;return(N=this.G)==null?void 0:N.hasSuggestions()};
Ij.prototype.show=function(){if(this.player.getPlayerState()!==3){Ci.prototype.show.call(this);var N=this.W;if(N){var h=this.G.hasSuggestions();g.GC(this.element,"ytp-shorts-branded-ui",h);h?N.show():N.hide()}var O;(O=g.Jx(this.player))==null||O.zv(!0);this.player.logVisibility(this.element,!0);this.watchButton.DT(!0)}};
Ij.prototype.hide=function(){Ci.prototype.hide.call(this);var N;(N=g.Jx(this.player))==null||N.zv(!1);this.player.logVisibility(this.element,!1);this.watchButton.DT(!1)};g.K(wpK,g.Vq);g.w=wpK.prototype;g.w.xz=function(){var N=this.player.getVideoData(),h=N.mutedAutoplay&&(N.limitedPlaybackDurationInSeconds>0||N.endSeconds>0||N.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!h)return!0;var O;var u=!!((N==null?0:g.RP(N))||(N==null?0:(O=N.suggestions)==null?0:O.length));u=!Lwo(this.player)||u;N=N.xm;O=this.player.sG();return u&&!N&&!O&&!h};
g.w.qH=function(){return this.endScreen.qH()};
g.w.zm=function(){return this.qH()?this.endScreen.n0():!1};
g.w.q5=function(){this.player.SV("endscreen");g.Vq.prototype.q5.call(this)};
g.w.load=function(){var N=this.player.getVideoData();var h=N.transitionEndpointAtEndOfStream;if(h&&h.videoId){var O=this.player.l_().JI.get("heartbeat"),u=g.RP(N);!u||h.videoId!==u.videoId||N.Nq?(this.player.Yz(h.videoId,void 0,void 0,!0,!0,h),O&&O.je("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),N=!0):N=!1}else N=!1;N||(g.Vq.prototype.load.call(this),this.endScreen.show())};
g.w.unload=function(){g.Vq.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.w.onCueRangeEnter=function(N){this.xz()&&(this.endScreen.created||this.endScreen.create(),N.getId()==="load"&&this.load())};
g.w.onCueRangeExit=function(N){N.getId()==="load"&&this.loaded&&this.unload()};
g.w.onVideoDataChange=function(){vd5(this);this.U&&zhj(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.G?this.endScreen=new oj(this.player):this.endScreen=new wU(this.player),g.H(this,this.endScreen),g.O9(this.player,this.endScreen.element,4))};g.yq("endscreen",wpK);})(_yt_player);
