(function(g){var window=this;'use strict';var m25=function(N,h){if(!Number.isFinite(N))return String(N);N=String(N);var O=N.indexOf(".");O===-1&&(O=N.length);var u=N[0]==="-"?"-":"";u&&(N=N.substring(1));return u+(0,g.zeS)("0",Math.max(0,h-O))+N},IyR=function(){return{T:"svg",
Z:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},C:[{T:"path",Z:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},tSY=function(){return{T:"svg",
Z:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},C:[{T:"path",Z:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},yp5=function(N){typeof N==="number"?(this.date=$2j(N,0,1),tH(this,1)):g.UR(N)?(this.date=$2j(N.getFullYear(),N.getMonth(),N.getDate()),tH(this,N.getDate())):(this.date=new Date(g.Aj()),N=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),tH(this,N))},$2j=function(N,h,O){h=new Date(N,h,O);
N>=0&&N<100&&h.setFullYear(h.getFullYear()-1900);return h},tH=function(N,h){N.getDate()!=h&&N.date.setUTCHours(N.date.getUTCHours()+(N.getDate()<h?1:-1))},$2=function(N,h){g.ib.call(this,N,{T:"div",
N:"ytp-reminder-menu",Z:{role:"menu",tabindex:"-1"},C:[{T:"div",N:"ytp-reminder-menu-contents",C:[{T:"div",N:"ytp-reminder-menu-items"}]}]},100,!0);this.G=h;this.U=[];this.menuPopupRenderer=void 0;this.items=this.Ir("ytp-reminder-menu-items");this.hide()},VSV=function(N){return(N.menuPopupRenderer&&N.menuPopupRenderer.items||[]).reduce(function(h,O){O&&O.menuServiceItemRenderer&&h.push(O.menuServiceItemRenderer);
return h},[])},yR=function(N){g.f.call(this,{T:"div",
C:[{T:"button",M5:["ytp-offline-slate-button","ytp-button"],C:[{T:"div",N:"ytp-offline-slate-button-icon",WB:"{{icon}}"},{T:"div",N:"ytp-offline-slate-button-text",WB:"{{text}}"}]}]});this.S=N;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.W=void 0;this.X=this.G=null;(this.L=this.Ir("ytp-offline-slate-button"))&&this.J(this.L,"click",this.V);this.hide()},PKY=function(N,h,O){!N.toggleButtonRenderer&&h&&h.toggleButtonRenderer?N.toggleButtonRenderer=h.toggleButtonRenderer:
h&&h.toggleButtonRenderer||(N.toggleButtonRenderer=null);
!N.upcomingEventReminderButtonRenderer&&O&&g.X(O,Rhm)?N.upcomingEventReminderButtonRenderer=g.X(O,Rhm):O&&g.X(O,Rhm)||(N.upcomingEventReminderButtonRenderer=null);VR(N)},VR=function(N){if(N.toggleButtonRenderer){var h=N.toggleButtonRenderer;
if(h.isToggled){var O=h.toggledText?g.Cv(h.toggledText):"";N.update({text:O,icon:MSm(h.toggledIcon)})}else O=h.defaultText?g.Cv(h.defaultText):"",N.update({text:O,icon:MSm(h.defaultIcon)});N.show()}else N.upcomingEventReminderButtonRenderer?(h=ppY(N))?(O=h.text?g.Cv(h.text):"",N.update({text:O,icon:MSm(h.icon)}),N.show()):N.hide():N.hide()},Edj=function(N,h,O){N.X||(N.X=new g.Yk(N.S.K().Ja));
var u={context:g.i$(N.X.config_||g.b$())};g.m7()&&(u.context.clientScreenNonce=g.m7());u.params=O;g.l$(N.X,h,u,{timeout:5E3,onSuccess:function(){N.upcomingEventReminderButtonRenderer&&N.W&&(N.upcomingEventReminderButtonRenderer.currentState=N.W,N.W=void 0)},
onError:function(){eh5(N)},
onTimeout:function(){eh5(N)}})},eh5=function(N){N.toggleButtonRenderer?(N.toggleButtonRenderer.isToggled=!N.toggleButtonRenderer.isToggled,VR(N)):N.upcomingEventReminderButtonRenderer&&(N.W=void 0,VR(N))},MSm=function(N){if(!N)return null;
switch(N.iconType){case "NOTIFICATIONS":return IyR();case "NOTIFICATIONS_NONE":return tSY();case "NOTIFICATIONS_ACTIVE":return g.mv();default:return null}},ppY=function(N){if(!N.upcomingEventReminderButtonRenderer)return null;
var h=N.W||N.upcomingEventReminderButtonRenderer.currentState;N=g.I(N.upcomingEventReminderButtonRenderer.states||[]);for(var O=N.next();!O.done;O=N.next())if((O=g.X(O.value,cpS))&&O.state===h&&O.button&&g.X(O.button,g.C_))return g.X(O.button,g.C_);return null},ayo=function(N){g.f.call(this,{T:"div",
N:"ytp-offline-slate",C:[{T:"div",N:"ytp-offline-slate-background"},{T:"div",N:"ytp-offline-slate-bar",C:[{T:"span",N:"ytp-offline-slate-icon",C:[{T:"svg",Z:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},C:[{T:"path",Z:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{T:"circle",Z:{cx:"12",cy:"12",r:"3"}}]}]},{T:"span",N:"ytp-offline-slate-messages",C:[{T:"div",N:"ytp-offline-slate-main-text",Z:{"aria-label":"{{label}}"},WB:"{{mainText}}"},{T:"div",N:"ytp-offline-slate-subtitle-text",WB:"{{subtitleText}}"}]},{T:"span",N:"ytp-offline-slate-buttons"}]},{T:"button",M5:["ytp-offline-slate-close-button","ytp-button"],C:[g.Lv()]},{T:"button",M5:["ytp-offline-slate-open-button","ytp-button"],C:[g.QT()]}]});var h=this;this.api=N;this.G=this.W=null;this.background=this.Ir("ytp-offline-slate-background");
this.U=this.Ir("ytp-offline-slate-bar");this.L=new g.YL(function(){g.u9(h.U,"ytp-offline-slate-bar-fade")},15E3);
this.V=!1;this.X=new g.YL(function(){g.u9(h.element,"ytp-offline-slate-collapsed")},15E3);
g.H(this,this.X);g.H(this,this.L);this.countdownTimer=new g.YL(this.dj,1E3,this);this.J(N,"presentingplayerstatechange",this.AZ);this.J(N,"livestatedata",this.N5);this.J(this.Ir("ytp-offline-slate-close-button"),"click",function(){g.u9(h.element,"ytp-offline-slate-collapsed")});
this.J(this.Ir("ytp-offline-slate-open-button"),"click",function(){g.UC(h.element,"ytp-offline-slate-collapsed")});
this.hide();N=this.getVideoData();N.getPlayerResponse()&&(N=N.getPlayerResponse().playabilityStatus)&&this.N5(N);N=this.api.getPresentingPlayerType()===8&&!this.getVideoData().oC;var O=this.api.getPresentingPlayerType()===8;g.GC(this.element,"ytp-offline-slate-premiere-trailer",N);g.GC(this.element,"ytp-offline-slate-hide-background",O)},qbr=function(N,h,O){if(h){var u=h.subtitleText!=null?g.Cv(h.subtitleText):"";
O=O?O:h.mainText!=null?g.Cv(h.mainText):"";var D,U,d,b;h=(b=(D=h.mainText)==null?void 0:(U=D.accessibility)==null?void 0:(d=U.accessibilityData)==null?void 0:d.label)!=null?b:O;N.update({mainText:O,subtitleText:u,label:h});g.GC(N.element,"ytp-offline-slate-single-text-line",!u);g.GC(N.U,"ytp-offline-slate-bar-hidden",!O&&!u)}},Rj=function(N,h){var O=(0,g.to)();
this.trigger=N;this.G=h;this.U=O},SbK=function(N){g.Vq.call(this,N);
var h=this;this.B=!1;this.Y=0;this.L=!1;this.W=new g.YL(function(){gdS(h)},0);
this.G=this.heartbeatParams=null;this.X=!1;this.V=new g.qf(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.eS=new g.Yk(void 0);this.attestationResponse=Promise.resolve(void 0);this.D=Promise.resolve(void 0);this.utcOffsetMinutes=-(new yp5).getTimezoneOffset();this.U=new g.yg(this);g.H(this,this.W);g.H(this,this.U);rpS(this);sur(this);this.U.J(N,"heartbeatparams",this.J8);this.U.J(N,"presentingplayerstatechange",this.iO);this.U.J(N,"videoplayerreset",this.lO);this.U.J(N,g.xm("heartbeat"),
this.onCueRangeEnter);this.X&&this.G&&Jpx(this,void 0,this.G);var O=new g.Ym(Pu(this,!0),0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),u=new g.Ym(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});N.Vq([O,u]);juY(this)},juY=function(N){var h=N.getVideoData();
!h.j("use_rta_for_player")&&h.e3&&(h=h.botguardData)&&g.LD(h,N.player.K())},HbY=function(N){var h,O;
return g.c(function(u){if(u.G==1)return g.E(u,g.qWo(),2);if(!u.W)return N.sequenceNumber>=3?u.return({error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}):u.return(void 0);h=N.getVideoData();O={};return u.return(g.aSq((O.cpn=h.clientPlaybackNonce,O.encryptedVideoId=h.videoId||"",O),1500))})},rpS=function(N){var h=N.getVideoData();
if(h.e3)if(h.j("use_rta_for_player"))N.attestationResponse=HbY(N);else if(h=new g.Tka(h),g.A$.isInitialized()||N.sequenceNumber>=3){var O=Promise,u=O.resolve,D=null;if(h.videoData.vR){var U=g.Wfr(h);if(U){D={};var d={};U=U.split("&");U=g.I(U);for(var b=U.next();!b.done;b=U.next())b=b.value.split("="),b.length===2&&(d[b[0]]=b[1]);d.r1a&&(D.webResponse=d.r1a);d.r1c&&(D.error=TrR[Number(d.r1c)]);D.challenge=h.videoData.vR}}N.attestationResponse=u.call(O,D||void 0)}},WwK=function(N){var h=N.getVideoData();
if(!g.l4(N.getVideoData())||h.kX)return!1;if(h.L){N=h.L.flavor==="playready"&&h.j("html5_innertube_heartbeats_for_playready");var O=h.L.flavor==="widevine"&&h.j("html5_innertube_heartbeats_for_widevine");h=g.At(h.L)&&h.j("html5_innertube_heartbeats_for_fairplay");return!(N||O||h)}return!0},XpV=function(N){if(WwK(N))return!!N.heartbeatParams;
var h=N.getVideoData();return!g.l4(N.getVideoData())||h.yF||h.lM?!!h.heartbeatToken:!1},M4=function(N,h){if(!N.W.isActive()&&N.B){var O=N.getVideoData();
if(XpV(N)||O.isLivePlayback){if(h===void 0)if(N.L)if(N.X)h=7500;else{var u;h=((u=N.heartbeatParams)==null?0:u.interval)?N.heartbeatParams.interval*1E3:N.getVideoData().Bt||6E4}else h=1E3;N.W.start(h)}}},x2R=function(N,h,O){h.hE&&(O=g.KM(O,{internalipoverride:h.hE}));
var u={cpn:h.clientPlaybackNonce};h.contextParams&&(u.context_params=h.contextParams);h.rU&&(u.kpt=h.rU);O=g.KM(O,u);g.tY(O,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(D){if(!N.W.isActive()&&pi(N)){N.V.reset();N.sequenceNumber++;D=D.responseText;var U=fyx(D);if(U){N.player.wf("onHeartbeat",U);var d=U.status==="ok"?U.stop_heartbeat?2:0:U.status==="stop"?1:U.status==="live_stream_offline"?0:-1}else d=(d=D.match(YbY))?d[1]==="0"?0:1:-1;lyY(N,void 0,U,D,d)}},
onError:function(D){pi(N)&&eu(N,!0,"net-"+D.status)},
onTimeout:function(){pi(N)&&eu(N,!0,"timeout")},
withCredentials:!0})},gdS=function(N){var h,O;
g.c(function(u){h=N.player.K();O=N.getVideoData();if(!pi(N))return u.return();if(WwK(N))return ndm(N,h,O),u.l0(0);rpS(N);return g.E(u,Fwx(N,h,O),0)})},ndm=function(N,h,O){var u;
if((u=N.heartbeatParams)!=null&&u.url){var D=g.KM(N.heartbeatParams.url,{request_id:g.$3Y()});O.b0&&(D=g.KM(D,{vvt:O.b0}),O.mdxEnvironment&&(D=g.KM(D,{mdx_environment:O.mdxEnvironment})));g.at(h,O.oauthToken).then(function(U){U&&(D=g.KM(D,{access_token:U}));x2R(N,O,D)})}},pi=function(N){var h=N.getVideoData();
return N.player.getPresentingPlayerType()===3||g.Y(N.player.getPlayerStateObject(N.getPlayerType()),4)?!1:XpV(N)||h.isLivePlayback?!0:(Er(N),!1)},Fwx=function(N,h,O){var u,D,U,d,b,B,C,A,Q,L,z,v,t,R,p,M,a,J,W,F;
return g.c(function(l){if(l.G==1)return u="player/heartbeat",U={videoId:O.videoId,sequenceNumber:N.sequenceNumber,heartbeatServerData:(D=N.fC)!=null?D:O.heartbeatServerData},N.D=N.attestationResponse,O.e3?g.E(l,N.D,3):l.l0(2);l.G!=2&&(U.attestationResponse=l.W);d=g.MA(O);B=(b=d.client)!=null?b:{};B.utcOffsetMinutes=N.utcOffsetMinutes;U.context=d;U.cpn=O.clientPlaybackNonce;if(C=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)B.timeZone=C;A={heartbeatChecks:[]};
if(Q=O.getPlayerResponse())O.heartbeatToken&&(U.heartbeatToken=O.heartbeatToken),(L=Q.playabilityStatus)&&(z=L.liveStreamability)&&z.liveStreamabilityRenderer&&A.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");O.heartbeatToken&&A.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");g.Lp(h)&&(A.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED"),v=ZbV(N),t={},v!==null&&(t.clientPlayerPositionUtcMillis=v),p=(R=N.player.l_())==null?void 0:g.gM(R),a=((M=p)==null?void 0:M.freePreviewWatchedDuration)||
0,a>0&&(t.freePreviewWatchedDuration={seconds:""+a}),A.unpluggedParams=t);U.heartbeatRequestParams=A;O.isLivePlayback?(J=ZbV(N),J!==null&&(U.playbackState||(U.playbackState={}),U.playbackState.playbackPosition={utcTimeMillis:J})):h.j("enable_heartbeat_vod_playback_position")&&(W=k2R(N),W!==null&&(U.playbackState||(U.playbackState={}),U.playbackState.playbackPosition={streamTimeMillis:W}));N.player.publish("heartbeatRequest",U);F={timeout:3E4,onSuccess:function(iY){if(!N.W.isActive()&&pi(N)){var bY=
N.getVideoData(),BR=bY.e3&&N.D==null,oe;bY.e3=!((oe=iY.heartbeatAttestationConfig)==null||!oe.requiresAttestation)||BR;BR=iY.playabilityStatus;oe=JSON.stringify(BR)||"{}";iY.authenticationMismatch&&N.player.GO("authshear",{});var Oa=-1;var Ea=iY.playabilityStatus;Ea&&(N.player.wf("onHeartbeat",Ea),Ea.status==="OK"?Oa=iY.stopHeartbeat?2:0:Ea.status==="UNPLAYABLE"?Oa=1:Ea.status==="LIVE_STREAM_OFFLINE"&&(Oa=0));N.sequenceNumber&&Oa===-1||N.V.reset();N.sequenceNumber++;iY.heartbeatServerData&&(N.fC=
iY.heartbeatServerData);bY.L_=iY;(Ea=iY.playerCueRangeSet)&&g.$4(bY,Ea);iY.playerCueRanges&&iY.playerCueRanges.length>0&&(bY.cueRanges=iY.playerCueRanges);var nx,or;((nx=iY.progressBarConfig)==null?0:nx.progressBarStartPosition)&&((or=iY.progressBarConfig)==null?0:or.progressBarEndPosition)&&(bY.progressBarStartPosition=iY.progressBarConfig.progressBarStartPosition,bY.progressBarEndPosition=iY.progressBarConfig.progressBarEndPosition);bY.compositeLiveIngestionOffsetToken=iY.compositeLiveIngestionOffsetToken;
iY.compositeLiveStatusToken!==bY.compositeLiveStatusToken&&(bY.compositeLiveStatusToken=iY.compositeLiveStatusToken);bY.publish("dataupdated");lyY(N,iY,BR,oe,Oa)}},
onError:function(iY){pi(N)&&eu(N,!0,"net-"+iY.status)},
onTimeout:function(){pi(N)&&eu(N,!0,"timeout")}};
g.at(h,g.oX(O)).then(function(iY){iY&&(F.t6="Bearer "+iY);g.l$(N.eS,u,U,F)});
g.yy(l)})},lyY=function(N,h,O,u,D){D===-1?(O="decode "+g.pR(u,3),eu(N,!1,O)):D===2?(Er(N),N.L=!0):(N.Y=0,N.W.stop(),D===1?(N.L=!1,O&&O.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&N.player.Aa(!0),D="pe."+(O==null?void 0:O.errorCode)+";ps."+(O==null?void 0:O.status),N.player.aI("heartbeat.stop",2,N.GU(u),D),g.DR("heartbeatActionPlayerHalted",Np4(O)),(h==null?0:h.videoTransitionEndpoint)&&O&&(h=h.videoTransitionEndpoint,(u=g.X(h,g.Vi))&&hin(N,u,O,{itct:h==null?void 0:h.clickTrackingParams}))):(N.L=
!0,u=0,N.X&&O&&(u=Jpx(N,h,O),N.player.publish("livestatedata",O)),u?M4(N,u):M4(N)))},Jpx=function(N,h,O){var u=O.liveStreamability&&O.liveStreamability.liveStreamabilityRenderer,D=!(!u||!(u.switchStreamsImmediately||u.transitionTiming&&u.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
h=OUV(N,h,u);var U=N.getVideoData(),d=N.player.getPlayerStateObject(N.getPlayerType()),b=d.isPlaying()&&!g.hx(U)&&!N.player.isAtLiveHead(N.getPlayerType());if(U.K().FF()){var B,C=((B=N.player.wU())==null?void 0:B.zZ())||{};C.status=O.status||"";C.dvr=""+ +b;C["switch"]=""+ +D;C.ended=""+ +!(!u||!u.displayEndscreen);N.player.GO("heartbeat",C)}B=u&&u.broadcastId;C=N.G&&N.G.liveStreamability&&N.G.liveStreamability.liveStreamabilityRenderer&&N.G.liveStreamability.liveStreamabilityRenderer.broadcastId;
var A=B!==C&&B!=null;N.player.j("html5_log_heartbeat_broadcast_change")&&A&&N.player.GO("lbidh",{broadcastId:B},!0);var Q=N.player.j("always_cache_redirect_endpoint");if(b&&!D&&!Q)return h;var L=u&&u.streamTransitionEndpoint&&g.X(u.streamTransitionEndpoint,g.Vi),z=u&&u.transitionTiming;if(z==="STREAM_TRANSITION_TIMING_AT_STREAM_END")N.getVideoData().transitionEndpointAtEndOfStream=L;else if(Q&&!L&&N.getVideoData().transitionEndpointAtEndOfStream)N.getVideoData().transitionEndpointAtEndOfStream=void 0;
else if(!Q&&L&&hin(N,L,O))return h;if(b&&!D&&Q||Q&&L&&(z==="STREAM_TRANSITION_TIMING_IMMEDIATELY"||z==="STREAM_TRANSITION_TIMING_UNSPECIFIED")&&hin(N,L,O))return h;if(O.status.toUpperCase()==="OK"){if(!g.Zt(U)||A){var v={video_id:U.videoId};U.SM&&(v.is_live_destination="1");v.disable_watch_next=!0;v.raw_watch_next_response=U.getWatchNextResponse();v.autonav_state=U.autonavState;v.oauth_token=U.oauthToken;v.VJ=U.VJ;U.V&&(v.vss_credentials_token=U.V,v.vss_credentials_token_type=U.DP);U.b0&&(v.vvt=U.b0);
u=void 0;g.Zt(U)?A&&(u=new Rj("broadcastIdChanged",C+","+B),N.je("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",O)):(B&&(u=new Rj("formatsReceived",""+B)),N.je("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",O));N.player.j("html5_log_heartbeat_broadcast_change")&&A&&N.player.GO("lbidr",{broadcastId:B});N.player.loadVideoByPlayerVars(v,void 0,void 0,void 0,u);return h}N.player.Xz("heartbeat",N.getPlayerType())}u&&
u.displayEndscreen&&(N.offlineSlate?(N=N.offlineSlate,N.V=!0,N.fF&&N.api.Jz()):d.isBuffering()&&(U=((v=N.player.wU())==null?void 0:v.zZ())||{},N.player.GO("hbse",U,!0),N.player.Jz(!0,"h"),N.player.wf("onLiveMediaEnded",O)));return h},OUV=function(N,h,O){return N.player.j("web_player_use_heartbeat_poll_delay_ms")&&(N=Number(h==null?void 0:h.pollDelayMs))?N:(O=Number(O==null?void 0:O.pollDelayMs))?O:0},eu=function(N,h,O){if(!N.W.isActive()){N.W.stop();
N.Y++;var u=h?"heartbeat.net":"heartbeat.servererror";var D=N.getVideoData();if(D.mQ||h&&!g.l4(N.getVideoData())&&!XpV(N)&&D.isLivePlayback)D=!1;else{var U,d;((d=N.heartbeatParams)==null?0:d.retries)?U=N.heartbeatParams.retries:U=D.Yf||5;D=N.Y>=U}D?(g.DR("heartbeatActionPlayerHalted",h?{enforcedPolicyToHaltOnNetworkFailure:!0}:Np4()),(h=N.getVideoData())&&h.isLivePlayback?N.player.aI(u,1,"Video playback interrupted. Please try again.",O):N.player.aI(u,1,"Sorry, there was an error licensing this video.",
O)):(M4(N,N.V.getValue()),g.gp(N.V))}},Np4=function(N){var h={enforcedPolicyToHaltOnNetworkFailure:!1};
N&&(h.serializedServerContext=N.additionalLoggingData);return h},Er=function(N){N.Y=0;
N.W.stop();N.L=!1;N.sequenceNumber=0},sur=function(N){var h=N.getVideoData(),O=N.player.K();
if(h.isLivePlayback)if(g.Rc(O.L)){N.X=!0;N.B=!0;if(!g.v1(O)||g.Lp(O))N.offlineSlate=new ayo(N.player),g.H(N,N.offlineSlate),g.O9(N.player,N.offlineSlate.element,4);(h=h.getPlayerResponse())&&h.playabilityStatus&&(N.G=h.playabilityStatus);var u;((u=N.G)==null?void 0:u.status)!=="UNPLAYABLE"&&(N.G?(u=OUV(N,void 0,N.G.liveStreamability&&N.G.liveStreamability.liveStreamabilityRenderer))?M4(N,u):M4(N,7500):M4(N,Pu(N,!0)))}else N.player.aI("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK",
"nolive.1");else g.tj(h.D,"heartbeat")&&N.player.Xz("heartbeat",N.getPlayerType())},hin=function(N,h,O,u){var D=h&&h.videoId;
return D?(N.player.Yz(D,Object.assign({},{autonav:"1"},u||{}),void 0,!0,!0,h,g.oX(N.getVideoData())),N.je("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",O),!0):!1},ZbV=function(N){return(N=N.player.getProgressState(N.getPlayerType()).ingestionTime)&&isFinite(N)?""+Math.floor(N*1E3):null},k2R=function(N){return(N=N.player.getCurrentTime(N.getPlayerType()))&&isFinite(N)?""+Math.floor(N*1E3):null},Pu=function(N,h){h=h===void 0?!1:h;
N=N.getVideoData();return N.j("html5_use_server_init_heartbeat_delay")?isNaN(N.Bt)?15E3:N.Bt:h?1E3:2E3},fyx=function(N){try{var h=JSON.parse(N);
return h!=null?h:void 0}catch(O){}},uoo={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},DfY=uoo;DfY=uoo;
var TrR=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],Ufo={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.w=yp5.prototype;g.w.nG=DfY.FIRSTDAYOFWEEK;g.w.z0=DfY.FIRSTWEEKCUTOFFDAY;
g.w.clone=function(){var N=new yp5(this.date);N.nG=this.nG;N.z0=this.z0;return N};
g.w.getFullYear=function(){return this.date.getFullYear()};
g.w.getYear=function(){return this.getFullYear()};
g.w.getMonth=function(){return this.date.getMonth()};
g.w.getDate=function(){return this.date.getDate()};
g.w.getTime=function(){return this.date.getTime()};
g.w.getDay=function(){return this.date.getDay()};
g.w.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.w.getUTCMonth=function(){return this.date.getUTCMonth()};
g.w.getUTCDate=function(){return this.date.getUTCDate()};
g.w.getUTCDay=function(){return this.date.getDay()};
g.w.getUTCHours=function(){return this.date.getUTCHours()};
g.w.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.w.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.w.set=function(N){this.date=new Date(N.getFullYear(),N.getMonth(),N.getDate())};
g.w.setFullYear=function(N){this.date.setFullYear(N)};
g.w.setYear=function(N){this.setFullYear(N)};
g.w.setMonth=function(N){this.date.setMonth(N)};
g.w.setDate=function(N){this.date.setDate(N)};
g.w.setTime=function(N){this.date.setTime(N)};
g.w.setUTCFullYear=function(N){this.date.setUTCFullYear(N)};
g.w.setUTCMonth=function(N){this.date.setUTCMonth(N)};
g.w.setUTCDate=function(N){this.date.setUTCDate(N)};
g.w.add=function(N){if(N.years||N.months){var h=this.getMonth()+N.months+N.years*12,O=this.getYear()+Math.floor(h/12);h%=12;h<0&&(h+=12);a:{switch(h){case 1:var u=O%4!=0||O%100==0&&O%400!=0?28:29;break a;case 5:case 8:case 10:case 3:u=30;break a}u=31}u=Math.min(u,this.getDate());this.setDate(1);this.setFullYear(O);this.setMonth(h);this.setDate(u)}N.days&&(O=this.getYear(),h=O>=0&&O<=99?-1900:0,N=new Date((new Date(O,this.getMonth(),this.getDate(),12)).getTime()+N.days*864E5),this.setDate(1),this.setFullYear(N.getFullYear()+
h),this.setMonth(N.getMonth()),this.setDate(N.getDate()),tH(this,N.getDate()))};
g.w.equals=function(N){return!(!N||this.getYear()!=N.getYear()||this.getMonth()!=N.getMonth()||this.getDate()!=N.getDate())};
g.w.toString=function(){var N=this.getFullYear(),h=N<0?"-":N>=1E4?"+":"";return[h+m25(Math.abs(N),h?6:4),m25(this.getMonth()+1,2),m25(this.getDate(),2)].join("")+""};
g.w.valueOf=function(){return this.date.valueOf()};var dfY=new g.te("addUpcomingEventReminderEndpoint");var Gvx=new g.te("removeUpcomingEventReminderEndpoint");var bUx=new g.te("updateUpcomingEventReminderButtonStateCommand");var Rhm=new g.te("upcomingEventReminderButtonRenderer"),cpS=new g.te("upcomingEventReminderButtonStateRenderer");g.K($2,g.ib);
$2.prototype.updateMenuItems=function(){var N=this,h=VSV(this),O=0;O=0;for(var u={};O<h.length;u={fm:void 0},O++){var D=this.U[O];D||(D=new g.f({T:"div",N:"ytp-reminder-menu-item",Z:{role:"menuitem",tabindex:"0"},C:[{T:"div",N:"ytp-reminder-menu-item-icon",WB:"{{icon}}"},{T:"div",N:"ytp-reminder-menu-item-label",WB:"{{text}}"}]}),u.fm=O,D.listen("click",function(d){return function(){var b=d.fm;N.MS();b=VSV(N)[b];N.publish("reminderMenuItemClicked",b.serviceEndpoint||b.command)}}(u)),D.rf(this.items),
this.U[O]=D);
var U=h[O];u=null;switch(U.icon&&U.icon.iconType){case "NOTIFICATIONS":u=IyR();break;case "NOTIFICATIONS_NONE":u=tSY();break;case "NOTIFICATIONS_ACTIVE":u=g.mv()}U=U.text?g.Cv(U.text):"";D.update({icon:u,text:U})}for(;O<this.U.length;)this.U.pop().dispose();O===0?this.MS():this.Vd(this.G)};
$2.prototype.hide=function(){this.G&&this.G.removeAttribute("aria-haspopup");g.ib.prototype.hide.call(this)};
$2.prototype.show=function(){this.G&&this.G.setAttribute("aria-haspopup","true");g.ib.prototype.show.call(this)};
$2.prototype.q5=function(){g.Uu(this.U);g.ib.prototype.q5.call(this)};g.K(yR,g.f);
yR.prototype.V=function(){if(this.toggleButtonRenderer){var N=this.toggleButtonRenderer;N.isToggled?this.U(N.toggledServiceEndpoint):this.U(N.defaultServiceEndpoint);N.isToggled=!N.isToggled;VR(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.G&&this.G.fF)this.G.MS();else{var h=ppY(this);h&&this.U(h.serviceEndpoint||h.command);h=((N=g.X(h==null?void 0:h.command,g.Ql))==null?void 0:N.commands)||[];a:{N=g.I(h);for(var O=N.next();!O.done;O=N.next()){var u=h=void 0;if(O=(h=g.X(O.value,g.PD5))==
null?void 0:(u=h.popup)==null?void 0:u.menuPopupRenderer){N=O;break a}}N=void 0}this.G||(this.G=new $2(this.S,this.L),this.G.rf(this.element),g.H(this,this.G),this.G.subscribe("reminderMenuItemClicked",this.U,this));h=this.G;h.menuPopupRenderer=N;h.updateMenuItems()}};
yR.prototype.U=function(N){var h=g.X(N,dfY),O=g.X(N,Gvx);if(N&&(h||O)){if(h){var u=h;var D="notification/add_upcoming_event_reminder"}else O&&(u=O,D="notification/remove_upcoming_event_reminder");if(D&&u&&u.params)for(Edj(this,D,u.params),N=g.I(u.commands||[]),h=N.next();!h.done;h=N.next())if((h=h.value)&&g.X(h,bUx)){this.W=g.X(h,bUx).state;VR(this);break}}};g.K(ayo,g.f);g.w=ayo.prototype;g.w.getPlayerType=function(){if(this.api.getPresentingPlayerType()===8)return 1};
g.w.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.w.N5=function(N){var h,O,u=N==null?void 0:(h=N.liveStreamability)==null?void 0:(O=h.liveStreamabilityRenderer)==null?void 0:O.offlineSlate;if(u){this.W=N;h=u.liveStreamOfflineSlateRenderer;h.canShowCountdown?this.dj():qbr(this,h);var D,U,d,b;if(O=N==null?void 0:(D=N.liveStreamability)==null?void 0:(U=D.liveStreamabilityRenderer)==null?void 0:(d=U.offlineSlate)==null?void 0:(b=d.liveStreamOfflineSlateRenderer)==null?void 0:b.thumbnail){D=0;U=null;d=O.thumbnails;for(b=0;b<d.length;b++)d[b].width>
D&&(D=d[b].width||0,U=d[b].url);U&&(this.background.style.backgroundImage="url("+U+")")}else this.background.style.backgroundImage="";h.actionButtons||h.reminderButton?(this.G||(this.G=new yR(this.api),this.G.rf(this.Ir("ytp-offline-slate-buttons")),g.H(this,this.G)),PKY(this.G,h.actionButtons&&h.actionButtons[0],h.reminderButton)):this.G&&PKY(this.G,null,null);this.W=N}else this.W=null;this.AZ()};
g.w.AZ=function(N){if(this.api.getPresentingPlayerType()===8)var h=!0;else{var O=this.api.getPlayerStateObject(),u=this.getVideoData();h=u.isLivePlayback&&(O.isBuffering()||g.Y(O,2)||g.Y(O,64));var D=u.autonavState===2&&g.Y(O,2);O=O.isPlaying()&&!g.hx(u)&&!this.api.isAtLiveHead(void 0,!0);h=h&&!O&&!D}h&&this.W?this.fF?(N==null?0:g.Ar(N,2))&&!this.getVideoData().oC&&(g.UC(this.element,"ytp-offline-slate-collapsed"),this.X.stop(),g.UC(this.U,"ytp-offline-slate-bar-fade"),this.L.start()):(this.show(),
this.X.start(),this.api.publish("offlineslatestatechange"),this.V&&this.api.Jz()):this.fF&&(this.hide(),this.api.publish("offlineslatestatechange"))};
g.w.dj=function(){var N,h,O,u,D=(N=this.W)==null?void 0:(h=N.liveStreamability)==null?void 0:(O=h.liveStreamabilityRenderer)==null?void 0:(u=O.offlineSlate)==null?void 0:u.liveStreamOfflineSlateRenderer;D&&(N=Math.floor(g.Aj()/1E3),h=D.canShowCountdown&&Number(D.scheduledStartTime),!h||h<=N?(qbr(this,D),this.countdownTimer.stop()):(qbr(this,D,g.IH(h-N)),g.la(this.countdownTimer)))};
g.w.q5=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.f.prototype.q5.call(this)};Rj.prototype.W=function(N){return this.trigger&&N.trigger?this.trigger===N.trigger&&this.G===N.G:!1};
Rj.prototype.isExpired=function(){return(0,g.to)()-this.U>6E4};
Rj.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.G};g.K(SbK,g.Vq);g.w=SbK.prototype;g.w.q5=function(){Er(this);this.player.SV("heartbeat");g.Vq.prototype.q5.call(this)};
g.w.onCueRangeEnter=function(){this.B=!0;M4(this,Pu(this))};
g.w.J8=function(N){this.heartbeatParams=N;M4(this,Pu(this))};
g.w.iO=function(N){var h;this.player.getPresentingPlayerType()!==8&&((h=this.G)==null?void 0:h.status)!=="UNPLAYABLE"&&(g.Y(N.state,2)||g.Y(N.state,64)?(Er(this),this.X&&(this.B=!0,M4(this,Pu(this,!0)))):(g.Y(N.state,1)||g.Y(N.state,8))&&M4(this,Pu(this)))};
g.w.lO=function(){this.player.getPresentingPlayerType()!==3&&M4(this,Pu(this))};
g.w.getPlayerType=function(){if(this.player.getPresentingPlayerType()===8)return 1};
g.w.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.w.w6=function(N){switch(N){case 4:case 3:return!1}return!0};
g.w.je=function(N,h,O){N={trigger:N,reason:h};O&&(N.serializedServerContext=O.additionalLoggingData);g.DR("heartbeatActionPlayerTransitioned",N)};
g.w.GU=function(N){var h="LICENSE",O=fyx(N);if(O)return O.reason||g.Yo[h]||"";if(N=N.match(YbY))if(N=Number(N[1]))h=(h=Ufo[N.toString()])?h:"LICENSE";return g.Yo[h]||""};
g.w.rd=function(){return!!this.offlineSlate&&this.offlineSlate.fF};
var YbY=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.yq("heartbeat",SbK);})(_yt_player);
